### ISSUE TITLE
Improve the landing page

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/tool-suite-X#122]
A user-focused, simple landing page for docs that is not encumbered by technical language and that explains what the ODK-X tools are used for and whether it is appropriate for their needs.

From the convening roadmap: https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit

**Comment by maprehensive** [comment]
@wbrunette @elmps2018 @jbeorse @linl33 
I think this issue is complete. There may be intention to to make further improvements to the landing page through the docs process, but they can be captured in upcoming issues. Any objections to marking this as complete?

**Comment by linl33** [comment]
I agree with Ben.
