### ISSUE TITLE
Document anonymous access for Sync Endpoint

### ISSUE THREAD

**Issue by linl33** [opendatakit/tool-suite-X#224]
Document how to enable anonymous access for Sync Endpoint.

Anonymous access can be enable through Sync Endpoint's `security.properties`.
https://github.com/odk-x/sync-endpoint-default-setup/blob/0d97f322b6f3c48f86cdb47c9c1c7acf3f7bfb93/config/sync-endpoint/security.properties#L76-L77

The documentation should include 
 - how to set up a new Sync Endpoint instance with anonymous access
 - how to turn on/off anonymous access for an existing instance

**Comment by ADISKING1** [comment]
@linl33 can I work on this?

**Comment by wbrunette** [comment]
@ADISKING1 I have assigned the issue. Thanks for documenting this!
