### ISSUE TITLE
Change default server URL

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#226]
Change the default URL string "sync_default_server_url" from http://opendatakit-2.appspot.com to https://tables-demo.odk-x.org.

https://github.com/odk-x/services/blob/master/services_app/src/main/res/values/strings.xml#L188

Also remember to change it in the Spanish strings as well.

https://github.com/odk-x/services/tree/master/services_app/src/main/res/values-es

**Comment by VarunT11** [comment]
@wbrunette Can I work on it?

**Comment by wbrunette** [comment]
@VarunT11 I have assigned the issue to you.

**Comment by SondosAhmed** [comment]
I'd like to work on this
