### ISSUE TITLE
Contributors Guide: Document Build Variants

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#229]
As part of a new contributor's guide document the following:
1) What are build variants and why we use them for dependencies 
2) Which build variants correspond to the source branches 'development', 'demo', and 'master'
3) How are build variants accounted for at the gradle command line
4) How to change build variants in Android studio

**Comment by khushishikhu** [comment]
@wbrunette Can I work on this issue?

**Comment by wbrunette** [comment]
@khushishikhu this is not an 'easy win' or 'good first issue'. However, it is a great way to learn about how the ODK-X Android development environment is set up. I am happy for you to work on it. Let me know what you decide.

Here are some helpful hints/resources:
1) https://developer.android.com/studio/build/build-variants
2) To change/check your build variant in Android Studio you first need to view the variant window. Go to View->Tool Window->Build Variants
3) An example of the gradle configuration that decides on the dependencies based. From the build.grade file in Services:
  ```
  if (libraryProjectPath.exists() && gradle.useLocal) { // Local project is favoured
        implementation project(libraryProjectName)
    } else {
        demoImplementation(group: groupId, name: libraryDemoArtifactName, classifier: demoRelease,
                version: latestVersion, ext: 'aar')
        masterImplementation(group: groupId, name: libraryMasterArtifactName, classifier: masterRelease,
                version: masterArtifactVersion, ext: 'aar')
        snapshotImplementation(group: groupId, name: librarySnapshotArtifactName,
                classifier: snapshotRelease, version: latestVersion, ext: 'aar')
    }
```

**Comment by khushishikhu** [comment]
@wbrunette Yes currently I am researching on building up this project from the source code and read about it a lot and still working until I successfully made it up on my device.
Since it is document for contributors , we will describe all the three variants gradle build , where 
development :- must be the main branch for the mentor's use 
demo:- could be use for testing any PR 
master:- The branch provided to the contributors like me to fork and made up required changes.
And write the documentation accordingly by covering all the points you have mentioned in the issue description

please let me know if I understood correct ? as I don't have much experience with android.

**Comment by wbrunette** [comment]
@khushishikhu sounds like you are on the right track. I will assign the issue to you.

Your description of the branches need some refinement. Here are updated description, please feel free to improve the descriptions even more.
development :- the branch where new development, upgrades, and features are contributed and tested 
demo:- This branch is the last stable version of development. This provides a staging area used for testing before moving to an official release. This is where preview releases are staged.
master:- The current stable release.

**Comment by khushishikhu** [comment]
@wbrunette Thank you!! I will try my best to make it and provide you with more informative description to be added. Thank you for your guidance

**Comment by khushishikhu** [comment]
![Capture](https://user-images.githubusercontent.com/65439761/113469967-6e6f4a00-946f-11eb-8155-a7ebec8b5376.PNG)
@wbrunette I war trying to add the build variants with the dimension "version" but when I clicked to re-build the application, it shows the error I am not getting why it is occurring . can you please help me to know why am I facing this or what can be the thing I am doing wrong?

**Comment by wbrunette** [comment]
@khushishikhu, first I want to make sure you know that to solve this issue you do NOT need to make a new variant. You only need to document ODK-X's 3 variants and provide screenshots of the variants window and describe how to change between the 3 ODK-X build variants.

Therefore, I assume you are trying to add a new flavorDimension just for the fun of it to learn. The flavor dimensions are part of the gradle build system. When I am debugging problems with gradle I generally use the command line to try to understand the problem as you can issue lots of gradle commands that might help to better understand and solve the issue. With the limited information provided I do not know why, but the important point is you do need to create a new build variant to complete this issue.

**Comment by khushishikhu** [comment]
Okay I surely got your point @wbrunette . Thank you so much for clarifying me these points. yes I was trying to made all the 3 variants ( development, master, demo) for first testing my self before writing the contributor's document Therefore I was facing this issue. But now as you have told me that just to write the document, so I will focus on that and will send you the PR shortly.

**Comment by wbrunette** [comment]
@khushishikhu if you don't modify the build.gradle file it will work. Technically variants are a combination of flavors and dimensions. I noticed in the screenshot i see modifications of dimensions, so once you start altering the variants I am not sure what the bug is. If you do not modify build.gradle all 3 variants should compile correctly.

**Comment by khushishikhu** [comment]
@wbrunette just one thing I want to confirm that I have to make the document for contributors guide in ODK-X tool-suite-X ,right?

**Comment by wbrunette** [comment]
There is a contributors section in docs, but it only has a subsection for contributing to docs. It would be good to make another subsection about contributing to the tools. Then link it from the README of the the various repos like Services, Tables, and Survey.

**Comment by wbrunette** [comment]
@elmps2018 might have some thoughts on this.

**Comment by elmps2018** [comment]
There is a section about contributing to the tools: https://docs.odk-x.org/advanced-topics-developer/ but we need to figure out what goes there v. the repos and also have them point to e/o

**Comment by khushishikhu** [comment]
@elmps2018 @wbrunette  can you please tell me where exactly I should write the contributing to the tools document because I am getting confused in two opinions. Currently I have started with making a subsection under contributing section in docs as I have been told before. Thank you!!

**Comment by wbrunette** [comment]
@khushishikhu follow what @elmps2018 suggests for the location/placement of the instructions.
