### ISSUE TITLE
Buggy Grid Form Rendering in Survey Application

### ISSUE THREAD

**Issue by swaingotnochill** [opendatakit/tool-suite-X#232]
Application 
Survey 2.1.7

In survey application, while creating an instance in Grid Form, the table rendered is improper in vertical view of android phone along which also causes the next option on top app bar to display irregularly. 

Steps to reproduce:
1.Click on Grid Form.
2.Create an instance prompt.
3.The table created will be not displayed properly along with the top app bar.

Screen Recording :
https://user-images.githubusercontent.com/54025913/113281835-b709f480-9303-11eb-9b29-4bad90e11165.mp4

**Comment by linl33** [comment]
Bug in https://github.com/odk-x/app-designer/blob/master/app/config/tables/gridScreen/forms/gridScreen/comparison_screen.handlebars

**Comment by brngylni** [comment]
Can I work on it?

**Comment by swaingotnochill** [comment]
@brngylni I am working on this issue as i raised it. Meanwhile, you can look into other issues in the issue section and see if something fits you.

**Comment by wbrunette** [comment]
@swaingotnochill A Pull Request is between two branches, so your changes for the rating prompt are in this Pull Request. Please use a separate branch for each Pull Request.

Additionally please open your Pull Request against the odk-x/development branch. You will see that @linl33 changed your last pull request to point to the development branch. The development branch is where new development, upgrades, and features are contributed and tested. The master branch is the current stable release.

**Comment by swaingotnochill** [comment]
@wbrunette okay, I will close those two pull request and open a new one from the different branches to the development branch.
