### ISSUE TITLE
Incorrect button label for upload file chooser in suitcase

### ISSUE THREAD

**Issue by Shubhamr837** [opendatakit/tool-suite-X#233]
In the suitcase application if file chooser is opened for the upload option the file chooser opens with title "save" and button label "save" .
Whereas "save" should only be used for download option .

Steps to reproduce :
1 ) Login to suitcase .
2 ) Click on upload tab.
3 ) open file chooser 

Button will be labeled as "save" and title of the window will also be "save"

Possible solution is to provide a custom label like "select" to the file chooser object.

**Comment by Shubhamr837** [comment]
any admin please verify if this is a valid issue or not ? 
I would like to work on this if it is .

**Comment by wbrunette** [comment]
@Shubhamr837 go ahead and work on this issue. There might be some constraint that you run into. Let us know how it goes.

**Comment by Shubhamr837** [comment]
Thanks a lot  @wbrunette , I will update if I face any problem
