### ISSUE TITLE
Video: Changing the language in ODK-X Survey

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#235]
Make a video showing how to change the language in ODK-X Survey for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by Shubhamr837** [comment]
Hi @elmps2018 can I work on this ?

**Comment by elmps2018** [comment]
@Shubhamr837 yes! I just assigned you! Thanks for taking this on!

**Comment by Shubhamr837** [comment]
@elmps2018 can you please help me with this . In my survey application it only shows the current device language, when I change the device language to espagnol it changes and shows everything in Spanish.  It never shows both the language together. 
Screenshots : 
With device language as english : 
![Screenshot_20210407-225706_ODK-X Services](https://user-images.githubusercontent.com/45128519/113909037-dec1f680-97f4-11eb-8b8d-c7b969049877.jpg)

With device language as spanish : 
![Screenshot_20210407-225816_ODK-X Services](https://user-images.githubusercontent.com/45128519/113909165-fef1b580-97f4-11eb-8a4a-36e1e8c16aca.jpg)

**Comment by elmps2018** [comment]
Hi @Shubhamr837! Sorry for the confusion, it looks like  you might be in services rather than Survey? In Survey you can change the language using the contents menu: https://docs.odk-x.org/survey-using/?highlight=contents but only if you have an app with multiple languages set up. I am not sure which but I think some of the default ones have multiple languages so you can show this functionality.

**Comment by wbrunette** [comment]
You need the multiple languages set in the form. Then you can change the language once in the form.

**Comment by divyankachaudhari** [comment]
If this is not done yet, can I take this on?

**Comment by Shubhamr837** [comment]
Hi @divyankachaudhari , I am unable to create a form with multiple languages. You can go ahead with this. I have unassigned myself.

**Comment by elmps2018** [comment]
@divyankachaudhari I have assigned you, thanks for working on this issue! This demo https://docs.odk-x.org/cold-chain-tour-health-facilities/ has multiple languages if you want to use that as the example (there are other apps with multiple languages as well).

**Comment by divyankachaudhari** [comment]
Thank you very much, but I'm unable to do it :( Same issues as @Shubhamr837

**Comment by EstherPhebe** [comment]
@elmps2018 I want to work on this, please assign it to me.

**Comment by elmps2018** [comment]
@EstherPhebe assigned to you! Please note that this demo https://docs.odk-x.org/cold-chain-tour-health-facilities/ has multiple languages if you want to use that as the example (there are other apps with multiple languages as well). You can use the demo here, you don't have to create a form.

**Comment by EstherPhebe** [comment]
@elmps2018 I hope you are well

https://drive.google.com/folderview?id=1QVq1-IHGl6Q224xiZcAtdQnBJLypO8Mr

The folder has the video and accompanying .srt files.  Please let me know what you think

**Comment by elmps2018** [comment]
@EstherPhebe thanks so much this is great! Just uploaded to the Youtube Channel!
