### ISSUE TITLE
Video: Navigating with contents menu in ODK-X Survey

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#236]
Make a video showing how to navigate with the contents menu in ODK-X Survey for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by swaingotnochill** [comment]
I would also like to work on this one too. It will be a refreshing break from hard coding to work on this issues.

**Comment by wbrunette** [comment]
@swaingotnochill I have assigned this issue to you because you have 1 issue pending review. Please note that our limit is 2 assigned issues that are incomplete.

**Comment by aditisingh2412** [comment]
Hey! Can I work on this issue?

**Comment by linl33** [comment]
@swaingotnochill Can you give us an update on this issue. Let us know if you have any questions or would like to be unassigned.

**Comment by swaingotnochill** [comment]
@linl33 I actually want to know is the navigation we want is  Next or Previous button in forms and finalizing it or it is something else.

**Comment by wbrunette** [comment]
@elmps2018 what are your thoughts?

**Comment by elmps2018** [comment]
@swaingotnochill this issue is about navigating with the contents menu. See the contents part here: https://docs.odk-x.org/survey-using/?highlight=contents#navigating-a-form

You can use the contents menu to go to and see entered data. One of the common confusing things about the contents menu is that when you do this and then go "back" it follows the same path you used to get there. So showing both opening the contents menu and going to different points in a survey and then showing and explaining how back is path-dependent would be important for demoing in the video.

**Comment by EstherPhebe** [comment]
@swaingotnochill I see that your last update was 9 days ago, are you still working on this or can I work on it?

**Comment by swaingotnochill** [comment]
@EstherPhebe plzz go ahead...I am busy with my end term exam and final project..

**Comment by elmps2018** [comment]
@swaingotnochill thanks for the update! 
@EstherPhebe assigned to you thanks for working on this!

**Comment by EstherPhebe** [comment]
Hello @elmps2018,
The video and caption files are in the link folder 

[https://drive.google.com/folderview?id=1PEMEu2b9rEL9872aj1FINYObXiBpjvpe](https://drive.google.com/folderview?id=1PEMEu2b9rEL9872aj1FINYObXiBpjvpe)

**Comment by elmps2018** [comment]
@EstherPhebe great thanks for doing the captions too! Just added to the YouTube channel!
