### ISSUE TITLE
Video: Saving and finalizing in ODK-X Survey

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#237]
Make a video showing how to save and finalize in ODK-X Survey for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by swaingotnochill** [comment]
Can I work on this one ?

**Comment by emeka-okechukwu-dev** [comment]
@swaingotnochill hope it's fine I take this one on since it's not been assigned yet and I think you've reached a limit?

@elmps2018, I've already made a video accessible here: https://drive.google.com/file/d/1KSR6r006jCLI8xLBxtbGk_aWMG7UdxSk/view?usp=sharing

**Comment by emeka-okechukwu** [comment]
@swaingotnochill hope it's fine I take this one on since it's not been assigned yet and I think you've reached a limit?

Hey @elmps2018, can I be assigned to this issue?

I've already made a video accessible here:

https://drive.google.com/file/d/1KSR6r006jCLI8xLBxtbGk_aWMG7UdxSk/view?usp=sharing

Please lemme know what you think.

**Comment by elmps2018** [comment]
Hi @emeka-okechukwu-dev! This looks like the right sort of information, but could you highlight/circle what you are selecting since it is not always clear? Thanks!

**Comment by emeka-okechukwu** [comment]
Hi @elmps2018, sure I can work on that

**Comment by elmps2018** [comment]
Hi @emeka-okechukwu-dev are you still working on this issue? @iamhks completed something similar in #241.

**Comment by emeka-okechukwu** [comment]
Hi @elmps2018, so sorry for the delay but yeah I am still working on it. But since @iamhks seems to have done something similar then there's no problem.

Anyhow, I can continue if you'd like me to?

**Comment by elmps2018** [comment]
Hi @emeka-okechukwu-dev! If you can show the different kinds of saves, the finalize vs. incomplete vs. ignore that was not done and would still be helpful. @iamhks showed save and finalize with adding instances, but there are the different types of saves to video still.

**Comment by iamhks** [comment]
Yes, you can find that here: https://docs.odk-x.org/survey-using/#saving-a-form-instance

**Comment by khushishikhu** [comment]
@elmps2018 If someone isn't working on this issue. can I start working on this one?

**Comment by emeka-okechukwu-dev** [comment]
Hi @khushishikhu, unfortunately currently working on it and will have a turnover by Saturday.

Sorry about the delay guys been balancing with school work previously and just got free.

**Comment by emeka-okechukwu** [comment]
Hi @khushishikhu, unfortunately, I'm currently working on it and will have a turnover soon.

Sorry about the delay guys been extremely busy and just got free.

**Comment by khushishikhu** [comment]
@emeka-okechukwu-dev oh it's okay. I do understand. Please take your time. Thank you for letting me know.

**Comment by EstherPhebe** [comment]
@emeka-okechukwu-dev Hi, please let me know if you have an update on this? I'd like to work on it.

**Comment by emeka-okechukwu** [comment]
Hi @EstherPhebe, just finished the school semester a couple of weeks ago. Was also finding out the best way to show highlight/circle what I select for a while and just finished with the best way to do it.

**Comment by emeka-okechukwu** [comment]
Hi @elmps2018, my apologies my the delay, was finding out the best way to highlight my selections

Here's the best way I found (prolonging the selection):

https://drive.google.com/file/d/1tTWVkza9avAg7BM2RLblLuYVbCods17n/view?usp=sharing

Please lemme know what you think

**Comment by elmps2018** [comment]
@emeka-okechukwu-dev this looks good to me. 
@EstherPhebe did you have any comments? If this looks good to you, I sent you the Youtube invite, do you want to upload this video?

**Comment by EstherPhebe** [comment]
Hi @elmps2018, it looks good. I'll upload it, I'm still figuring my way around the YouTube studio. Thanks @emeka-okechukwu-dev
