### ISSUE TITLE
Video: Importing data in ODK-X Tables

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#238]
Make a video showing how to import data in ODK-X Tables for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by chinenyeokafor** [comment]
@elmps2018 Can I work on this?

**Comment by wbrunette** [comment]
@chinenyelilian  yes! I just assigned you! Thanks for taking this on!

**Comment by chinenyeokafor** [comment]
@elmps2018 The ODK-X table app stops/Crashes at configuring ODK-X table. Please what could be the cause?

**Comment by wbrunette** [comment]
@chinenyelilian What version of Android are you using? Android 11 has a known problem that will be fixed in version 2.1.8 (hopefully released this week). You can use any version of Android between Android 4.4 to Android 10.

**Comment by chinenyeokafor** [comment]
@wbrunette  My android version is 9

**Comment by wbrunette** [comment]
@chinenyelilian can you provide more specifics on what you are doing? Are you compiling the code and installing it on a device or did you use a web browser to download the apks? If so which version?

**Comment by chinenyeokafor** [comment]
I downloaded the app and the prerequisites from the links: https://github.com/odk-x/services/releases/latest
https://github.com/odk-x/tables/releases/latest
https://github.com/openintents/filemanager/releases.

The ODK-X table application doesn't move past the initial configuration stage.

**Comment by elmps2018** [comment]
Do the other apps work? Also make sure the install from unknown sources is checked per the directions:
https://docs.odk-x.org/basics-install/
I have occasionally had problems with install when it isn't

**Comment by chinenyeokafor** [comment]
Thank you @elmps2018 and @wbrunette,I have setup the app successfully.

This is the link to the video: https://drive.google.com/file/d/1h6i41n3XbJxH86-ZTRRmLmt0KxyT71c5/view
Kindly review and share feedback.

**Comment by elmps2018** [comment]
Hi @chinenyelilian this looks good to me! @wbrunette do you want to check and see if you have any feedback? If it looks all set I can add to the YouTube.

**Comment by wbrunette** [comment]
@chinenyelilian good job! @elmps2018 The only thing I would add is in the description of the video that the CSV must match the table's format. However, I think just adding that requirement to the description when uploading the video to YouTube will be sufficient.

**Comment by elmps2018** [comment]
Good point @wbrunette! @chinenyelilian could you add narration or a picture to that effect? I worry that folks don't read the descriptions so having it in the video would be great.

**Comment by chinenyeokafor** [comment]
@elmps2018 Okay, will do

**Comment by chinenyeokafor** [comment]
@elmps2018 and @wbrunette I have done the necessary addition as advised. Please see the link to the video: https://drive.google.com/file/d/1hpL8W9T6CcJGKpLLGT2K1zjANF5VgdVk/view?usp=drivesdk
Kindly review and share feedback.

Thank you.

**Comment by elmps2018** [comment]
This is great, super helpful details, I just uploaded to the YouTube channel, thanks!
