### ISSUE TITLE
Video: Exporting data from ODK-X Tables

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#239]
Make a video showing how to export data in ODK-X Tables for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by iamhks** [comment]
Hi, can I work on this issue?

**Comment by iamhks** [comment]
Hi @elmps2018, I worked on this issue.
Here is the link to the video: https://drive.google.com/file/d/1RNRySQODzPZ05op0f-T0NiGixt4q5sq-/view?usp=sharing
Please review and tell me if I need to make any changes.

I did not include setting up with the services app first because, when someone is exporting that would have been done already and is needed only when importing.

**Comment by wbrunette** [comment]
@iamhks I have assigned the issue to you. @elmps2018 will review your link.

**Comment by iamhks** [comment]
@elmps2018 It would be helpful if you could review the link, since I can then follow those instructions for another video issue.

**Comment by elmps2018** [comment]
Hi @iamhks! The content looks good here, but it was sometimes hard to tell what you are selecting. Going a bit slower and also highlighting/circling what you select would help!

**Comment by iamhks** [comment]
Thanks @elmps2018 , here's the updated link: https://drive.google.com/file/d/1RvCTBqGPfkry8lc9Uy3_QTpu22AIrUsW/view?usp=sharing

**Comment by elmps2018** [comment]
@iamhks this looks good! I will go ahead and get it processing with YouTube to add to the channel, thanks!

**Comment by iamhks** [comment]
Hi @elmps2018 I see the video has been added to the channel. Hopefully, this issue can be closed now. Thanks.

**Comment by elmps2018** [comment]
@iamhks oh yes closing now!
