### ISSUE TITLE
Video: Selecting the form and instance in ODK-X Survey

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#240]
Make a video showing how to select the form and the instance in ODK-X Survey for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by swaingotnochill** [comment]
@elmps2018 I think it's a pretty easy win issue. Can I work on this?

**Comment by swaingotnochill** [comment]
Here is the drive link containing the video:

https://drive.google.com/file/d/1G63lu6Dp3ZxtopzNVgLpqCiTS67ifIXY/view?usp=drivesdk

We can remove the background music if we don't want. If there are any changes you would like, we can do that too. Any feedbacks? @elmps2018

**Comment by elmps2018** [comment]
Thanks @swaingotnochill for working on this! This is off to a good start. Screen record is fine. Could you add a title for selecting a form since you do that first? To make clear which part is selecting a form, creating an instance, and editing an instance? Arrows/circles/highlighting and going a bit slower would also be helpful, but the right content is there! I wouldn't include the saving part in this since I think we'll have a separate video for that and it might be confusing.

**Comment by elmps2018** [comment]
Hi @swaingotnochill! This has the right content which is great, but it is a little too fast to follow! Could you slow it down and highlight/circle what you are selecting to help users follow along?

**Comment by khushishikhu** [comment]
@elmps2018 can I try to work on this issue? If no one is working on it

**Comment by elmps2018** [comment]
@swaingotnochill are you still working on this issue? @iamhks completed something similar in #241.

**Comment by swaingotnochill** [comment]
@elmps2018 Yes..will submit soon.

**Comment by iamhks** [comment]
@swaingotnochill if you have not yet started, we can use mine for this one and you can work on #241 because I got confused and made a video of this issue.

**Comment by swaingotnochill** [comment]
Anything goes fine..I made one earlier but it was too fast..Since, you made one, that's great..We will use yours. Thanks for working on this issue.

**Comment by iamhks** [comment]
Thanks @swaingotnochill.
@elmps2018 Please check if everything's okay or if any changes are to be made on the video.
Link: https://drive.google.com/file/d/1U6zQ_AnXTbmI6uV0DentrLv2ohiPuUMO/view?usp=drivesdk

**Comment by elmps2018** [comment]
@swaingotnochill and @iamhks thanks this looks great, will upload this to the YouTube channel shortly!
