### ISSUE TITLE
Video: Working with sub-forms and linked tables in ODK-X Survey

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#241]
Make a video showing how to add, edit, and delete sub-form/linked table instances for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by iamhks** [comment]
I would like to work on this!

**Comment by wbrunette** [comment]
@iamhks thanks for taking on this issue, I have assigned it to you.

**Comment by iamhks** [comment]
Hi @elmps2018 , sorry for the delay. Here's the video: https://drive.google.com/file/d/1U6zQ_AnXTbmI6uV0DentrLv2ohiPuUMO/view?usp=drivesdk

**Comment by elmps2018** [comment]
Hi @iamhks! Thanks for working on this! Sorry for any confusion, but this looks like adding, editing, and deleting an instance, rather than sub-forms and linked tables. More like issue #240 or #237. I am not sure if @swaingotnochill is still working on those, let me check.

**Comment by iamhks** [comment]
Hi @elmps2018 , since this issue is still pending, I thought I'll complete it. But I have a doubt, I was referring to https://docs.odk-x.org/survey-using/#opening-a-subform and it also showed creating a new instance. Could you point me to the doc/reference for sub-forms/linked tables in Survey?

**Comment by elmps2018** [comment]
Hi @iamhks! So the example shows creating a new instance **from inside a form**, which is a sub-form or linked table. You can demo this with the same household members example in the link. You would show entering the main (household) form, navigating/entering along to the members form, and then entering members data in the linked_table/sub-form, then saving that (ending back up in the household form), going back in and editing the data and saving again, and then deleting as well. For more info on tables see: https://docs.odk-x.org/xlsx-converter-using/?highlight=linked_table#linked-tables and the earlier link had the opening a subform.

**Comment by iamhks** [comment]
Thank you so much for the elaborate clear explanation @elmps2018 , I understood where I was making a mistake.
Here's the link to the video: https://drive.google.com/file/d/1VoolhhUZzxviy4dbvLFt41KcnCdSis_d/view?usp=sharing

**Comment by elmps2018** [comment]
Hi @iamhks! Thanks for working on this! This is the right content now! Could you just slow it down (may be able to do this with video editing software or just redo slower) so that folks can more easily follow along? Particularly for picking the household form, to highlight clearly and slowly which one you are picking, and then to give people a moment to read/see the screen before adding an instance to the subform or editing. Thanks!

**Comment by iamhks** [comment]
@elmps2018 Sure, here's the updated one: https://drive.google.com/file/d/1WPZhjyln05t--SsQ9cyEyoMXR81afg7G/view?usp=sharing
Feel free to point out if there's something I need to slow down even further.

**Comment by elmps2018** [comment]
@iamhks this is great thanks! Uploading to Youtube next.
