### ISSUE TITLE
Video: Introducing XLSXconverter

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#242]
Make a video introducing the XLSXconverter and its functionality (especially converting & preview in Chrome) for our Youtube Channel. 
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning). 

Context: ODK-X has started a [youtube channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ) to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by swaingotnochill** [comment]
Please assign this issue to me.

**Comment by wbrunette** [comment]
@swaingotnochill thanks for working on this issue, I have assigned it to you.

**Comment by aditisingh2412** [comment]
Hey! Can I work on this issue?

**Comment by linl33** [comment]
@swaingotnochill Can you give us an update on this issue? Let us know if you have any questions or would like to be unassigned.

**Comment by swaingotnochill** [comment]
@linl33 Yes..I am working on the other issues first, so @aditisingh2412 if you want feel free to work on this.

**Comment by wbrunette** [comment]
@aditisingh2412 are you still interested?

**Comment by aditisingh2412** [comment]
> @aditisingh2412 are you still interested?

Yes I'm interested.

**Comment by wbrunette** [comment]
@aditisingh2412 I have assigned the issue to you.

**Comment by aditisingh2412** [comment]
> @aditisingh2412 I have assigned the issue to you.

Could you please explain what I have to do in this issue? I have to make a video of what's present in this document: https://docs.odk-x.org/xlsx-converter-using/ right?

**Comment by elmps2018** [comment]
Hi @aditisingh2412! Thanks for working on this issue! So there is a LOT of written documentation on the xlsxconverter and making forms to convert. But what we wanted for this video is a bit more of an introduction to converting and preview in chrome. I think starting with the app designer on your computer, showing navigating to that path, and grunt to launch the preview, then walking through and explaining the different tabs in preview and demoing converting an excel would be the key goals. https://docs.odk-x.org/getting-started-2-architect/?highlight=chrome#setting-up-odk-x-application-designer has the initial launch and a screenshot in chrome, so replicating that and then walking around, especially the preview and converter tabs.

**Comment by aditisingh2412** [comment]
> Hi @aditisingh2412! Thanks for working on this issue! So there is a LOT of written documentation on the xlsxconverter and making forms to convert. But what we wanted for this video is a bit more of an introduction to converting and preview in chrome. I think starting with the app designer on your computer, showing navigating to that path, and grunt to launch the preview, then walking through and explaining the different tabs in preview and demoing converting an excel would be the key goals. https://docs.odk-x.org/getting-started-2-architect/?highlight=chrome#setting-up-odk-x-application-designer has the initial launch and a screenshot in chrome, so replicating that and then walking around, especially the preview and converter tabs.

Okay sure I'll do this :)

**Comment by EstherPhebe** [comment]
@elmps2018 Hi. If nobody is working on this, can I work on it?

**Comment by elmps2018** [comment]
@aditisingh2412 was assigned -- any updates? If I don't here back in a day or so I can assign to you @EstherPhebe

**Comment by aditisingh2412** [comment]
@elmps2018 you can assign this issue to @EstherPhebe

**Comment by elmps2018** [comment]
Thanks for the update @aditisingh2412! @EstherPhebe added you on!

**Comment by EstherPhebe** [comment]
Here is the link to the video

https://drive.google.com/file/d/1qiEmoM-6L6M4-lwCrvwMN5_EMPz63o4o/view?usp=drivesdk

**Comment by elmps2018** [comment]
@EstherPhebe thanks for working on this! Also great idea to advertise the channel at the start. One point to add in the description or as an intro slide might be that you need to set up various apps (chrome, nodejs, etc.). Alas can't just download the app designer and have grunt work. Maybe a separate video about setting up app designer first is needed? What do you think? Otherwise looked good in terms of key content to me! @wbrunette @linl33 (or Albert, whose github username I cannot recall...) any comments?

**Comment by linl33** [comment]
@elmps2018 Looks good to me as well.

@EstherPhebe FYI you can upload videos directly to GitHub now ([Link to announcement](https://github.blog/2021-05-13-video-uploads-available-github/))

**Comment by EstherPhebe** [comment]
> @EstherPhebe thanks for working on this! Also great idea to advertise the channel at the start. One point to add in the description or as an intro slide might be that you need to set up various apps (chrome, nodejs, etc.). Alas can't just download the app designer and have grunt work. Maybe a separate video about setting up app designer first is needed? What do you think? Otherwise looked good in terms of key content to me! @wbrunette @linl33 (or Albert, whose github username I cannot recall...) any comments?

@elmps2018 Thanks for the feedback. I'll make an application designer installation video, create an application designer playlist and put the video at the top, so its the first one in the queue. Does that work?

**Comment by EstherPhebe** [comment]
> @elmps2018 Looks good to me as well.
> 
> @EstherPhebe FYI you can upload videos directly to GitHub now ([Link to announcement](https://github.blog/2021-05-13-video-uploads-available-github/))

Thanks @linl33. I'll check that out

**Comment by elmps2018** [comment]
@EstherPhebe that sounds great! Good idea to use the playlists!
