### ISSUE TITLE
Add a button to Suitcase to refresh list of tables after logging in.

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#243]
If the server changes it's table manifest after you have passed the login/setup screen on suitcase it doesn't find new tables that have been created.

**Comment by Shubhamr837** [comment]
Hi @wbrunette can I work on this?

**Comment by wbrunette** [comment]
@Shubhamr837 I am going to assign you this issue but you also have 2 other issues that are not finished as well. I realize there are 2 issues that are waiting on review in addition to the 2 incomplete issues that are assigned to you. You will now have 3 incomplete which is more than our usual 2 max, but I also realized you just got the video today and the sync-client yesterday.

**Comment by Shubhamr837** [comment]
Thanks , I understand this . I will try to send PRs for the previous incomplete ones within 24 hours .
