### ISSUE TITLE
Update default server URL

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#244]
Update the default server URL in androidlibrary strings.xml from

```
<string name="default_sync_server_url">https://opendatakit-simpledemo.appspot.com</string>
<string name="default_legacy_server_url">https://opendatakit-2.appspot.com</string>

<string name="default_sync_server_url">https://tables-demo.odk-x.org</string>
<string name="default_legacy_server_url">https://tables-demo.odk-x.org</string>
```

Also change the translation strings.xml in spanish (es) so the url is consistent.

**Comment by VarunT11** [comment]
@wbrunette Can I work on this?

**Comment by pawanharariya** [comment]
@wbrunette Can I work on this?

**Comment by linl33** [comment]
@pawanharariya I've assigned this issue to you.
@VarunT11 Please complete your in-progress issues before taking on new issues.
