### ISSUE TITLE
Update table permalink URL in XLSX Converter Reference  

### ISSUE THREAD

**Issue by EstherPhebe** [opendatakit/tool-suite-X#246]
All the tables on the [XLSX Converter Reference](https://docs.odk-x.org/xlsx-converter-reference) page all have permalink URL's that have `#id--`. An example of this is https://docs.odk-x.org/xlsx-converter-reference/#id1 for the worksheet reference table. 

1. Update the permalink URL's for all the tables on the page to match table title. 

[https://docs.odk-x.org/xlsx-converter-reference/#id1](https://docs.odk-x.org/xlsx-converter-reference/#id1) will be updated to [https://docs.odk-x.org/xlsx-converter-reference/#worksheet-reference-table](https://docs.odk-x.org/xlsx-converter-reference/#worksheet-reference-table.).  
https://docs.odk-x.org/xlsx-converter-reference/#id2 will be updated to https://docs.odk-x.org/xlsx-converter-reference/#survey-worksheet-required-columns and so on. This update will be for all tables on the page.

**Comment by EstherPhebe** [comment]
**@opendatakit-bot claim**

**Comment by EstherPhebe** [comment]
@wbrunette @elmps2018 Please assign this to me.

**Comment by wbrunette** [comment]
@EstherPhebe I have assigned the issue to you.
