### ISSUE TITLE
How to upgrade/update versions

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#248]
We do not seem to have documented how to update versions of the software, e.g. from v2.1.6 to 2.1.7, see this forum post:
https://forum.odk-x.org/t/upgrading-from-v-2-1-6-to-2-1-7/1298/2

Documenting this process as a tip or section, possibly here: https://docs.odk-x.org/build-app/#updating-an-application to explain this process would be helpful.

**Comment by iamhks** [comment]
@elmps2018 Please assign this to me.

**Comment by elmps2018** [comment]
@iamhks assigned, thanks for working on this!
