### ISSUE TITLE
init-odkx-sync-endpoint.py should use a shallow checkout of Sync Endpoint

### ISSUE THREAD

**Issue by linl33** [opendatakit/tool-suite-X#249]
`init-odkx-sync-endpoint.py` does a full checkout of Sync Endpoint but only the most recent commit is needed. It should perform a shallow checkout instead to save time and bandwidth.

Such as this, https://github.com/linl33/sync-endpoint-containers/blob/b8125d9afc2e7af275fa3a6cd42874f4eb3dc6e8/Dockerfile#L6

**Comment by Shubhamr837** [comment]
Hi @linl33 can I work on this?

**Comment by linl33** [comment]
@Shubhamr837 I've assigned this to you.

**Comment by Shubhamr837** [comment]
Hi @linl33 can I have some more details about this?
The script builds docker image and deploys the stack.
Should we create a method so that it updates the sync-endpoint files by fetching the file modified by last commit?

**Comment by linl33** [comment]
There is a `git clone` in the script. The command performs a full checkout but a full checkout isn't necessary. Modifying that command would be sufficient.
