### ISSUE TITLE
Document the form order

### ISSUE THREAD

**Issue by khushishikhu** [opendatakit/tool-suite-X#250]
## Description
I was reading the documentation and came out with this issue that we don't have the documentation in 'Using ODK-X survey' about how we can order the instances list as we have for opening the form, saving the instances, deleting the instances, or editing the instances. This requires a subsection where we have to write about this feature. The thing which I want to add in the documentation is shown in the screenshot.
![image](https://user-images.githubusercontent.com/65439761/114411861-316f2a00-9bca-11eb-99bc-e9571a1c88ae.png)

**Comment by khushishikhu** [comment]
@elmps2018 @linl33  @wbrunette can you please look at this issue and check if it is correct or not.

**Comment by wbrunette** [comment]
@khushishikhu this orders the forms list, not the instance list (to clarify terminology). If you want to document it I don't see a problem, but I do not think it belongs in the general directions as it is more of advanced item, not a getting started item. @elmps2018 can provide the information about where best to put the documentation. Perhaps a new section for user adjustments.

**Comment by elmps2018** [comment]
@khushishikhu good suggestion! Not a getting started level issue, but the using survey has more details: https://docs.odk-x.org/survey-using/ it talks about instance order, for instance. So putting form order after opening a form could be a good spot here.

**Comment by khushishikhu** [comment]
@wbrunette @elmps2018 can you please assign me on this issue. Thank you for making it me more clear

**Comment by wbrunette** [comment]
@khushishikhu I have assigned the issue to you.
