### ISSUE TITLE
Android emulator links broken in docs

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#252]
There are a bunch of mentions, see pic, of the android emulator in docs but they give 404. Please fix! 
<img width="703" alt="Screen Shot 2021-04-13 at 1 03 11 PM" src="https://user-images.githubusercontent.com/35489974/114599589-e8b28200-9c58-11eb-80d2-90ae1ef9a3f6.png">

**Comment by chinenyeokafor** [comment]
@elmps2018 Please assign this to me.

**Comment by elmps2018** [comment]
@chinenyelilian assigned to you, thanks!
