### ISSUE TITLE
Video: Syncing with ODK-X services

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#253]
Make a video showing how to use ODK-X services to log in and sync data for our Youtube Channel. Can basically do a video demoing this process of logging and syncing with a demo server: https://docs.odk-x.org/survey-sample-app-install/
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning).

Context: ODK-X has started a youtube channel to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by elmps2018** [comment]
Make sure to go slow enough and use highlighting/cursor/something so viewers can tell what you are entering and clicking!

**Comment by chinenyeokafor** [comment]
@elmps2018 Can I work on this?

**Comment by elmps2018** [comment]
Hi @chinenyelilian! It looks like you are assigned to two open issues. We ask folks to make sure to finish off one of their issues before taking another to make sure issues are being actively worked on and that there are enough to go around! If this is still available when you finish one of the other issues let me know and I can assign you!

**Comment by chinenyeokafor** [comment]
@elmps2018 I have turned in one of my open issues (Awaiting response from @wbrunette). 

After it is approved, I will get back to this. Thank you

**Comment by ADISKING1** [comment]
Hey @elmps2018,
If this issue is still available, I would like to work on it.

**Comment by elmps2018** [comment]
Hi @chinenyelilian and @ADISKING1 since @chinenyelilian had turned in an issue and asked for this one first, I am assigning to @chinenyelilian

**Comment by chinenyeokafor** [comment]
Thank you @elmps2018 

This is the link to the video: https://drive.google.com/file/d/1lHoT5sP7MYMekS_ix58-204BetTm_2bt/view?usp=drivesdk
Kindly review and share feedback.

**Comment by elmps2018** [comment]
@chinenyelilian this looks good -- it has all the right content. One suggestion would be if there is anyway to speed up the video part where the syncing is going on (sorry, I don't know video editing, but if it's possible to have the syncing phase be at high speed so folks don't have to watch the sync for many minutes).

**Comment by chinenyeokafor** [comment]
@elmps2018 The video has been edited accordingly.

Please see the video: https://drive.google.com/file/d/1lMeHAmfA0imB_0al17hwlPOz80SYJKrm/view for your review.

**Comment by elmps2018** [comment]
@chinenyelilian this is great, just uploaded to the YouTube channel, thanks!
