### ISSUE TITLE
Video: Installing basic tools (English)

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#254]
Make a video showing how to install the basic tools on a tablet. Basically, video this: https://docs.odk-x.org/basics-install/
We have this in Spanish already as well so can do something very similar: https://youtu.be/jrGSySKK9p8
Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning).

Context: ODK-X has started a youtube channel to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by Leena1666** [comment]
Can you please assign this to me?

**Comment by elmps2018** [comment]
@Leena1666 just assigned you, thanks, let us know any questions or share your video when ready!

**Comment by Leena1666** [comment]
sure, Thanks

**Comment by Leena1666** [comment]
Here's my video, will be glad to get any feedback on what I can improve! https://drive.google.com/drive/folders/1M43qRk9Mm1ev7S_KOjT2QFctxkOF5rQ9?usp=sharing

**Comment by elmps2018** [comment]
@Leena1666 thanks for working on this, looks great and I will upload to our YouTube next!
