### ISSUE TITLE
Video: Different views in ODK-X Tables

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#255]
Make a video showing how to use the different views in ODK-X Tables for our Youtube Channel. Can basically do a video walking through the same content as this documentation: https://docs.odk-x.org/tables-using/ This one is particularly likely to benefit from text of what is going on (e.g. "Switching to list view")/audio narration (if with audio narration please check & fix the automatic captioning). Make sure to go slow enough for viewers to follow and highlight what is being selected on the tablet. 

Context: ODK-X has started a youtube channel to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by chinenyeokafor** [comment]
@elmps2018 Can I work on this?

**Comment by elmps2018** [comment]
@chinenyelilian assigned you!

**Comment by chinenyeokafor** [comment]
Thank you @elmps2018 

Please see video: https://drive.google.com/file/d/1lV9yJrJQOY7xbidHILNHjVvsN3Rd5Xwz/view?usp=drivesdk

Kindly review and share feedback.

**Comment by elmps2018** [comment]
@chinenyelilian this is great, thank you! Will upload to the YouTube channel next!
