### ISSUE TITLE
Selection of multiple table to download from cloud endpoint  

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#258]
Currently we  are only able to select only one table inside suitcase , To correct this issue  we can make a queue/list of  tables selected and then download them all together .
@wbrunette  @linl33

**Comment by sarahelshabrawy** [comment]
Can I work on it ?

**Comment by sanyud24** [comment]
hey , @sarahelshabrawy , I'm sorry I'm not the mentor , Mentors for outreachy are @wbrunette and @linl33  and caroline krafft ,  I opened up this issue for myself and wanted mentors consideration over
 it , you can look for this open issue https://github.com/odk-x/tool-suite-X/issues/207

**Comment by sarahelshabrawy** [comment]
@sanyud24  I'm sorry I didn't know that you wanted to work on it, so I was asking one of the mentors to assign it to me. Anyway, sorry for the misuderstanding, Good luck.

**Comment by sanyud24** [comment]
Ohnno! It's  alright✌,  thankyou for understanding,  best of luck to you too😊

**Comment by wbrunette** [comment]
@sanyud24 you are correct this is an issue. The reason we did put it in the issue queue yet is because if you read the project description you will see this is part of the suggested project. If accepted this should be part of the new user interface for suitcase.

**Comment by sanyud24** [comment]
Ohkay , sure ,should I close this issue then?
