### ISSUE TITLE
Video: Demo Longitudinal Clinic Study app

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#260]
Make a video demoing the [Longitudinal Clinic Study app](https://docs.odk-x.org/hope-study-intro/)! There is a good guided tour documented in these docs that you could work through on video. Do not need to show the install/code/underlying files but do show all the great features

Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning).

Context: ODK-X has started a youtube channel to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by sarahelshabrawy** [comment]
Would you please assign it to me.

**Comment by elmps2018** [comment]
Hi @sarahelshabrawy! I just assigned one of the other demos to you and it looks like you now have two open issues! We encourage folks to finish an issue rather than take on a third one so that the issues queue is up to date and there are enough easy/good first issues to go around!

**Comment by sanyud24** [comment]
may I work on this issue?

**Comment by wbrunette** [comment]
@sanyud24 I have assigned this issue to you.

**Comment by sanyud24** [comment]
Thankyou , for assigning @wbrunette , I'll be working over it

**Comment by sanyud24** [comment]
Hi  ,  let me know if I had to do some changes 
Here's the video link:

https://drive.google.com/file/d/1nb6TpRPeuKhmfQDKDYiUDMyEiN1hhkar/view?usp=sharing

**Comment by elmps2018** [comment]
Hi @sanyud24! Thanks for working on this! A few comments:
-Please go slower at key screens, for example, the first screen where you pick the form to start with, and use highlighting or somehow indicate which you are clicking. 
-Please try to demo all of the tablet based content in the demo. While you showed some bits of survey, one of the great things in the demo is about the existing client list and navigating to clients, for example: https://docs.odk-x.org/hope-study-tour-home-locator/
-I would recommend walking through what is already in the docs in the guided tour: https://docs.odk-x.org/hope-study-intro/

**Comment by sanyud24** [comment]
Ohkay , sure I'll do it again with more clarity.

**Comment by sanyud24** [comment]
Hi , I've covered all the three options from screening to sync data 
video link:
https://drive.google.com/file/d/1o8Wws1h96Nf1hXShI0kJkHf9MNun45Lz/view?usp=sharing

**Comment by elmps2018** [comment]
@sanyud24 thanks for the revised video! This is much clearer and walks through more features! My one suggestion is if you are able to speed up the syncing part (I think you can do this as a speed up in any video editing app) that would be helpful. Otherwise ready to post to youtube!

**Comment by sanyud24** [comment]
Yeah sure I'll do it ✌

**Comment by sanyud24** [comment]
Hi , I've done the changes , fast-forwarded syn part to 30 sec
https://drive.google.com/file/d/1os7pvp9inQEoU4ve1aTOOjvvYaA-F7dI/view?usp=sharing

**Comment by elmps2018** [comment]
@sanyud24 fabulous thanks so much! I'll upload to the Youtube channel next!

**Comment by sanyud24** [comment]
thankyou!! sure 👍
