### ISSUE TITLE
Video: Demo Inventory Management and Maintenance App

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#261]
Make a video demoing the [Inventory Management and Maintenance App](https://docs.odk-x.org/cold-chain-intro/)! There is a good guided tour documented in these docs that you could work through on video. Do not need to show the install/code/underlying files but do show all the great features

Can do without sound or with audio narration (if with audio narration please check & fix the automatic captioning).

Context: ODK-X has started a youtube channel to share videos of how to do key tasks in ODK-X. Although these tasks are often explained in the documentation, we frequently get requests for videos and some things are easier to learn watching a video than reading documentation. We are working on getting videos in English & Spanish but also welcome contributions in other languages!

**Comment by chinenyeokafor** [comment]
Please can I work on this??

**Comment by elmps2018** [comment]
@chinenyelilian thanks for helping with this documentation work! I have assigned to you! Let us know any questions.

**Comment by chinenyeokafor** [comment]
@elmps2018 Please is there an existing demo server URL and login details for the the cold chain application?

**Comment by elmps2018** [comment]
Hi @chinenyelilian great question! There is not a demo server but there is a demo app you can download and push to your tablet. Details: https://docs.odk-x.org/cold-chain-intro/#installing-cold-chain . This one does require setting up a demo server to test the group permissions and things, if you are able to do that.

**Comment by chinenyeokafor** [comment]
@elmps2018  Yes, I already have the app on my mobile device. I was setting up the sync endpoint and just wanted to clarify.

Thanks.

**Comment by chinenyeokafor** [comment]
I have set up Sync Endpoint on Azure cloud service and created 2 users A and B on phpLDAPadmin and granted all permissions to user A. I've set the admin password and allowed non-encrypted connections on my mobile device. With User A, I have reset the App Server and synchronized from the server. 
Everything looks fine but the Cold Chain Management app still displays "User is Not Authorized. Please Log In". I've synchronized as user A and B 

@elmps2018 @wbrunette Please guide me. 
I got the copy of the application from the app folder in the [cold-chain-demo branch of the App Designer repository](https://github.com/odk-x/app-designer/tree/cold-chain-demo). 

![image](https://user-images.githubusercontent.com/28391088/115943060-aa616200-a4a5-11eb-9097-62e2646c62bc.png)

_

**Comment by elmps2018** [comment]
@chinenyelilian awesome work getting this all set up so far! Were you able to set up the different groups as well? https://docs.odk-x.org/cold-chain-intro/#installing-cold-chain has a warning about the groups.

**Comment by chinenyelilian** [comment]
@elmps2018 I used the groups created when the LDAP server was brought up.

**Comment by elmps2018** [comment]
@chinenyelilian using the groups created when following the default setup instructions is likely causing the problem since there are specific regional groups built into the app that are needed to access the data.

**Comment by chinenyeokafor** [comment]
Okay, Thanks

**Comment by chinenyeokafor** [comment]
@elmps2018  Please see link to the demo video and kindly review.

https://drive.google.com/file/d/1onYMGg3Fi785jJOyGAPdR3aggrYorlnI/view?usp=drivesdk

**Comment by elmps2018** [comment]
@chinenyelilian this is great glad you got it working! The one thing I wanted to check before posting to Youtube was whether you had changed or wanted to edit out the password/address if it's a server you have, don't want anyone messing that up!

**Comment by chinenyeokafor** [comment]
@elmps2018, Please go ahead. I have changed the login parameters.

**Comment by elmps2018** [comment]
@chinenyelilian Great! Uploading next! Thanks for your help!
