### ISSUE TITLE
Error message while selecting "Empty" directory

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#262]
There can be an error dialog box while selecting a empty directory in odk-x-suitcase instead of letting suitcase select the empty directory. 

Steps to reproduce :
1. login into suitcase
2.  using the browse button select an empty directory

**Comment by sanyud24** [comment]
could this be a valid issue @wbrunette  @linl33

**Comment by wbrunette** [comment]
This is a valid issue, thank you for finding issues to work on! It's good to see initiative in improving ODK-X 🥇

**Comment by sanyud24** [comment]
Thankyou, I will be working over it then.

**Comment by wbrunette** [comment]
according to @Shubhamr837 this got fixed with the Suitcase UI revamp in suitcase
