### ISSUE TITLE
Consolidate sync-endpoint default user instructions

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#263]
Create a new documentation file to consolidate sync-endpoint user instructions into it's own section under sync-endpoint. The pages that information got consolidated from should be updated with prominent links to the user section.

https://docs.odk-x.org/sync-endpoint/#creating-groups
(leave configuration and startup but move creating users, creating groups, and assigning to groups to new section. The remaining information should be combined in LDAP should be combined with advanced sub-subsection) 
https://docs.odk-x.org/sync-endpoint-cloud-setup/#creating-a-sample-user
https://docs.odk-x.org/sync-endpoint-cloud-setup/#anonymous-access-for-odk-x-sync-endpoint-cloud
https://docs.odk-x.org/sync-endpoint-manual-setup/#anonymous-access-for-odk-x-sync-endpoint

**Comment by chinenyeokafor** [comment]
@wbrunette Please can I work on this?

**Comment by chinenyeokafor** [comment]
Thank you!
