### ISSUE TITLE
Add deprecation warning to Aggregate Extenstion directions

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#265]
At the top of the Aggregate extension page a large red message should inform users that Aggregate is deprecated and no longer supported.

https://docs.odk-x.org/aggregate-tables-extension/

**Comment by sarahelshabrawy** [comment]
Can I work on it ? I opened a pull request for one of my 2 issues, but it's still under review.

**Comment by wbrunette** [comment]
@sarahelshabrawy I will assign it to you because you may have missed @linl33 question. Your pull request review has stopped because we are waiting on the answer to: https://github.com/odk-x/tool-suite-X/issues/257#issuecomment-822213199

Therefore, the reviewers are waiting on you ... normally we only allow a third when you are waiting on the reviewers.

**Comment by sarahelshabrawy** [comment]
@wbrunette Thanks for letting me know, I really missed it and was waiting for the review, sorry.
