### ISSUE TITLE
ODK-X docks/ Sync-Endpoint Documentation : Port number

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#266]
From what I've surveyed in setting up sync-enpoint and running the server , people are making common mistakes of not shutting down application running over port:80 like Apache2, which runs on port80 , I came across with this  problem too , had to search a lot for this , This issue can be added below the Note here

![port](https://user-images.githubusercontent.com/57134307/115507259-85000880-a299-11eb-935e-4a420efe5be9.jpg)

-  It can be written as to remind people to find app using same port  by passing this command "netstat -ano | findStr "8080""  and close it first.  or just reminding them .
- Mostly Apache2 uses this port ,"it can be written as for ex - Apache2"
-  It'll be helpful for beginners .

**Comment by sanyud24** [comment]
Can I do this modification mentors ?

**Comment by wbrunette** [comment]
@sanyud24 I am not sure I get exactly what you are proposing, yes you cannot have conflicting ports. Running on port 80 is a protected port so it's a advisable to run it on another port when developing. Go ahead an make a proposed change in a pull request and we can review the details of what you are suggesting.
