### ISSUE TITLE
Document how to use the QR scanner in ODX-X services to log in

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#267]
Add documentation about configuring/logging in to the server using a QR code as alternative to typing the server URL, user name password.

Possible areas to add the QR code login methods are:
https://docs.odk-x.org/services-using/#initial-server-configuration
https://docs.odk-x.org/services-using/#authenticating-users

A QR code can be generated using app-designer.

**Comment by sanyud24** [comment]
Hi, Although I have  open issues  , one of them is a long one and taking time ( https://github.com/odk-x/tool-suite-X/issues/264) , so may I work on this , this is a small issue , I'll do it asap?

**Comment by wbrunette** [comment]
@sanyud24 I am going to assign the issue to you, but this is a one time exception.

**Comment by sanyud24** [comment]
Thanks a lot!!
