### ISSUE TITLE
Add documentation about the QR code generator in app-designer

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#268]
The application designer has the ability to generate a QR code that services can use to automatically populate the server URL, username and password in ODK-X Services. A description of this available functionality should be added to the documentation of Application Designer.

**Comment by EstherPhebe** [comment]
@wbrunette I'd like to work on this.

**Comment by wbrunette** [comment]
@EstherPhebe I have assigned the issue to you
