### ISSUE TITLE
 ODK-X REST Protocol links broken in docs

### ISSUE THREAD

**Issue by chinenyeokafor** [opendatakit/tool-suite-X#269]
There are mentions of rest protocol, that when clicked returns dead-end 404 errors.
![image](https://user-images.githubusercontent.com/28391088/116197262-70ee5800-a72c-11eb-887f-6ec589610b33.png)

**Comment by iamhks** [comment]
Hi @chinenyelilian I think there's already a related issue to fix broken links and typo here: https://github.com/odk-x/tool-suite-X/issues/207

**Comment by chinenyeokafor** [comment]
Thanks for pointing this out  @iamhks 
I guess odk-x/docs/pull/109 closes this.
