### ISSUE TITLE
Sync-endpoint sign in page UX improvement

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#270]
The Sync Endpoint sign in page has an outdated title. 

Add a header and include the ODK-X logo
Update the page title to: Sign in to Sync Endpoint
Reduce the width of the content container to 440px

![Sign in page](https://user-images.githubusercontent.com/1215441/116258579-47badf80-a79f-11eb-9c68-1e84d6825430.png)

**Comment by chinenyeokafor** [comment]
@maprehensive I'd like to work on this.

**Comment by wbrunette** [comment]
@chinenyelilian I have assigned the issue to you.

**Comment by wbrunette** [comment]
@chinenyelilian are you still working on this issue? It is fine if you are no longer working on it, as we would like to unassign the issue to let others know they can work on it. If you are still working on the issue great. Please let us know.
