### ISSUE TITLE
Sync-endpoint navigation UX improvement

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#271]
The Sync-endpoint header and navigation has an out of date logo and can be simplified. 

Change the logo to use the ODK-X logo
Remove the My Account pick list in the navigation
Update the hyperlink on the logo to link to the Sync-endpoint landing page (Who Am I?)

Remove prefacing text "Logged in as" from the username 
Remove the hyperlink applied to the username - doesn't link to anything
Change the Sign Out button to a text link that reads: Sign out
Add a solidus between the username and Sign out

![Header navigation](https://user-images.githubusercontent.com/1215441/116261312-b4cf7480-a7a1-11eb-8eb1-f60d472956c1.png)

**Comment by sanyud24** [comment]
May I work on this ?

**Comment by wbrunette** [comment]
@sanyud24 I have assigned the issue to you.

**Comment by sanyud24** [comment]
Hi , I'm sorry but I'm just not able to find the html or xml file that contains this page , Can I get this issue unassigned as I've not applied to Sync-Endpoint , I would like to spend some of the remaining days working on projects I applied for .

**Comment by maprehensive** [comment]
@sanyud24 No problem, I've unassigned you.
