### ISSUE TITLE
Update ODK-X Scan with warning/request for maintainer

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#272]
The ODK-X Scan tools have not been updated in a couple of years and are in need of a maintainer! 
This issue is to add an announcement to the ODK-X scan read me - on github - and the docs 
https://docs.odk-x.org/scan-intro/
to a) warn users that the tools have not been recently updated and b) encourage someone to become a maintainer of the tools.

**Comment by EstherPhebe** [comment]
Hi @elmps2018 Can I work on this, I'm done with my second open issue and I'd send in the details for my second one very soon.
