### ISSUE TITLE
Survey Listview UI Update 

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#273]
Hi everyone , its almost been a week since I started working on Survey app for the issue https://github.com/odk-x/tool-suite-X/issues/154  and I'm enjoying working on it , It's just my proposal idea about the listview that contains forms :
1. It can be modified a bit by adding padding and backgrounds , this is just something I just worked upon , its totally my own interest.
2. The textsize of  textview containing the "last update date and time" can be made little smaller as compared to others as its less important than Title and TableID
![Screenshot_20210428-133524_ODK-X Survey](https://user-images.githubusercontent.com/57134307/116372991-906baa80-a82a-11eb-9cdb-8c1ffc981092.jpg)

3. The TextView containing "Select the form to open" can be removed and in place of that Arrows indicating "open forms" can be placed 
![Untitled123_20210428134515](https://user-images.githubusercontent.com/57134307/116373372-e3456200-a82a-11eb-9fb8-e771df0083fd.png)
   
# Arrow  will also prevent mistakes likes : accidental opening of form, So Instead of opening from by clicking on it , It can be opened by an "Arrow" . 

Please let me know if any of these changes can be made .

**Comment by wbrunette** [comment]
The PMC/TSC would need to discuss at our next meeting. We met before you submitted this issue (April 27(. The next meeting is May 11.

**Comment by sanyud24** [comment]
Yeah , Sure , Thankyou for the review.

**Comment by wbrunette** [comment]
After PMC/TSC meeting we decided that we did not want the arrow as the only click option. Clicking on the words is a common use case.
