### ISSUE TITLE
Suitcase: Add serialVersionUID to serializable classes

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#274]
Add serialVerison ID to serializable classes like PushPanel , PullPanel , LoginPanel , IOPanel etc . to remove the warning  .

As it is strongly recommended that all serializable classes explicitly declare serialVersionUID value, since its computation is highly sensitive to class details that may vary depending on compiler implementations, any change in class or using different id may affect the serialized data.
-gfg

**Comment by sanyud24** [comment]
May I work on this issue if it seems a valid issue to you   . @wbrunette .

**Comment by linl33** [comment]
We don't use Java Serialization. Thanks for pointing this out though.
