### ISSUE TITLE
Sync-endpoint landing page layout improvements

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#275]
This issue to improve the presentation of the information presented on the Sync-endpoint landing page (currently called Who Am I?).

Change the page title from "Who am I?" to "Sync Endpoint"

Create a two-column layout to show the current page contents. 
Heading is "Account details" 
For the current content under Who am I?, show Username, Full name and Default group in the left column
For the current content under Groups & Roles, add either "Group:" or "Role:" to the left hand column

To make it easier for users to quickly select the Form table they want to navigate to,
Add a single column layout to show the users list of Form tables on the page body
Heading is "Form tables"
Each row contains the name of a form table, linked to that form table

Content sections are 400px wide in desktop layout
Rows are 50 px high

![Landing page](https://user-images.githubusercontent.com/1215441/116895051-f9a15280-ac5c-11eb-8081-809a44aaaed9.png)

**Comment by Wishy-S** [comment]
@maprehensive can i work on this issue please?

**Comment by wbrunette** [comment]
@Wishy-S I have assigned the issue to you. Thank you for taking it on :)

**Comment by Wishy-S** [comment]
@wbrunette As i m new to the community so getting a few problems while logging into server.
 I m trying signing in into the "ODK server 2.0" using default username : **admin** and password : **aggregate**
But it says **Incorrect username or password** . 
I have done my set up exactly described in  _**https://github.com/odk-x/sync-endpoint-web-ui/blob/master/RUN.md**_ .
Can you please show me the path to get through this?
Here is the screenshots of the error.

1. ![Screenshot from 2021-05-18 19-48-34](https://user-images.githubusercontent.com/54708414/118667948-0c498900-b812-11eb-9951-6e75f056b246.png)


2. ![Screenshot from 2021-05-18 19-42-28](https://user-images.githubusercontent.com/54708414/118667233-744b9f80-b811-11eb-9779-f8ba3ac6484d.png)


In screenshot 1 Below the **error report** is printed.

**Comment by wbrunette** [comment]
@Wishy-S the instructions are in the process of being updated. Check out the pull request with some of the changes:
https://github.com/odk-x/sync-endpoint-web-ui/pull/14

**Comment by wbrunette** [comment]
@Wishy-S are you still working on this issue? It is fine if you are no longer working on it, as we would like to unassign the issue to let others know they can work on it. If you are still working on the issue great. Please let us know.

**Comment by Wishy-S** [comment]
Apologies ,For now I'm not able to complete the task so , you can assign it
to someone else.

**Comment by toadmengo** [comment]
I'd like to work on this issue
