### ISSUE TITLE
PowerShell command for activating odkxenv

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#276]
The command here should be  " .\odkxenv\Scripts\activate "

![wrongcode](https://user-images.githubusercontent.com/57134307/116896841-3d428f00-ac52-11eb-9ae7-5af59a161ce1.jpg)

**Comment by sanyud24** [comment]
Hi , May  I work on this @wbrunette

**Comment by wbrunette** [comment]
@sanyud24 I assigned the issue to you
