### ISSUE TITLE
Sync-endpoint form table page navigation UX improvement

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#277]
The form table page currently has the page navigation links in a collapsible left hand column. The form table name / page title is also contained in that column. 

To maximize available screen width for the form table contents, and to make the page title and links always visible, 
Move the page title to the top of the page, below the main navigation
Move the navigation links to the top of the page, to the right of the page title

As "Rows" is the most commonly selected form table view, make Rows the default view instead of Manifest 
Also, change the order of the navigation links to: Rows, Manifest, Attachments, Export data

When viewing a page, the corresponding page navigation link should be grey, not blue, and the link should be removed

![Form tables page](https://user-images.githubusercontent.com/1215441/116898244-56ead300-ac60-11eb-8398-3412b8fdf302.png)

**Comment by toadmengo** [comment]
I'll try to work on this.

**Comment by wbrunette** [comment]
@toadmengo if you have questions feel free to ask by commenting on this issue.

**Comment by wbrunette** [comment]
https://github.com/odk-x/sync-endpoint-web-ui/pull/20
