### ISSUE TITLE
Sync-endpoint allow bulk delete on form table 

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#278]
## Overview

The ability to bulk-delete rows from sync-endpoint can save users significant time when managing data. Current functionality allows for a single row to be deleted. This issue is for the creation of bulk-delete functionality. 

### Separate View and Delete actions

As "View" row details is a single-row action, this button is separated into it's own column with title "Details". The View button is the same as current. 

Instead of a delete button per row, the left-most column contains a check-box per row. The header row also contains a check-box, which will select all the rows when checked. Selecting a check-box will enable the user to perform an action on that row. 

### Add actions row to top of table

Add a new to the top of the table to contain actions selector and item count.

When a user has selected one or more rows via the check-box, 
Then the user can select the "Delete rows" option from the dropdown button in the actions rows and click Go to delete the rows 
And the user should see a confirmation dialogue:
- for single row deletes keep the confirmation dialogue as is
- for bulk-delete change the wording in the body of the confirmation dialogue to read:

> Really delete these rows?
> There are X rows selected to be deleted. 

Where X is the number of rows selected. 

Use the Bootstrap small single button dropdown for the actions dropdown: https://getbootstrap.com/docs/4.0/components/dropdowns/

### Feedback for actions when no rows selected

When a user has not selected any rows
And selects the "Delete rows" option from the dropdown button in the actions rows and click Go to delete the rows 
Return a warning to inform the user that no action has been taken:

> No rows were selected, so no rows were deleted. 

Use the Warning alert from Bootstrap: https://getbootstrap.com/docs/4.0/components/alerts/

![Form tables page](https://user-images.githubusercontent.com/1215441/116898798-058f1380-ac61-11eb-8a3a-6aa8d5efa4dd.png)

![Form tables confirm delete](https://user-images.githubusercontent.com/1215441/116903386-8c92ba80-ac66-11eb-88f8-f30db8ba4c0f.png)

**Comment by sheykerkup** [comment]
@EstherPhebe  @wbrunette  can I work on this? If i understand well this work is to be done in ODK-X tables right?

**Comment by wbrunette** [comment]
@sheykerkup ... oops., this issue should be marked as ready for release. A recent PR included these changes https://github.com/odk-x/sync-endpoint-web-ui/pull/20

Sorry about the confusion.

**Comment by wbrunette** [comment]
@sheykerkup the changes are in the development branch waiting for the 2.1.9 release before moving to the master branch

**Comment by sheykerkup** [comment]
> @sheykerkup the changes are in the development branch waiting for the 2.1.9 release before moving to the master branch

Ok thanks.
