### ISSUE TITLE
Note 4GB+ recommended for server (Droplet)

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#290]
Apps need at least 2GB so recommend 4GB+ for server (Droplet on Digital Ocean,  for example)

**Comment by ShristiJain** [comment]
Hi @elmps2018 I would like to work on this issue. Can you please guide me on how to get started with this issue and what changes are required to be done.

**Comment by wbrunette** [comment]
@ShristiJain I have assigned the issue to you. Here are some instructions on contributing to our documentation: https://docs.odk-x.org/contributing/

There is also documentation in README file of the GitHub repo: https://github.com/odk-x/docs

**Comment by ShristiJain** [comment]
Thank you @wbrunette . I will start working on it right away.

**Comment by ShristiJain** [comment]
Hi, 
Should I add this recommendation to the "sync-endpoint-cloud-setup.rst" file ?

**Comment by wbrunette** [comment]
@ShristiJain that sounds like a good place. When you submit a pull request it will be reviewed and if changes are desired he reviewer will mention anything you need to fix before it's accepted.

**Comment by ShristiJain** [comment]
Okay sure. Thanks

**Comment by ShristiJain** [comment]
Dear mentors @elmps2018 , @EstherPhebe , @jbeorse and @wbrunette ,
I have made a PR to solve this issue. Kindly review it and let me know if there are any changes.
