### ISSUE TITLE
Suitcase shows done (Success message ) after deleteing a table using Anonymous Login. ( For Gsoc Branch ) 

### ISSUE THREAD

**Issue by Shubhamr837** [opendatakit/tool-suite-X#293]
Steps to reproduce :
1 ) Login using Anonymous login in suitcase.
2 ) Go to clear tab.
3 ) Delete a Table from the list.
Even after 401 response suitcase shows "Done" in the progress bar.

**Comment by adi9835** [comment]
Hi can work on this? @Shubhamr837

**Comment by adi9835** [comment]
Can you help me get started I have successfully compiled the project in Intellij but I don't know where should I look.

**Comment by Shubhamr837** [comment]
Hi @adi9835 you can check the this file in my fork. https://github.com/Shubhamr837/suitcase/blob/tableIdDropDown/src/main/java/org/opendatakit/suitcase/net/DeleteTask.java
The do in background method should throw an exception if response status code is not 200.

**Comment by adi9835** [comment]
Hi I have Just pushed my changes, please have a look.

**Comment by Shubhamr837** [comment]
Yes merged in my branch.
