### ISSUE TITLE
Update permalink URL to match the table title

### ISSUE THREAD

**Issue by EstherPhebe** [opendatakit/tool-suite-X#295]
The permalink URL for the tables on the [Using ODK-X XLSX Converter](https://docs.odk-x.org/xlsx-converter-using/#) page could be improved with a more descriptive URL..

https://docs.odk-x.org/xlsx-converter-using/#id3 could be improved to https://docs.odk-x.org/xlsx-converter-using/#simple-survey-example 
https://docs.odk-x.org/xlsx-converter-using/#id4 could be improved to https://docs.odk-x.org/xlsx-converter-using/#multiple-choice-example,
and so on, for all tables on the page.

**Comment by ShristiJain** [comment]
Hi @EstherPhebe , I am Shristi Jain. I would like to work on this issue. I would be grateful if you could help me on how to get started on this.

**Comment by EstherPhebe** [comment]
@ShristiJain I have assigned it to you.

**Comment by ShristiJain** [comment]
Hey @EstherPhebe I have made a pull request to fix this issue. Kindly review it.

**Comment by Kulex001** [comment]
@EstherPhebe since there is no much easy win or good first issue related to my topic, can i also contribute to this issue please?

**Comment by EstherPhebe** [comment]
> Hey @EstherPhebe I have made a pull request to fix this issue. Kindly review it.

Hi @ShristiJain, The goal is that https://docs.odk-x.org/xlsx-converter-using/#id3 permalink which is what is currently on the page should change to a more descriptive permalink, like this https://docs.odk-x.org/xlsx-converter-using/#simple-survey-example

The tables on the [XLSX Converter Reference page](https://docs.odk-x.org/xlsx-converter-reference/#) all have updated permalink tables, see https://docs.odk-x.org/xlsx-converter-reference/#worksheet-reference-table. You can look through the xlsx-converter-reference.rst file.

Some information here: https://docutils.sourceforge.io/docs/ref/rst/directives.html#:~:text=nametext,as%20reference%20name.

If you have any more questions let me know.

**Comment by ShristiJain** [comment]
Hey @EstherPhebe , I will look into the xlsx-converter-reference.rst file, as mentioned by you, to understand this better and then get back to you. Thank you for your help.

**Comment by ShristiJain** [comment]
Hey @EstherPhebe , I have made a PR to fix this issue. Kindly check.
