### ISSUE TITLE
Remove OI File Manager requirement from documentation

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#297]
ODK-X had a dependency on using OI File Manager versions 2.1.8 and lower. However, with the upcoming version 2.1.9 drops the requirement to use OI File Manager. The documentation should be updated to reflect this change.

**Comment by CtripleU** [comment]
Hello, @wbrunnette! 
I'd like to work on this. Could you please assign this to me? Thank you

**Comment by Ksenia2102** [comment]
@wbrunette
I would like to on this too.

**Comment by wbrunette** [comment]
@CtripleU I have assigned the issue to you since you were first. Please make sure to search the documentation so that you find all references to OI File Manager.

**Comment by CtripleU** [comment]
Thank you, @wbrunette. 
I have submitted a PR for this issue. Kindly review.

**Comment by elmps2018** [comment]
@wbrunette potential follow-up issue(s): identifying and re-doing any videos that show OI file manager.
