### ISSUE TITLE
Update minimium Android version in the documentation

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#298]
In version 2.1.9, ODK-X will drop support for Android 4.4.4. The new minimum Android version is 5.0. The documentation should be updated to reflect this change.

**Comment by Lamouresparus** [comment]
Hello @wbrunette I would like to work on this. Thanks

**Comment by Ksenia2102** [comment]
@wbrunette I ready to work on this

**Comment by wbrunette** [comment]
@Lamouresparus I have assigned the issue to you since you were first.

**Comment by Lamouresparus** [comment]
Thank you @wbrunette
