### ISSUE TITLE
Bug in Authentication Error dialog box

### ISSUE THREAD

**Issue by chitranshix** [opendatakit/tool-suite-X#300]
**Current Scenario**
On the "Change User/Logout" screen, if a user selects the "Authenticate New User" button with empty fields for username 
& password & then clicks on the "OK" button in the Authentication Error dialog box, the user is redirected to the main screen.
![IMG_20211021_143658 (2)](https://user-images.githubusercontent.com/43718257/138264849-8406f483-2941-4437-a1da-d97f218fb2b7.jpg)

**Problem description**
For empty username & password text fields, the Authentication Error dialog box points out that a username & password are not configured. It also prompts the user to update their settings. The user might decide to do 3 things after seeing this dialog box. They may either want to cancel changing the user, or they may use a different username & password or they may update their settings.

All 3 of these steps could be taken from the current screen itself. The user can cancel/log out by clicking the respective buttons. They can type in a new username & password in the empty fields. They can also select the setting menu from the title bar.

But clicking on the "OK" button in the dialog box navigates the user away from the current screen to the main screen. This isn't needed. It also gives rise to 1 additional step if the user wants to type in a new username & password.

**Proposed Solution**
Change the navigation from the main screen to the current screen in the Authentication Error's OK button's click handler.

**Comment by Lamouresparus** [comment]
@wbrunette can I pick up this task please?

**Comment by wbrunette** [comment]
@apigeoneer go ahead and put in a PR to fix the issue. One thing to check is if the code is being reused somewhere else as maybe the behavior is correct for the same dialog. (It may be only used on this screen something to investigate)

**Comment by chitranshix** [comment]
Hi! I have created a PR. Please have a look.
