### ISSUE TITLE
location to create framework.xlsx file not clear in documentation.

### ISSUE THREAD

**Issue by sheykerkup** [opendatakit/tool-suite-X#301]
***Docs Workflow***: Building an Application -> ODK-X Survey: Designing a Form

***Steps to Reproduce the Issue:***
1) Visit the documentation site (https://docs.odk-x.org/)
2) Select ‘Build an Application’ in the sidebar (https://docs.odk-x.org/build-app/#).
3) Go to ‘Creating framework.xlsx’ section of the content (https://docs.odk-x.org/build-app/#creating-framework-xlsx) and notice the first step.

4) Now, go to the ‘Generating formdef.json’ section (https://docs.odk-x.org/build-app/#generating-formdef-json) and notice the directory in which we are to find the framework.xlsx file which was created in step 3 above.

***Expected Workflow:*** I expected the flow to be asking us to convert the framework.xlsx file `config/assets/framework/forms/framework.xlsx` since that is the folder in which it was created before. 

***What actually happened:*** It said to convert the framework.xlsx file `app/config/assets/framework.xlsx`

***Proposed Solution:*** Update documentation to describe the correct path to upload framework.xlsx for conversion.

**Comment by sheykerkup** [comment]
@EstherPhebe  @wbrunette  is this valid?

**Comment by wbrunette** [comment]
It should refer to config/assets/framework/forms/framework/framework.xlsx. Assigning the issue to you.

**Comment by sheykerkup** [comment]
@wbrunette  I have sent a PR for this issue.
