### ISSUE TITLE
Fix tests in AndroidLibrary PR#214 and resubmit PR

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#302]
I accidentally merged https://github.com/odk-x/androidlibrary/pull/214 and had to revert the merge with the following commit (https://github.com/odk-x/androidlibrary/commit/2eb7074e0d415cda97f09cff0b9a3ed071f12d2c) because PR#214 caused the unit tests to break. 

We will need the code that was in PR#214 but we need the Android unit tests to pass.

To fix this issue create a new Pull Request(PR) with both 1) the code changes in PR#214 and 2) the necessary changes to that the unit tests no longer fail.

**Comment by Kulex001** [comment]
@wbrunette can i take this?

**Comment by wbrunette** [comment]
@Asukwo-comfort I have assigned the issue to you

**Comment by wbrunette** [comment]
@Asukwo-comfort I just saw the request to put back the video issue assignment to you. We generally only allow 2 issues at a time. Which two issues do you want to have assigned so that we can open one up to someone else?

**Comment by Kulex001** [comment]
Okay, i should be unassigned from this "Re: [odk-x/tool-suite-X] Video:
Demo Geographic Health Survey app (#259)"
Thank you

**Comment by puranjayK** [comment]
Hi @wbrunette, is the issue still open. I would like to work on it

**Comment by wbrunette** [comment]
yes, it's available puranjayK. I have assigned it to you.

**Comment by WaltonG** [comment]
Hi @wbrunette. Am ready to work on this issue. My understanding is that the codebase to work on is from pull request PR #214 and PR #302 should fix the failing tests in PR #214.

**Comment by wbrunette** [comment]
@WaltonG thank you for asking clarifying questions. You are currently linking to Issue 214 not the PR 214 in the Android library repository. See the PR https://github.com/odk-x/androidlibrary/pull/214

You need to fix the PR so it passes the tests and can be merged.

The title ended up looking weird as the number of this issue is #302 and does not refer to a PR (NOTE: the difference between black and grey text). I realize it is confusing and in the future, and in the future I am going to try to avoid ending the title of a Issue with the word PR.

Let me know if you want me to assign you the issue.

**Comment by WaltonG** [comment]
@wbrunette thank you for clarification. Yes assign me the issue

**Comment by wbrunette** [comment]
@WaltonG I have assigned the issue to you

**Comment by WaltonG** [comment]
Working on it

**Comment by WaltonG** [comment]
@wbrunette I have pushed the commited the changes. All 41 tests have passed

**Comment by wbrunette** [comment]
@WaltonG it's good to link the PR you want reviewed to this Issue. NOTE: you need to create a Pull Request for your changes to be reviewed and merge. Check out the Outreachy channel for more information about Pull Requests as I linked instructions and others linked tutorials.

**Comment by WaltonG** [comment]
@wbrunette I have linked the PR

**Comment by wbrunette** [comment]
Closed by https://github.com/odk-x/androidlibrary/pull/229
