### ISSUE TITLE
Add To Tables Documentation how to Debug a Android Webview 

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#303]
Debugging errors in customized html and JavaScript files can be challenging when customizing Tables applications. A section should be added to the documentation on how to connect your Chrome browser to an Android Webview to get debugging information.

Possible Resources to Link:
https://developer.chrome.com/docs/devtools/remote-debugging/webviews/
https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by sheykerkup** [comment]
Hi, @wbrunette  I recently went through this and had some challenges which I succeeded to resolve. If you do not mind I will like to document them including the steps I took to resolve debugging tables showing spreadsheet as default view.

**Comment by kenejane** [comment]
Hi @wbrunette , do I assume this issue has been assigned?, If yes please point me to another good first issue i can begin with. Thank you

**Comment by wbrunette** [comment]
@sheykerkup I have assigned the issue to you.

**Comment by sheykerkup** [comment]
@wbrunette  @clarlars  I have linked a PR for this. I am not sure why I can not tag you in that repository.
