### ISSUE TITLE
FOR OUTREACHY LEAFLET PROJECT - Create an Android Application with a WebView that has a custom webpage.

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#304]
This issue is an introductory task that helps demonstrate someone's preparedness to accomplish the Outreachy Fall 2021 Leaflet Project.  To complete this introductory task post a comment that contains a link of your repository and branch on GitHub that contains a functioning Android Application that uses the Android WebView to create a simple custom webpage.  The webpage needs only to display custom text like "Hello World!".

No need to try to setup Leaflet yet, as that will be the first step in your project if your project is accepted.

Please request to be assigned to the issue so we can track the number of peopling doing this exercise. Multiple people can work on this issue simultaneously (10 will be the limit).

**Comment by kenejane** [comment]
I will love to work on this project.

**Comment by permission-error1** [comment]
Hi @wbrunette I would like to participate in this

**Comment by sheykerkup** [comment]
@wbrunette. I would love to work on this issue.  I started playing around with android webview, leaflet and openStreetMap last week and created a demo project for it already on github, though it is not perfect for now. My project might have already gotten more advanced since I had set up leaflet. Do I need to create another project or swap the map page with another to display the custom "Hello World!"?

Here is the custom Android WebView application demo I have been working on in my spare time [https://github.com/sheykerkup/ODK-X-Leaflet.js-Demo](https://github.com/sheykerkup/ODK-X-Leaflet.js-Demo) branch `main`

**Comment by permission-error1** [comment]
> This issue is an introductory task that helps demonstrate someone's preparedness to accomplish the Outreachy Fall 2021 Leaflet Project. To complete this introductory task post a comment that contains a link of your repository and branch on GitHub that contains a functioning Android Application that uses the Android WebView to create a simple custom webpage. The webpage needs only to display custom text like "Hello World!".
> 
> No need to try to setup Leaflet yet, as that will be the first step in your project if your project is accepted.
> 
> Please request to be assigned to the issue so we can track the number of peopling doing this exercise. Multiple people can work on this issue simultaneously (10 will be the limit).

Hi @wbrunette! are we supposed to include this functionality in a forked repo of https://github.com/odk-x/androidlibrary or it should be an independent repo of our own?

**Comment by chitranshix** [comment]
Here are the repos I created displaying custom text using Android WebView in 2 separate Android apps -
[JAVA Android WebView demo](https://github.com/apigeoneer/android_webview_demo_java/tree/master), [Kotlin Android WebView demo](https://github.com/apigeoneer/android_webview_demo_kotlin).

**Comment by kenejane** [comment]
@wbrunette Here is a link to the repository I created. https://github.com/kenejane/Android-webview

**Comment by sheykerkup** [comment]
> @wbrunette. I would love to work on this issue. I started playing around with android webview, leaflet and openStreetMap last week and created a demo project for it already on github, though it is not perfect for now. My project might have already gotten more advanced since I had set up leaflet. Do I need to create another project or swap the map page with another to display the custom "Hello World!"?
> 
> Here is the custom Android WebView application demo I have been working on in my spare time https://github.com/sheykerkup/ODK-X-Leaflet.js-Demo

I have updated the application to load and display custom hello world page first instead of map. 
Here is the link [https://github.com/sheykerkup/ODK-X-Leaflet.js-Demo](https://github.com/sheykerkup/ODK-X-Leaflet.js-Demo) branch `main`

**Comment by permission-error1** [comment]
> This issue is an introductory task that helps demonstrate someone's preparedness to accomplish the Outreachy Fall 2021 Leaflet Project. To complete this introductory task post a comment that contains a link of your repository and branch on GitHub that contains a functioning Android Application that uses the Android WebView to create a simple custom webpage. The webpage needs only to display custom text like "Hello World!".
> 
> No need to try to setup Leaflet yet, as that will be the first step in your project if your project is accepted.
> 
> Please request to be assigned to the issue so we can track the number of peopling doing this exercise. Multiple people can work on this issue simultaneously (10 will be the limit).

Hi @wbrunette here is the Android App I created that has a webpage that displays "Hello World!" https://github.com/julian55455/android-webview

**Comment by Lamouresparus** [comment]
Hello @wbrunette  I would like to work on this

**Comment by Lamouresparus** [comment]
Hi @wbrunette here is the link to the [repository](https://github.com/Lamouresparus/Outreachy_Odk-x_Leaflet_Project) for the Android Web View Demo. It is on the master branch.
Thank you😊
