### ISSUE TITLE
Add user group instructions for Web UI Login in the Sync-Endpoint documentation

### ISSUE THREAD

**Issue by CtripleU** [opendatakit/tool-suite-X#308]
Although there are instructions for adding new users and groups [here](https://docs.odk-x.org/sync-endpoint-user-instructions/?highlight=ldap%20user#assigning-users-to-groups), the admin group to which a user should be added to be able to log in to the Web UI isn't stated. This causes end-users to frequently encounter the `incorrect username or password`  issue when trying to log in with the users they create. I also encountered this issue when setting up the Sync-Endpoint on my computer.

**Comment by CtripleU** [comment]
Hello, @elmps2018 and @wbrunette.
Could you please review this issue and inform me if it is valid? Thank you!

**Comment by wbrunette** [comment]
It is not true that they have to be ad admin, as you can login to the Sync Web UI with any user. However, the user does need to have one of the Tables roles assigned https://docs.odk-x.org/data-permission-filters/
These "roles" are available as Groups 500, 501, 502 503.

Feel free to create a PR clarifying that a user needs to be assigned one of the roles in addition to any group they want to use.

**Comment by CtripleU** [comment]
Thank you for the correction, @wbrunette. I will create a PR just as you have explained.
