### ISSUE TITLE
Fix typo in Documentation - ODK-X Services

### ISSUE THREAD

**Issue by sheykerkup** [opendatakit/tool-suite-X#316]
-  In the section **Syncing**,  `The username can be be changed by pressing the Change User button. Instructions are provided in the Authenticating Users section.` Repetition of 'be'.

-  In the section **Syncing**, `When you are ready to sync you data click on Sync Now.` Should be `When you are ready to sync your data, click on Sync Now.` 

-  In the section **Tables Settings**,  `Use Custom Home Screen chooses whether to display the index.html file of your Data Management Application or the list of tables when ODK-X Tables is launched.`  Should be `to choose`.

**Comment by sheykerkup** [comment]
@wbrunette @clarlars  would like to send  PR for this

**Comment by wbrunette** [comment]
@sheykerkup on your third bullet 'choose' would be incorrect, how about 'selects' 

I have assigned the issue to you.

**Comment by wbrunette** [comment]
In the future there is already a line edits in the documentation for finding and fixing documentation errors https://github.com/odk-x/tool-suite-X/issues/207

**Comment by sheykerkup** [comment]
> In the future there is already a line edits in the documentation for finding and fixing documentation errors #207

OK I see it. Should I close all these issues I created regarding line edits then?

**Comment by wbrunette** [comment]
The page the edits are needed is: https://docs.odk-x.org/services-using/

**Comment by AliceUmeji** [comment]
Hi @wbrunette can I be assigned this task?

**Comment by wbrunette** [comment]
@AliceUmeji I have assigned the issue to you

**Comment by AliceUmeji** [comment]
@wbrunette thank you. 

Please I tried looking for but can't find the code, can you help me out @wbrunette? Thanks

**Comment by AliceUmeji** [comment]
@wbrunette I have submitted a pull request.

https://github.com/odk-x/docs/pull/214

Thank you.
