### ISSUE TITLE
Fix typos in documentation - Managing ODK-X Services

### ISSUE THREAD

**Issue by sheykerkup** [opendatakit/tool-suite-X#317]
Page **Managing ODK-X Services** of the Documentation [Managing ODK-X Services](https://docs.odk-x.org/services-managing/) has the following typos;

-  In the section **Resetting the App Server**,  `The username can be be changed by pressing the Change User button.`  Repetition in the word `be`.

-  In the section **Resetting the App Server**,  `A confirmation dialog will popup asking you to confirm resetting the App Server.` Should be `pop up`.

-  In the section  **Setting an Administrator Password**,  `After creating an admin password, the screen show show that it is enabled. `Should be `After creating an admin password, the screen shows that it is enabled`.

- In the section **Managing Server Settings**  `Allow unsafe/unsecure Authentication - if checked Services will.`  Should be unsecured.

**Comment by sheykerkup** [comment]
@wbrunette @clarlars  would like to send  PR for this

**Comment by wbrunette** [comment]
@sheykerkup go ahead and prepare a PR to fix the issues.

**Comment by wbrunette** [comment]
NOTE: The spelling of "popup" is correct when referring to a computing UI visual element, so there is one less change.

**Comment by bossintroverts** [comment]
hello @wbrunette can I be assigned this please?

**Comment by Sukriti-sood** [comment]
@wbrunette  Can I work on this issue

**Comment by wbrunette** [comment]
@Sukriti-sood I have assigned the issue to you
