### ISSUE TITLE
No Input Validation When finalizing a form

### ISSUE THREAD

**Issue by Lamouresparus** [opendatakit/tool-suite-X#325]
In the Survey App, I can create a blank form. This because, I can go to next without selecting any option, or typing anything.
This is understandable, because you can mark the instance as incomplete. My concern is the fact that you could actualy finalize an empty form (that is no entry was recorded). Is this a bug, or is this how its supposed to work?

**Comment by wbrunette** [comment]
There is the required column in form definition that if set to true will require the question be answered before the user can move on. It's up to the form designer to decide if the question is required or not.
