### ISSUE TITLE
Fix the end of the AWS instructions

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#330]
1) The 'Launching the ODK-X Server' section does not show a screenshot of the web-ui login ( http://[IP_ADDRESS]/web-ui/login) the screenshot incorrectly has the users/group login.
2) The instructions to take the stack up and down are out of date. They should be

Take the stack/swarm down:
"docker stack rm syncldap"

Bring the stack/swarm up with HTTPS support execute this command in the sync-endpoint-default-setup folder:
"docker stack deploy -c docker-compose.yml -c docker-compose-https.yml syncldap" 

3) The revised instructions for starting/stopping the Stack/Swarm should be placed in a subsection at the same level as Option 1, Option 2, Option 3, and Anonymous Access sections.

**Comment by vkamunya** [comment]
Hello @wbrunette  I'm new to contributing and wanted to work on this issue, where do I edit the documentation to be able to make the changes? Thanks

**Comment by vkamunya** [comment]
Hello @wbrunette wbrunnette, could you assign me this issue?

**Comment by wbrunette** [comment]
@vkamunya I have assigned the issue to you

**Comment by AnshuKumari197** [comment]
can i work on this issue ?
