### ISSUE TITLE
Fix CSV naming on Suitcase export

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#333]
When Suitcase downloads a table and saves the contents in into a CSV file the CSV file is named "link_unformatted". The CSV filename should be the table id so it should be "<table_id>.csv"

**Comment by sanyud24** [comment]
hi , can i work on this issue @wbrunette

**Comment by wbrunette** [comment]
@sanyud24 I am assigning the issue to you

**Comment by wbrunette** [comment]
@sanyud24 can you give us an update on your progress?

**Comment by sanyud24** [comment]
sorry for the delay, will be submitting the PR today.
