### ISSUE TITLE
Fix error in Docs about missing reference label

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#335]
A label got changed with this PR now we are getting this error:

sync-endpoint.rst:144:undefined label: sync-endpoint-setup-create-user

Because of this PR deleted the reference label.
https://github.com/odk-x/docs/pull/208

**Comment by aasthaa-007** [comment]
Hi @wbrunette 
I would like to fix the issue 
Can I proceed?

**Comment by wbrunette** [comment]
@aasthaa-007 I have assigned the issue to you
