### ISSUE TITLE
Remove OI file manager from "How to Delete All ODK-X Data" video

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#336]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X. Some include OI file manager, which has gone away as a requirement in more recent versions. We need to redo videos that had OI file manager to show instead operations using Google Files.

This issue is to revise the "How to Delete All ODK-X Data" video -- https://www.youtube.com/watch?v=KNogiu-crzA -- you can make other improvements as well, but the current video is a good example/starting point. 

See also discussion here in general: https://github.com/odk-x/tool-suite-X/issues/299

**Comment by mustafaali10** [comment]
I am supposed to produce a video where we delete all the ODK-X Data using Google Files instead of OI File Manager.

Did I get it right @elmps2018 Ma'am ? And if yes I would like to work on it !

**Comment by elmps2018** [comment]
Hi @mustafaali10! Yes, you have the right idea! I just assigned you to this issue! Let us know if you have any questions while working away.

**Comment by mustafaali10** [comment]
@elmps2018 Ma'am it's done!  Sorry for taking a while as I wasn't well the past days.

Here's the video : https://drive.google.com/file/d/1UlY6eO6E9e6y0-qGywpskQqaxWWNRbVC/view?usp=sharing

I request you to have a look and let me know any changes to be made !

Thanks.

**Comment by elmps2018** [comment]
@mustafaali10 thanks this looks good! I'll upload it to Youtube next.

**Comment by mustafaali10** [comment]
Thanks @elmps2018 Ma'am ! 👍😄
