### ISSUE TITLE
Remove OI file manager from "How to Export Data in ODK-X Tables" video

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#338]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X. Some include OI file manager, which has gone away as a requirement in more recent versions. We need to redo videos that had OI file manager to show instead operations using Google Files.

This issue is to revise the "How to Export Data in ODK-X Tables" video -- https://www.youtube.com/watch?v=zqp69HA77eo -- you can make other improvements as well, but the current video is a good example/starting point. 

See also discussion here in general: https://github.com/odk-x/tool-suite-X/issues/299

**Comment by nuilewis** [comment]
Hello, I would like to claim this issue, please

**Comment by elmps2018** [comment]
Great, @nuilewis assigned to you! Let us know if you have any questions while working away.

**Comment by nuilewis** [comment]
Thank you, So I was thinking the best way to go about it would be to recreate the video, so I was able to get the applications, but I wanted to find out if there is some sample data or dummy data that I can use to show how to export data?

**Comment by elmps2018** [comment]
Great question @nuilewis! Yes, either the Tables or Survey demos would be good (you can create data or use existing data from the Tables demo):
https://docs.odk-x.org/survey-sample-app-install/
https://docs.odk-x.org/tables-sample-app-install/

**Comment by nuilewis** [comment]
Alright, thanks!

**Comment by nuilewis** [comment]
Hello, I am done with the video, I decided to make it a 16:9 aspect ratio and added additional text to make it easier to follow along, with some music. I was wondering what's the best way to send the video for review?, would a link on Google Drive work?

**Comment by elmps2018** [comment]
Hi @nuilewis! A google drive link is great! I am not sure about including music -- there may be copyright issues.

**Comment by nuilewis** [comment]
I made sure to use royalty-free music, so I don't think copyrights will be an issue

**Comment by nuilewis** [comment]
https://drive.google.com/file/d/1bDCfBwBRmxC4bjPb_tE3ynomvkRtlxzW/view?usp=sharing
Here is the link to the file.

**Comment by nuilewis** [comment]
I'll be waiting for your feedback, please. Thanks!

**Comment by elmps2018** [comment]
Hi @nuilewis! This looks good! If you can just add one detail, to point out that the data are in the table_id.csv file (and that the other two are the table properties and definitions) that would be great! Then I think it's set.

**Comment by nuilewis** [comment]
alright

**Comment by nuilewis** [comment]
Hello, this is the link for the updated video
https://drive.google.com/file/d/1Cdm-VAYivdTzqM6YVCIzfU-f9pA6G4IL/view?usp=sharing

please have a look whether it's okay, thanks!

**Comment by nuilewis** [comment]
Please use this instead, I made some slight changes

https://drive.google.com/file/d/1fJTbiQ1kqbHTdx07pHsCkqnChBp-e2Ve/view?usp=drivesdk

**Comment by elmps2018** [comment]
Hi @nuilewis! Can you just change where it says table_id.csv folder to table_id.csv file? Otherwise looks good.

**Comment by nuilewis** [comment]
okay

**Comment by nuilewis** [comment]
here's the updated video
https://drive.google.com/file/d/1k4rKtmOlyBXu1wmK6-2ZUqS7lNG-JMK1/view?usp=sharing

**Comment by elmps2018** [comment]
Hi @nuilewis! This looks great, I think the only thing is you had the ODK rather than ODK-X logo at the end. If you just want to delete that part of the video or swap out for the ODK-X logo then all set and I will upload.

**Comment by nuilewis** [comment]
> Hi @nuilewis! This looks great, I think the only thing is you had the ODK rather than ODK-X logo at the end. If you just want to delete that part of the video or swap out for the ODK-X logo then all set and I will upload. 

Okay, I tried to find the ODK-X logo but couldn't find one that was good enough or high res enough for the video so I used the ODK logo. I guess I'll remove the logo then.

**Comment by nuilewis** [comment]
Hello @elmps2018 I was able to replace the ODK logo with the ODK-X logo, here's the link.

https://drive.google.com/file/d/1kbTrF4L4wMQPbgpvB1M8VuhE6EYpjYae/view?usp=drivesdk

**Comment by elmps2018** [comment]
@nuilewis Great, I just uploaded it to our YouTube channel, should be visible soon! Thanks for working on this and make sure to record your contribution.

**Comment by nuilewis** [comment]
> @nuilewis Great, I just uploaded it to our YouTube channel, should be visible soon! Thanks for working on this and make sure to record your contribution. 

Okay, thanks!
