### ISSUE TITLE
Remove OI file manager from "How to Zip and Share ODK-X Data" video

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#339]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X. Some include OI file manager, which has gone away as a requirement in more recent versions. We need to redo videos that had OI file manager to show instead operations using Google Files.

This issue is to revise the "How to Zip and Share ODK-X Data" video -- https://www.youtube.com/watch?v=jzqu7w4VepM -- you can make other improvements as well, but the current video is a good example/starting point.

See also discussion here in general: https://github.com/odk-x/tool-suite-X/issues/299

**Comment by permission-error1** [comment]
Hi @elmps2018 I would like to work on this.

**Comment by elmps2018** [comment]
@julian55455 great, I assigned it to you! Let me know if you have any questions while working away.

**Comment by permission-error1** [comment]
> @julian55455 great, I assigned it to you! Let me know if you have any questions while working away.

@elmps2018 Do we just have to  use a screen record of an android device or you have some other specific tools you use to record these videos

**Comment by elmps2018** [comment]
Hi @julian55455! You can definitely do this with a screen recording to capture the work on the tablet. It's nice if you can make sure to have a pointer as you record or highlight in video editing software after. But anything that will create a video that can be uploaded to YouTube works!

**Comment by permission-error1** [comment]
@elmps2018 not so sure whether you linked the right example of the video for this issue but I still fail to import the data in .csv format in the adk-x tables app.
**I get an error Import file must reside in opendatakit folder**
An example of the video can be found on my google drive
https://drive.google.com/file/d/12s4UGaCnB_gromkGgY2gGuAhxsQRtOJI/view?usp=sharing

cc @wbrunette @elmps2018

**Comment by elmps2018** [comment]
Hi @julian55455! This is a "correct" error. As per the importing directions: 
https://docs.odk-x.org/tables-managing/#importing-data
The file you import needs to be in a specific location. If you put it there hopefully will then work!

**Comment by permission-error1** [comment]
@elmps2018 even when I place this file in `**opendatakit folder**` nothing seems working.

Is it working from your side?
cc @wbrunette

**Comment by elmps2018** [comment]
@julian55455 it's not just the open data kit folder generally, it's the exact location listed in the directions.

**Comment by permission-error1** [comment]
> @julian55455 it's not just the open data kit folder generally, it's the exact location listed in the directions.

@elmps2018  do you mean something like this `opendatakit/default/config/assets/csv/.csv`?. Because that's what am doing

**Comment by elmps2018** [comment]
Yes, except .csv should be tableid.csv where tableid is replaced with the name of the table you are trying to import into.

**Comment by permission-error1** [comment]
Hey @elmps2018  I need your review here https://drive.google.com/file/d/1GVEUMDu6Tc0h47Npj8hfkcQd8j1JdroB/view?usp=sharing

**Comment by permission-error1** [comment]
> On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X. Some include OI file manager, which has gone away as a requirement in more recent versions. We need to redo videos that had OI file manager to show instead operations using Google Files.
> 
> This issue is to revise the "How to Delete All ODK-X Data" video -- https://www.youtube.com/watch?v=Kzut6Xrv3SM -- you can make other improvements as well, but the current video is a good example/starting point.
> 
> See also discussion here in general: #299

@elmps2018 I think we could change the link of the youtube of this issue to something like https://www.youtube.com/watch?v=jzqu7w4VepM

**Comment by elmps2018** [comment]
Hi @julian55455! Okay, a bit confused here with the different issues! I may have put the wrong link, so fixed that, but did you mean to do the importing one or this one? Your comments were about importing, which is different than zip or share.

**Comment by permission-error1** [comment]
@elmps2018 actually I noticed later that the link to youtube was different from the issue description. So I left importing and did what the description of the issue  required How to `Zip and share ODK-X Data` and uploaded a new different video on my drive  https://drive.google.com/file/d/1GVEUMDu6Tc0h47Npj8hfkcQd8j1JdroB/view?usp=sharing

**Comment by permission-error1** [comment]
@elmps2018  Sorry for confusing you but at first I was mislead by the youtube link of importing

**Comment by elmps2018** [comment]
@julian55455 great this is the right content now! Can you do the start slower (show files for longer, for example) and then speed up the compression? You may be able to do this with video editing software (or just cut out the time between 5% and 90% or something).

**Comment by permission-error1** [comment]
@elmps2018 does this look any better
 https://drive.google.com/file/d/1k1ShuSq6fMUnXcyLB6TeSvmSqAelG_ms/view?usp=sharing

**Comment by Ndacyayisenga-droid** [comment]
@elmps2018

**Comment by elmps2018** [comment]
@julian55455 looks great! I'll upload to YouTube channel next. Thanks! Make sure to record your contribution!
