### ISSUE TITLE
Remove OI file manager from "How to install basic ODK-X tools on your tablet" video

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#340]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X. Some include OI file manager, which has gone away as a requirement in more recent versions. We need to redo videos that had OI file manager to show instead operations using Google Files.

This issue is to revise the "How to install basic ODK-X tools on your tablet" video -- https://www.youtube.com/watch?v=_387vP9CO9M -- you can make other improvements as well, but the current video is a good example/starting point. 

See also discussion here in general: https://github.com/odk-x/tool-suite-X/issues/299

**Comment by jesse5555** [comment]
hey @elmps2018
I kindly request to be assigned this

**Comment by elmps2018** [comment]
@jesse5555 just assigned you now! Let us know any questions.

**Comment by S1Y333** [comment]
Hi @elmps2018, does this issue still need to be worked on? If so, can you please assign me this? Thank you

**Comment by elmps2018** [comment]
@S1Y333 yes this still needs doing I assigned to you! Please see the current video linked in the issue above and redo with Google Files instead.

**Comment by S1Y333** [comment]
> @S1Y333 yes this still needs doing I assigned to you! Please see the current video linked in the issue above and redo with Google Files instead.

@elmps2018 Hi Caroline, can I use iPad to record this video because I don't have Andriod tablet? Or I should use Google’s Android Emulator? Thank you

**Comment by elmps2018** [comment]
@S1Y333 the ODK-X tools only work on Android tablets, so I don't think an iPad would work. You might be able to record with an Android emulator.

**Comment by S1Y333** [comment]
@elmps2018 Hi Caroline, please find the video here --> https://drive.google.com/file/d/1lrei-x1oPI1FBuAclLfWeKA4wEjjXsg0/view?usp=share_link

Let me know if it's good to go. Many thanks

**Comment by elmps2018** [comment]
Hi @S1Y333 this is great, thanks for working on this! I uploaded the video to our YouTube channel!
