### ISSUE TITLE
Video of setting up ODK-X Sync Endpoint Users and Groups

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#344]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X.

This issue is to create a video demo of setting up users and groups

Here are the docs instructions: https://docs.odk-x.org/sync-endpoint-user-instructions/

Note you will need to set up a server to test, see options here: https://docs.odk-x.org/sync-endpoint-cloud-setup/

**Comment by sanyud24** [comment]
Hi, @elmps2018 may I work on this issue?

**Comment by elmps2018** [comment]
Hi @sanyud24 just assigned you to this issue! Let us know any questions as you are working away.

**Comment by sanyud24** [comment]
https://drive.google.com/file/d/1bOAENDMsi7c5rrJIOdLkmr-I95CxPPDx/view?usp=sharing 
Did the tutorial on setting up ODK-X Sync Endpoint Users and Groups @elmps2018

**Comment by elmps2018** [comment]
Hi @sanyud24 thanks for working on this! It looks super close, I am just going to ask @matt9j or @wbrunette to check on the technical details! I did notice adding an entry directly rather than a child at the start and group #507

**Comment by sanyud24** [comment]
Sure @elmps2018 I'll fix that

**Comment by sanyud24** [comment]
Hi @elmps2018 , did it with the child entry https://drive.google.com/file/d/1dKzJzQxkhD9wzPxeFhYYhA9KKle3V-qy/view?usp=sharing

**Comment by elmps2018** [comment]
@sanyud24 great! @wbrunette or @matt9j please check the technical details.

**Comment by matt9j** [comment]
Hi @sanyud24, thanks for your contribution! The users part of the video looks great to me! The groups part is almost set, but is missing the detail that the group names have to have a particular structure. This is the note in the group creation documentation:

> The group name must start with the group prefix, in this case the group prefix is `default_prefix` so for example: `default_prefix my-new-group`

**Comment by sanyud24** [comment]
Sure @matt9j !! will make the changes.

**Comment by sanyud24** [comment]
https://drive.google.com/file/d/1fL5PIGxr-0RlsE1Z3T3kRmMyPT3aZVlq/view?usp=sharing
Did the final changes @matt9j @elmps2018

**Comment by elmps2018** [comment]
@matt9j if you can recheck this addressed your comment and let us know that would be great!

**Comment by matt9j** [comment]
That looks great! Thanks for y'alls patience with a late reply!

**Comment by elmps2018** [comment]
@matt9j thanks! @sanyud24 I'll get this added to YouTube next, thanks for working on this!
