### ISSUE TITLE
Video of using ODK-X Suitcase - Graphical interface

### ISSUE THREAD

**Issue by elmps2018** [opendatakit/tool-suite-X#345]
On our YouTube [channel](https://www.youtube.com/channel/UCxOZGaf3xUiD85q8qJaw2bQ), there are a number of videos demo-ing various features of ODK-X.

This issue is to create a video demo of ODK-X Suitcase (graphical interface) 

Here are the docs instructions: https://docs.odk-x.org/suitcase-intro/

**Comment by shreyavijayvargiya** [comment]
@elmps2018 what should be the username and password to open ODK-X Suitcase? I read the documentation but it's still unclear to me and I'm not able to login anonymously too.

**Comment by elmps2018** [comment]
You may be able to download from one of the demo servers:
-https://docs.odk-x.org/tables-sample-app-install/
- https://docs.odk-x.org/survey-sample-app-install/

@wbrunette or @linl33 do you know if these should allow demoing suitcase?

If not, you may need to set up a demo server or see if someone working on a demo server will let you demo suitcase with it.

**Comment by wbrunette** [comment]
Yes, Suitcase will work with the demo servers. I do not remember off the top of my head if Suitcase supports anonymous users so it is probably best to use the username/password login.

**Comment by shreyavijayvargiya** [comment]
@elmps2018 @wbrunette I downloaded the odk-x suitcase .jar file and proceeded as mentioned in the documentation but I have a few concerns-
1. In the download tab -> I'm getting an error message on the screen but still the CSV files are getting downloaded on my system.
2. Nothing about the update tab or clear tab is mentioned in the documentation.
3. In the clear tab, when I click the delete button it says "unable to reach cloud endpoint server", can you tell me how to resolve this?
4. The reset button is shifted to the clear tab but in documentation, it is mentioned in the upload tab. Will the reset button remove all the tables from the server and will they be unretrievable? 

Also, could you please assign this issue to me and let me know if this will be considered as a contribution to the Outreachy project "UI uplift for mobile apps"

**Comment by elmps2018** [comment]
Hi @shreyavijayvargiya can you send a screen shot of the error message for (1) and explain a bit more about what steps you are taking that lead to the error message? 
@wbrunette are there new tabs that need to get documented for (2)
(3) it may not allow you to clear the server (you may not have permissions to clear the demo server). For the video you can just point to it and note what it does rather than demo it. 
(4) The reset button does remove all the tables from the server, but as with (3) if you point to these and note what they do rather than a full demo I think that's fine. 

Assigning to you -- yes, a video is definitely a contribution!

**Comment by shreyavijayvargiya** [comment]
@elmps2018 
![Screenshot (20)](https://user-images.githubusercontent.com/57625355/162577892-829a2f6c-2da0-4e51-85d6-98a8021db443.png)


I get this error message every time I select any of the following- download attachments, apply scan formatting, or extra metadata columns, but still, the CSV files are getting downloaded on my system so I think that the feature is working fine but I don't know why the error message is getting displayed every time.


<img width="859" alt="img" src="https://user-images.githubusercontent.com/57625355/162577997-1d0a243f-ec53-48ee-826d-cd918f71c94f.png">

**Comment by elmps2018** [comment]
Hi @shreyavijayvargiya! I am not sure what the problem is either, can you maybe create an issue with this error? If you want to do the video without selecting those options and just highlight that you can select them if you want, that would work.

**Comment by shreyavijayvargiya** [comment]
@elmps2018 Here's the drive link for the video. Please check once.
https://drive.google.com/file/d/1Z--MceQOE0rWe2HUWkOenMf3SpJ1gIAV/view?usp=sharing

**Comment by elmps2018** [comment]
Hi @shreyavijayvargiya! Thanks for working on this! I think you can skip the installation step (which will also be confusing because there will be newer versions than 2.1.9). Starting with the Suitcase interface the demo video is helpful! If you can trim the video to be just that it would be great.

**Comment by shreyavijayvargiya** [comment]
@elmps2018 Please check the updated link-
https://drive.google.com/file/d/1K0iJcPS0K_89_LdGymjs50-R4cO-4im7/view?usp=sharing

**Comment by elmps2018** [comment]
Great thanks @shreyavijayvargiya I'll upload it to the Youtube next!
