### ISSUE TITLE
Hide/Show password icon in Services 

### ISSUE THREAD

**Issue by sanyud24** [opendatakit/tool-suite-X#347]
The show password icon should show the password but the functionality has been reversed in both server password and change admin password dialog box.

...................................................................................................
![adminpass](https://user-images.githubusercontent.com/57134307/160936343-34840b66-b4ea-42ca-acc6-8f6ac55fb7af.jpeg)
![serverpass](https://user-images.githubusercontent.com/57134307/160936354-01cd77dd-58b1-4002-8107-4619e4c3c479.jpeg)

**Comment by sanyud24** [comment]
@wbrunette @elmps2018 May I work on this issue if it seems valid?

**Comment by wbrunette** [comment]
1) we have an open issue about this already so I am closing this a duplicate https://github.com/odk-x/tool-suite-X/issues/257
2) The password already has a new UI waiting to be tested
