### ISSUE TITLE
FOR OUTREACHY UI UPLIFT PROJECT - UI improvement: consistent menu items under the ellipsis

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#349]
The scope of this issue is to determine a consistent set of menu items under the ellipsis in the mobile app header for Services, Survey and Tables. 

By making the menu items consistent, users should be able to more easily learn where certain functions are in an application. 

Objectives: 
- Provide consistent menu layouts within applications
- Make it easier for users to learn which functions will be under the ellipsis

In this issue you can focus on one app. For the Outreachy project, we will aim for greater consistency across the mobile apps: Tables, Services and Survey. 

Guidance for this issue:

- Look at Survey, Tables or Services and become familiar with the current menu layouts throughout the app
- Provide a redesign of the menu items that meets the objectives
- Checkout the project for the mobile app
- Find the menu files and apply the design improvements 
- Build the project, screenshot the improvement in the emulator
- Write a brief description including a rationale for the design that you applied
- Post the description and screenshots back to this issue

This issue can be used for an Outreachy application for the project [User interface uplift for mobile apps](https://www.outreachy.org/outreachy-may-2022-internship-round/communities/odk-x/#user-interface-uplift-for-mobile-apps)

Please request to be assigned to the issue so we can track the number of peopling doing this exercise. Multiple people can work on this issue simultaneously.

**Comment by kavyarishi19** [comment]
Kindly assign me this issue

**Comment by wbrunette** [comment]
@kavyarishi19 I have added you to the issue, as a reminder multiple people can work on this issue.

**Comment by AliceUmeji** [comment]
Can I also be assigned to this issue?

**Comment by kavyarishi19** [comment]
The following changes have been made in the UI of Tables app:
![UIChanges1](https://user-images.githubusercontent.com/78750829/162567190-fff6465f-8443-470a-b0cc-acd1517051ef.jpeg)
The colour of the outline icons have been changed to Dark Blue along with some changes in the icons 
The icons used before were 
![Screenshot (82)](https://user-images.githubusercontent.com/78750829/162567356-e8ce89ff-b65d-4cbe-8a87-fb6af70a166b.png)
Colour and design changes have been made  in the icons: 
![image](https://user-images.githubusercontent.com/78750829/162567666-c645e8a2-106b-47fc-82ca-3fc7f832844b.png)
Previously we had these icons:
![Screenshot (83)](https://user-images.githubusercontent.com/78750829/162567799-f5f3c20a-0159-476a-ba78-976531612ff7.png)
Following font changes have been made in the subheadings : 
![image](https://user-images.githubusercontent.com/78750829/162567871-fd8b300a-670e-4961-a6da-d93635c14ec4.png)
![image](https://user-images.githubusercontent.com/78750829/162567893-3eac66e7-ec47-40ae-8d2a-1eac69c95b98.png)

The changes have been made keeping the ODK-X Design Guidelines 
The rationale behind the changes are :
1.Dark blue for outline icons etc. where clear and precise is required
2.Light blue - use as primary brand colour, headings, links etc.
3.Yellow - use as secondary brand colour, occasional headings, highlights etc.
4.Shades for use in backgrounds of info boxes, warning messages etc. 

The changes in icons are based on the rationale that the current icons should be aesthetically pleasing and providing it with the unique flavour and making it stand apart from other applications. 
I had following objectives in mind while making the UI changes.
Objectives:
- Provide consistent menu layouts within applications
- Make it easier for users to learn which functions will be under the ellipsis

The changes in Font style are: Montserrat for headings and Source sans pro for paragraph text .

**Comment by kavyarishi19** [comment]
@maprehensive 

@wbrunette

**Comment by maprehensive** [comment]
@kavyarishi19 Thanks for the contribution, the UI changes are well articulated. 

My feedback is to also focus on improvements to consistency and learnability of the menu items that presented on the menu bar and under the ellipsis. 

Here's a good reference for the principle: [Ten Usability Heuristics: #4: Consistency and standards](https://www.nngroup.com/articles/ten-usability-heuristics/).

So your redesign should look to improve the layout of the menus as well as improving the visual look and feel. 

Hope that helps!
Ben

**Comment by AliceUmeji** [comment]
Can I work on this issue @maprehensive?

**Comment by wbrunette** [comment]
@AliceUmeji I have added you to the issue, as a reminder multiple people can work on this issue.

**Comment by AliceUmeji** [comment]
Here is my submission. Thank you.
https://docs.google.com/document/d/1I5Zhl8wBDzLztbvX17fc7qBh5J9ZqGxQA10rCcb8qRc/edit?usp=sharing

**Comment by AliceUmeji** [comment]
Quick question @wbrunette, @maprehensive and Caroline please. I'd like to keep working on this project. Do I continue redesigning or should I focus on the issues instead? Thank you.

**Comment by maprehensive** [comment]
This issue will be closed as the Outreachy applications have concluded.
