### ISSUE TITLE
(broken link) see example installation on Ubuntu link, points to the repo's github main page

### ISSUE THREAD

**Issue by jesse5555** [opendatakit/tool-suite-X#351]
while trying to [build]( https://github.com/odk-x/sync-endpoint-default-setup#build) the [sync-endpoint-default-setup]( https://github.com/odk-x/sync-endpoint-default-setup) repo,  using Ubuntu seams to be a much easier but its link just does nothing and opens the repo's main page on opening in a new browser.

Below is a simple video for this.

https://user-images.githubusercontent.com/99703219/163380935-e29fd53e-aabd-4f0b-b917-c81c60831030.mp4

**Comment by jesse5555** [comment]
hello @matt9j @elmps2018
If this issue makes sense, i kindly request it to be assigned to me

**Comment by jesse5555** [comment]
If you don't mind, you can also add **simple** and **docs** label or its equivalent showing that the fix is a one-line patch in docs
Thank you

**Comment by elmps2018** [comment]
@jesse5555 assigned to you, if you can fix the link that's great!

**Comment by jesse5555** [comment]
hey @elmps2018 I kindly request for a review from you.
