### ISSUE TITLE
odk-x_Suitcase- Error in downloading tables csv

### ISSUE THREAD

**Issue by shreyavijayvargiya** [opendatakit/tool-suite-X#354]
I'm attaching the screen recording here of the error message I'm getting in downloading the files in odk-x_suitcase.
https://drive.google.com/file/d/11bulGC-Yb6m4Z0Xq_KIcyRmlv5RY8bvv/view?usp=sharing

**Comment by wbrunette** [comment]
@shreyavijayvargiya thank you for providing the video, it's very helpful. My first question is why are you applying "Scan formatting" to a non-Scan enabled form?

**Comment by shreyavijayvargiya** [comment]
@wbrunette can you please tell me how to differentiate between which is a scan-enabled form and which one is not?
Rest I think I understand now why I'm getting this error message. Thanks!

**Comment by wbrunette** [comment]
Check out: https://docs.odk-x.org/scan-intro/
