### ISSUE TITLE
ODK-X Services - Menu navigation UI improvement

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#358]
The ODK-X Services mobile app has multiple menu navigation states, depending on where the user is in the application.

The menu navigation is a mix of icons and text items under the ellipsis menu. The mix changes on different screens:

![Screenshot_Services01](https://user-images.githubusercontent.com/1215441/193394603-04354027-4001-4021-8905-cfa07126a406.png)
![Screenshot_Services02](https://user-images.githubusercontent.com/1215441/193394606-cc384024-98a6-4500-88b1-af127ee4ff48.png)
![Screenshot_Services03](https://user-images.githubusercontent.com/1215441/193394608-b5ac7da7-618d-481f-b2d9-4f326cf9bc7e.png)

## Why this needs to be improved:
- icons do not currently communicate the function they link to. The function needs to be learned by the user.
- the placement of menu items is different across the screens

## Objectives: 
- Limit icon use to functions that can be immediately recognized from the icon by most users
- Make the menus consistent across the application

## Guidance for this issue:
- Look at Services and become familiar with the current menu layouts throughout the app
- Provide a redesign of the menu items that meets the objectives
- Write a brief description including a rationale for the design that you applied
- Post the description and screenshots back to this issue

## Design Guidelines:
Colours, icons and other user interface elements used should conform to the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

## Outreachy
This issue can be used for an Outreachy application for the project [Custom UI components for ODK-X mobile apps](https://www.outreachy.org/apply/project-selection/#odk-x)
**This issue is for the User Interface Design stream of the project.**

Multiple people can work on this issue simultaneously.

**Comment by BlueSkiez-dev** [comment]
Hi @wbrunette I would like to work on this issue

**Comment by maprehensive** [comment]
@BlueSkiez-dev You're assigned. Thanks!

**Comment by EQua-Dev** [comment]
Hi @maprehensive, please can I be assigned this task?

**Comment by BlueSkiez-dev** [comment]
@maprehensive Proposed redesign for Issue #360 
![ezgif-5-b4c8b35d2d](https://user-images.githubusercontent.com/67054844/194762862-c6efc7a8-8f24-408c-86f5-788926afa43a.gif)

The decisions influencing the design and the details of the redesign are as follows:
<img width="863" alt="Frame 12" src="https://user-images.githubusercontent.com/67054844/194762915-f459c696-e889-45fc-b8b4-82ecf8129f7b.png">
<img width="863" alt="Frame 13" src="https://user-images.githubusercontent.com/67054844/194762917-847457dc-bdfa-4edc-888d-da60ce2f7eff.png">

Please let me know If I missed anything, thanks guys!

**Comment by permission-error1** [comment]
Hi @maprehensive i would like to work on this

**Comment by maprehensive** [comment]
@EQua-Dev you're assigned. Thanks!

**Comment by maprehensive** [comment]
@julian55455 you're assigned. Thanks!

**Comment by maprehensive** [comment]
@BlueSkiez-dev That's a great proposal, very nicely articulated. 

The consistency and simplicity is good. One thing to consider is whether there are any screens that Sync function should not be available from?

**Comment by BlueSkiez-dev** [comment]
Yes indeed.
Here's what I propose in that case @maprehensive 


<img width="863" alt="Frame 12" src="https://user-images.githubusercontent.com/67054844/194831330-89e1e8f6-bc37-48bb-afb5-5925a523b8e9.png">

**Comment by ghost** [comment]
I would love to work on this issue @maprehensive @wbrunette

**Comment by Augusta2** [comment]
@maprehensive  Please I will love to work on this issue

**Comment by Augusta2** [comment]
Hello @maprehensive,  I already finished this project although I was not assigned to it. If I must be, Can you please assign it?
I will still post screen shots just in case. Thanks

**Comment by Augusta2** [comment]
@maprehensive This is my work on the Menu Navigation UI improvement.
I tried to make navigation throughout the application easier.
Please correct me if I'm missing anything.

![Augusta_Home page](https://user-images.githubusercontent.com/115414092/195337207-c95a5f36-eadd-45b4-97b0-a4bce692de4e.jpg)
![Augusta_Menu](https://user-images.githubusercontent.com/115414092/195337244-5780d514-18a7-412f-9fba-13c27622b337.jpg)
![Augusta_Project description1](https://user-images.githubusercontent.com/115414092/195337365-2203560d-5419-4ac8-837d-8654d721799b.jpg)
![Augusta_Project description2](https://user-images.githubusercontent.com/115414092/195337395-6ec7c06d-4d2f-41dc-bafc-5c72bd6839ec.jpg)
![Augusta_Project description3](https://user-images.githubusercontent.com/115414092/195337437-d1e9f057-cf0b-41b0-9ddf-a32e1910c57f.jpg)
![Augusta_Project description4](https://user-images.githubusercontent.com/115414092/195337460-f6586216-fae1-4891-b543-7d0e7cc0f7cb.jpg)

This is the link to the [prototype on Figma ](https://www.figma.com/proto/acrU99IH3PedOPYpaN4jnT/Untitled?node-id=12%3A379&scaling=min-zoom&page-id=12%3A378&starting-point-node-id=12%3A379)

This is the link to the [Usability study](https://docs.google.com/presentation/d/11pm-Cs_kbXYKcM5NzahNrrCZlbGVjkKq/edit?usp=drivesdk&ouid=108047287310748611678&rtpof=true&sd=true) I conducted and Description

**Comment by caxrii** [comment]
@maprehensive I'd like to work on this

**Comment by maprehensive** [comment]
@Caxri7 You can work on this without being assigned - go for it!

**Comment by caxrii** [comment]
![ODK-X Services](https://user-images.githubusercontent.com/99927193/196489389-b0d02020-a3f7-402c-90bf-22f784bcc37e.png)
![ODK-X Services 03](https://user-images.githubusercontent.com/99927193/196489217-17e7aadb-c820-4122-83dd-7fa0f205b50e.png)
![ODK-X Services 02](https://user-images.githubusercontent.com/99927193/196489205-4e3b4735-f7bb-4cf4-8bd2-7bcb7f197c40.png)
![ODK-X Services 01](https://user-images.githubusercontent.com/99927193/196489187-db74421e-eecd-4096-bddb-c03c035d43f1.png)
![ODK-X Services 4](https://user-images.githubusercontent.com/99927193/196501794-0bf1d2c2-edcf-4ddb-981c-97fa5d3f9da1.png)

@maprehensive 
This is my contribution to the issue.
The change user/logout and update user permissions should be in the settings page. The update user permissions have the same function with the verify user permissions in the settings page which is confusing, this led to the redesign of the settings page.
I added the logout function and user permission to the settings page with icons that communicates the real functions.
I made the icons across the settings page consistent.
I used the required icon size in the design guide.
I also used the color and spacing stated in the design guide for my designs.

**Comment by Rubadel** [comment]
@maprehensive 

**At the first** for the **sync status icons**,
it is better to be appear based on the sync status, and when click on them show the releted function, 

these video display what I mean :

**Conflict sync status** 

https://user-images.githubusercontent.com/66481905/196920633-3d61413a-3869-4493-973a-f39e7e7ac0c3.mov

The Icon of sync appear as there is problem with sync, and  the clicking on it will start the resolve problem with toast message for the user.

**normal sync status**

https://user-images.githubusercontent.com/66481905/196921135-1ec8f1e8-0468-4691-bf06-1b4f0e4f9ced.mov

The Icon of sync appear as normal and the clicking on it will open the related page.


**Secondly** for **navigation bar** I recommend this one, appropriate for all devices, collect all option/ navigation buttons in one place, simple, clear,  easy and familiar for most users and in technical aspect less pages(activities) so les resource of app usage 

<img width="172" alt="Screen Shot 1444-03-26 at 12 07 30 AM" src="https://user-images.githubusercontent.com/66481905/197288878-63d4b29e-e697-43c3-be95-afd54c3e8cf8.png">

https://user-images.githubusercontent.com/66481905/196923102-0fecdd5f-2231-4279-892b-bdcd1d6970fe.mov





I looking forward your feedback

**Comment by Karimatu05** [comment]
Hello @maprehensive i made this iteration what do you think? i will be waiting for your feedback thank you
![third Iteration](https://user-images.githubusercontent.com/100648626/197306311-d0a5bf75-3cae-4dd3-815b-f8089c5d3f12.jpg)

**Comment by JessicaItepu** [comment]
..

**Comment by mishymia** [comment]
Hi @maprehensive this is my design as I wait for your feedback thanks.
![services 1.png](https://user-images.githubusercontent.com/105456703/197584540-4fbab4a0-d96b-4b3f-870d-e73ac576d70b.png)
![services 2.png](https://user-images.githubusercontent.com/105456703/197584570-af7f150e-6c58-4cc6-82f7-ef4d1baa25da.png)
![services 3.png](https://user-images.githubusercontent.com/105456703/197584597-4c1d7f8c-b91d-4664-9d8b-b06744626fe7.png)
I used a single icon throughout the application so as to create consistency across the screens and represented the icons in the old design which was confusing to recognise as clear descriptive labels. Doing so, users aren't confused about the function.

**Comment by realdipo** [comment]
**@maprehensive Here are my contributions to Menu Navigation UI improvement #358. I took some liberties with the assigned design guidelines for text colours and error state colours as these weren't outlined in the design guidelines.**

![Rationale 2](https://user-images.githubusercontent.com/30560611/197787631-2fecdcaf-4546-4ab5-ae83-343e613acce8.png)
![Rationale 3](https://user-images.githubusercontent.com/30560611/197787635-8c6f8490-e5c1-4832-9cb0-f8b12320d45a.png)
![Rationale 4](https://user-images.githubusercontent.com/30560611/197787652-933ffc3e-fec5-4fc9-9372-c473c51da702.png)
































![Rationale 1](https://user-images.githubusercontent.com/30560611/197787611-eaa3a0fc-4a94-4818-9423-10f34a86f1d1.png)

**Comment by 010220010** [comment]
Hello there @maprehensive, I hope this meets you well. This is just to put forward my design ideas in a bid to fulfill the set objectives. Below is a well labelled image containing my ideas put together in a chart.
![Authentication from the sync screen (1)](https://user-images.githubusercontent.com/105234341/199123347-1010d5fd-5655-4ad6-ac19-5bbc273f2a57.png)

**Comment by Erieola** [comment]
Hi @maprehensive 
![Erie](https://user-images.githubusercontent.com/81233753/199708920-41429d86-2446-4a56-8fff-03d82e61994b.jpg)

Kindly find the links to my submission below, Feedback will be appreciated.

Figma: https://www.figma.com/file/unVUG3yR0McIsDeeqPrtrO/Erie?node-id=43%3A7373
Prototype: https://www.figma.com/proto/unVUG3yR0McIsDeeqPrtrO/Erie?page-id=43%3A7373&node-id=44%3A7411&viewport=-104%2C62%2C0.2&scaling=scale-down&starting-point-node-id=44%3A7411

**Comment by cvemann** [comment]
Here's a Redesign for the Menu UI Navigation for Services @Redeem-Grimm-Satoshi;
The most important action 'syncing' is left at the Top bar, while the rest is collapsed into the overflow menu (the 3-dot). 

![Image](https://user-images.githubusercontent.com/80982139/211424006-9c1735a0-f01f-4e3e-a52a-aff11ba2dc6d.png)

### Guidance
- The Title font is 22px and fills the container.
- The height of the navigation menu is 64px.
- All the icons are 24px and the padding between them is also 24px.
- The margin on both ends is 16px.

This component would be tailored for the other tools to keep top app bars consistent in look, feel and experience.

**Comment by maprehensive** [comment]
@Cveman1 the Services redesign in the Outreachy 2022 branch includes a hamburger menu on the left with a list of links:

Let's discuss how your changes will build on that navigation in the meeting tomorrow. 

![Image](https://user-images.githubusercontent.com/1215441/211583009-a1b5e933-b298-4eda-aaa9-48406f549457.png)
