### ISSUE TITLE
Redesign the ODK-X Survey app icon

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#362]
The current Survey app icon is not branded ODK-X, and do not clearly communicate the core app function.

![Screenshot_Survey01](https://user-images.githubusercontent.com/1215441/193406186-7847d81d-d74b-47be-ae1d-77b042eb5bce.png)

This task is to redesign the app icon to be:

- Recognisable as applications in the ODK-X suite of tools
- Ideally incorporating the ODK-X logo (note this issue for Logo refresh https://github.com/odk-x/tool-suite-X/issues/355)
- can be distinguished as the Survey app without accompanying text
- Preferably does not rely on the app name in the icon

App icons should be created as SVG format and be clear and legible at small sizes, such as 20x20px

### You do not need to be assigned to this issue to work on it for an Outreachy application

**Comment by Karimatu05** [comment]
Hi, am Outreachy applicant. I would love to work on this please @maprehensive

**Comment by Redeem-Grimm-Satoshi** [comment]
@maprehensive sent a PR for the first issue, Can I draft out different versions of this ODK-X Survey App Icon?

**Comment by maprehensive** [comment]
> @maprehensive sent a PR for the first issue, Can I draft out different versions of this ODK-X Survey App Icon?

Yes, that's a good way to approach this task. We will then provide feedback on the designs and you can iterate again.

**Comment by maprehensive** [comment]
> Hi, am Outreachy applicant. I would love to work on this please @maprehensive

Sure thing @Karimatu05 , I will assign you.

**Comment by jessjaey** [comment]
@maprehensive  can I be assigned this

**Comment by Thimmo** [comment]
Hello @maprehensive Can I also be assigned to join @Karimatu05 in fixing this issue

**Comment by Karimatu05** [comment]
> > Hi, am Outreachy applicant. I would love to work on this please @maprehensive
> 
> Sure thing @Karimatu05 , I will assign you.

Thanks but am a UI\UX designer so would i also send a pull request or i can attach my contribution to the issues am assigned ? @maprehensive

**Comment by Karimatu05** [comment]
@maprehensive can u send us where we can get the complete design so that we can make the icons changes

**Comment by jessjaey** [comment]
@maprehensive 
Please review my design on the Survey app icon ![image](https://user-images.githubusercontent.com/105664383/195189737-2874c184-bdc5-465f-83a5-c72774feae89.png) icon

**Comment by Karimatu05** [comment]
@maprehensive this is what i came up with. Your feedbacks are welcome thank you.
![ideas](https://user-images.githubusercontent.com/100648626/195680697-35ff08a4-06aa-4968-89b0-5a0a0b5b77a1.jpg)

**Comment by Karimatu05** [comment]
![ideas](https://user-images.githubusercontent.com/100648626/195316096-e8000691-88df-46a2-8267-e9b19100ae30.png)

**Comment by Augusta2** [comment]
Hello @maprehensive  I would love to work on this

**Comment by jessjaey** [comment]
I put your feedback into consideration for my iterations of the app icons![image](https://user-images.githubusercontent.com/105664383/195708660-720f91eb-1b6b-467d-a751-63707b2215cd.png)

**Comment by cvemann** [comment]
> I put your feedback into consideration for my iterations of the app icons![image](https://user-images.githubusercontent.com/105664383/195708660-720f91eb-1b6b-467d-a751-63707b2215cd.png)

I love your new iterations, a bit sleek

**Comment by jessjaey** [comment]
> > I put your feedback into consideration for my iterations of the app icons![image](https://user-images.githubusercontent.com/105664383/195708660-720f91eb-1b6b-467d-a751-63707b2215cd.png)
> 
> 
> 
> I love your new iterations, a bit sleek

Thankyou for your feedback ✨

**Comment by Grace-io** [comment]
Hi @maprehensive . this was what i came up with
![{FE621048-1292-4EED-8FD0-0E63DAAB134E}](https://user-images.githubusercontent.com/115491097/195826697-bc62962f-40f1-476c-807c-285e12319085.png)
![{DA03963F-7079-49D7-A962-B46ED7356031}](https://user-images.githubusercontent.com/115491097/195826721-18aca36f-074d-44ca-b68c-bee0ad3b3353.png)
![{715AB2E3-756D-4F9C-974F-3693F6E676B6}](https://user-images.githubusercontent.com/115491097/195826843-74a339ef-6729-4ce4-9d88-e3facb3a4794.png)
![{EEE3B00D-AB52-47BA-8525-B0B29A8E71F0}](https://user-images.githubusercontent.com/115491097/195826875-37f2ee88-cf40-460e-86f7-59c6574a28e4.png)
![{BE53FAC7-E742-4AD0-9068-19681F17D14C}](https://user-images.githubusercontent.com/115491097/195826905-a8cf22fc-463a-4688-8a31-a47a4b73763c.png)
![{275F112F-A8D7-4B9D-AD10-87B7E93CEF13}](https://user-images.githubusercontent.com/115491097/195827077-6b2c584e-7225-47b9-ba10-45389d6da32b.png)
![Android Small - 1](https://user-images.githubusercontent.com/115491097/195827144-af9e3bdf-5bf6-4ce5-9d0c-74a759914263.png)
![{2006F371-C956-4468-898D-D983966A2A06}](https://user-images.githubusercontent.com/115491097/195827178-f0a98d51-7666-400d-a89e-81beb26f738b.png)

Looking forward to your feedbacks

**Comment by Itsmiracle1130** [comment]
Kindly review this I would like to know what you think


![image](https://user-images.githubusercontent.com/115800726/195961908-4c07e305-5b7e-452c-b1ed-db0804742e48.jpeg)

![image](https://user-images.githubusercontent.com/115800726/195961915-881d893f-4561-477d-bde8-001e0af825f6.jpeg)

**Comment by Thimmo** [comment]
Hello @maprehensive,
Here is what I have come up with for the survey app icon.

![ODKX-logo](https://user-images.githubusercontent.com/105228037/196011851-e6158100-409f-4953-b247-52073ca4d090.png)

**For accessibility, I also tested the logo for distortion in different sizes.** 
![Frame 49](https://user-images.githubusercontent.com/105228037/196011872-1b3ad7ba-9c35-4254-bd22-5ca471f72358.png)

![Frame 50](https://user-images.githubusercontent.com/105228037/196011874-4ec11ce3-af14-4e0b-9af2-ac075e327842.png)

![Frame 51](https://user-images.githubusercontent.com/105228037/196011875-b1fe87f4-53b9-4b12-9c2b-49578fca5735.png)

I'd also appreciate your feedback.

**Comment by maprehensive** [comment]
@jessjaey Great work! 

Your concepts are very polished, the gradient gives it really professional look. 

I like the way the first iteration promotes the document / list icon – it focusses on the function of the app. 

A question to help with the next iteration – which icon communicates the function of the app better - the document icon, or the document with the list? 

Great work, this is really good.

**Comment by maprehensive** [comment]
@Karimatu05 Good job. 

Great to see the iterations, the use of the brand colors and seeing the icon placed in the header is really helpful - we get to see how it will work!

For your next iteration see if you can bring your ideas together into one strong icon: 
- selecting the color you think will work best
- choose between the outline or solid color treatment 
- choose between having the ODK-X logo in the icon or sitting underneath 

The ideas are strong – look forward to see how you bring it together!

**Comment by maprehensive** [comment]
@Grace-io This is a really unique idea - well done. 

The presentation and rationale is really good. The explanation of the technical design choices is a good thing to include – it shows how much thought has gone into the idea. 

And showing the icon in different treatments – mono, white background, color background – really helps show how it will work. 

In your next iteration you could try:
- using fewer colors - simplifying can really strengthen a design
- showing the icon in context - e.g. the app header with the app name next to it

Look forward to seeing where you take this.

**Comment by maprehensive** [comment]
@Itsmiracle1130 This is a very distinct and eye-catching design. 

The incorporation of parts of the logo and clipboard is well done. 

I would be interested to see:
- some of your design rationale / decisions written down
- your summary of what the final icon shape is meant to represent
- versions using fewer colors - simplifying can really strengthen a design
- showing the icon in context - e.g. the app header with the app name next to it

Well done, this is very inventive.

**Comment by maprehensive** [comment]
@Thimmo This is a nice execution, I like the way you've brought your ideas together. 

Good communication of the design rationale, and it's great to see the different sizes. 

I would be interested to see:

- an iteration on the sizes of the elements in the icon - the checkboxes, list lines, ODK-X logo - the balance doesn't feel quite right
- Could the tick be incorporated into a check box? that may still communicate the idea, but simplify the overall execution 
- versions using fewer colors - simplifying can really strengthen a design
- showing the icon in context - e.g. the app header with the app name next to it

Congratulations, this is looking very promising.

**Comment by Grace-io** [comment]
> @Grace-io This is a really unique idea - well done. 
> 
> The presentation and rationale is really good. The explanation of the technical design choices is a good thing to include – it shows how much thought has gone into the idea. 
> 
> And showing the icon in different treatments – mono, white background, color background – really helps show how it will work. 
> 
> In your next iteration you could try:
> - using fewer colors - simplifying can really strengthen a design
> - showing the icon in context - e.g. the app header with the app name next to it
> 
> Look forward to seeing where you take this. 

Thank you for the feedback @maprehensive
 I will ensure that I implement them in my next iteration.

**Comment by jessjaey** [comment]
@maprehensive Thankyou for your feedback 
I'll work on it✨

> @jessjaey Great work! 
> 
> 
> 
> Your concepts are very polished, the gradient gives it really professional look. 
> 
> 
> 
> I like the way the first iteration promotes the document / list icon – it focusses on the function of the app. 
> 
> 
> 
> A question to help with the next iteration – which icon communicates the function of the app better - the document icon, or the document with the list? 
> 
> 
> 
> Great work, this is really good. 
> 
> 
> 
> 
> 
>

**Comment by Itsmiracle1130** [comment]
> @Itsmiracle1130 This is a very distinct and eye-catching design. 
> 
> 
> 
> The incorporation of parts of the logo and clipboard is well done. 
> 
> 
> 
> I would be interested to see:
> 
> - some of your design rationale / decisions written down
> 
> - your summary of what the final icon shape is meant to represent
> 
> - versions using fewer colors - simplifying can really strengthen a design
> 
> - showing the icon in context - e.g. the app header with the app name next to it
> 
> 
> 
> Well done, this is very inventive. 
> 
> 

Thanks for your feedback @maprehensive ,all observations are duly noted and will be effected as requested in my iteration

**Comment by JessicaItepu** [comment]
.

**Comment by jessjaey** [comment]
@maprehensive 
Please review my design,I put your feedback into consideration for my iterations of the app icons![image](https://user-images.githubusercontent.com/105664383/196325518-dcf026c8-709c-48e7-8c36-f529177d4a3f.png)![image](https://user-images.githubusercontent.com/105664383/196325537-a8bce20e-d25d-4e46-8dbb-e304506df3f6.png)

**Comment by maprehensive** [comment]
@jessjaey This is really nice. 

I like the way you've simplified and provided a rationale for your preferred design. 

My only minor feedback is the same as for Services icon:

> I think the ODK-X logo is still a little hard to see (my eyesight is quite bad 🤓). One suggestion is to slightly increase the whitespace around the logo – that can help bring clarity at small sizes.

Thanks!

**Comment by Karimatu05** [comment]
> @Karimatu05 Good job.
> 
> Great to see the iterations, the use of the brand colors and seeing the icon placed in the header is really helpful - we get to see how it will work!
> 
> For your next iteration see if you can bring your ideas together into one strong icon:
> 
> * selecting the color you think will work best
> * choose between the outline or solid color treatment
> * choose between having the ODK-X logo in the icon or sitting underneath
> 
> The ideas are strong – look forward to see how you bring it together!

@maprehensive  what do you think on this?
![ideas 2](https://user-images.githubusercontent.com/100648626/196469626-5cdac698-f683-428c-ad65-43b1609813a1.jpg)

**Comment by Grace-io** [comment]
Hi @maprehensive, here is what I was able to come up with after iteration based on your feedback. I'll appreciate more feedbacks as it will help me improve my design. 
![Odk-x survey logo icon iter](https://user-images.githubusercontent.com/115491097/196558425-eef53030-9cdc-4357-a5af-f1fb4a64716a.png)

**Comment by Thimmo** [comment]
> 

@maprehensive Thank you for your feedback. I reiterated on the design based on your feedback. I was able to come up with these changes.

- **I incorporated the circle tick into the checkbox**
- **I also simplified the use of colors to strengthen the design**
- **Lastly, I balanced up the size of the elements in the design from the checkboxes to the list lines and the ODKX logo**

![completed survey](https://user-images.githubusercontent.com/105228037/196588026-a8a50614-85f0-4b77-b6e9-d8423eefb6b9.png)

I also tried out the iterations in different sizes.
![24px ODKX logo3](https://user-images.githubusercontent.com/105228037/196589993-98aa107c-01f2-4143-bf00-d30127c161d6.png)
![36px ODKX Logo2](https://user-images.githubusercontent.com/105228037/196589996-9cb4b5d7-16fc-44a9-aa7a-606cb4d58155.png)
![48px ODKX Logo1](https://user-images.githubusercontent.com/105228037/196589999-18ccb1d6-cc2c-4c96-9164-f20eaabb4a3c.png)

**Comment by JessicaItepu** [comment]
![odk survey 1](https://user-images.githubusercontent.com/115474999/196799925-35809183-5854-41a9-98ff-42408b53ee5a.png)
![odx survey](https://user-images.githubusercontent.com/115474999/196799976-45268ddf-a398-4185-a3fe-00c3bbdebff6.png)

@maprehensive could you check out this design? I tried to put in all your previous suggestions and corrections and i hope this is to your liking. I would like to get your feedback.

**Comment by Augusta2** [comment]
Hello @maprehensive 
This is my design for the ODK-X survey icon. I will love to hear what you think about them.

![Survey icon thought process](https://user-images.githubusercontent.com/115414092/197067616-aaeb9471-a848-4a43-b05f-c5d6e79a5b05.png)
![SUrvey Icon thought process2](https://user-images.githubusercontent.com/115414092/197067650-f19ef0d1-0020-45e7-8c40-31052f7f1b50.png)
![SUrvey iconTP3](https://user-images.githubusercontent.com/115414092/197067788-cad90a41-e89e-49aa-8cd0-356c1ef1cb1a.png)
![Survey icon variation](https://user-images.githubusercontent.com/115414092/197067786-838c58ff-b626-49bc-a149-32a66c264fc9.png)
![Survey icon- Black background](https://user-images.githubusercontent.com/115414092/197067787-b13365e3-caee-4470-9a34-189d3cd08607.png)
![Screenshot 2022-10-20 223802](https://user-images.githubusercontent.com/115414092/197067906-ada2e496-a9b3-40c6-8929-b6f1c2f3e995.png)
![Survey Icon](https://user-images.githubusercontent.com/115414092/197067943-d8ecf006-29af-4ba6-9e7e-682ed2533aee.png)

Here is the link to the document of my [Project proposal](https://1drv.ms/p/s!Alp6WckMB-v5gRXQUGBDOtcf6FgQ)

**Comment by BlueSkiez-dev** [comment]
Hi @maprehensive  @wbrunette 
Here is my submission for the survey icon redesign.

I'd love to know your thoughts on this.

<img width="663" alt="Frame 75 (1)" src="https://user-images.githubusercontent.com/67054844/197099597-c046f1e7-5c6b-4e64-b1ec-4f436f43ea38.png">

**Comment by cvemann** [comment]
This is super cool, clean and simple 

> Hi @maprehensive @wbrunette Here is my submission for the survey icon redesign.
> 
> I'd love to know your thoughts on this.
> 
> <img alt="Frame 75 (1)" width="663" src="https://user-images.githubusercontent.com/67054844/197099597-c046f1e7-5c6b-4e64-b1ec-4f436f43ea38.png">

**Comment by BlueSkiez-dev** [comment]
> This is super cool, clean and simple
> 
> > Hi @maprehensive @wbrunette Here is my submission for the survey icon redesign.
> > I'd love to know your thoughts on this.
> > <img alt="Frame 75 (1)" width="663" src="https://user-images.githubusercontent.com/67054844/197099597-c046f1e7-5c6b-4e64-b1ec-4f436f43ea38.png">

Thanks a lot 🙏 @Cveman1

**Comment by Itsmiracle1130** [comment]
Hello @maprehensive based on your feed back I was able to make a few adjustments to my previous icon and also a few more illustrations 
Please I'd like to know what you think about these...

![image](https://user-images.githubusercontent.com/115800726/197325064-f14fe50c-9029-408d-9320-c88ca0ea541e.jpeg)

![image](https://user-images.githubusercontent.com/115800726/197325108-673dcf9a-aaac-41e8-b2e5-c4f3938781a8.jpeg)

![image](https://user-images.githubusercontent.com/115800726/197325118-b8d5fc15-ab0d-4430-9bde-9160deefa268.jpeg)

![image](https://user-images.githubusercontent.com/115800726/197325140-6aee7ab3-9c7e-4199-9255-3a9665123d57.jpeg)

Thanks

**Comment by maprehensive** [comment]
@Karimatu05 This is great. Clean and simple, and I like the consistency you've got across your different app icons. 

The icon is a little big in the mockups compared to the navigation icons - it's approx twice the height now. You could try bringing the size down to see if it still works well in the app header. 

Nice work, this is looking really good.

**Comment by maprehensive** [comment]
@Grace-io Very nice! This is looking good. 

Further feedback:
- the solid line makes the icon stronger versus the outline stroke you used in the local screen mockup
- the list lines are getting a bit squashed and lost at small sizes, it would be good to see if you can make these more prominent by spacing, reducing from 3 to 2, using less colors or some other way!

Great iteration, thanks!

**Comment by maprehensive** [comment]
@Thimmo I think this works well. It's very clear, particularly at the larger sizes. 

Thank you!

**Comment by maprehensive** [comment]
@Thimmo I think this works well. It's very clear, particularly at the larger sizes. 

Thank you!

**Comment by maprehensive** [comment]
@JessicaItepu This is looking really good - strong in the light and dark mode. 

The overall icon size is too big in the mockups. You could check out standard dimensions in the top app bar and try resizing yours: https://m3.material.io/components/top-app-bar/overview

Thanks!

**Comment by maprehensive** [comment]
@Augusta2 This is good. The write-up of your thought process is clear and helpful, the decisions you have made make sense. 

Feedback:
- simplify: focus on the idea that you think is the strongest and make it prominent so that it is unmissable, even at small sizes
- the ODK-X logo looks altered - you should use the existing logo. 
- keep working on the overall size - it will need to be even smaller for the top app bar and the status bar

Great start, thank you!

**Comment by maprehensive** [comment]
@BlueSkiez-dev This is a good start, well done. 

My comments re. the use of logo and the choice of color from the Services app apply here as well. 

Feedback: the check/tick mark is a bit lost in the mockups - it looks like it's competing for prominence with the background color or the circle color. 

I would try to make the tick stand out very clearly at smaller sizes. 

Great work, thank you.

**Comment by maprehensive** [comment]
@Itsmiracle1130 Great iteration with a very clear explanation of the thought process. 

The use of the X is clever, but it is not standing out, especially smaller sizes. You could explore how to make this more prominent by reducing the lines, changing color, size or something else!

Good to see the color variations – which color do you think works best, and why?

Thank you!

**Comment by JessicaItepu** [comment]
> @JessicaItepu This is looking really good - strong in the light and dark mode.
> 
> The overall icon size is too big in the mockups. You could check out standard dimensions in the top app bar and try resizing yours: https://m3.material.io/components/top-app-bar/overview
> 
> Thanks!

Thank you @maprehensive for the feedback. I have tried reducing the size.

![odx survey-1](https://user-images.githubusercontent.com/115474999/197377372-8ac98aea-c27c-4370-89f4-6e60bb99c76e.png)
![IMG-20221023-WA0002](https://user-images.githubusercontent.com/115474999/197377386-f750014e-4d75-4afe-9dc2-cd5499ee8a7e.jpg)

**Comment by jessjaey** [comment]
@maprehensive I did a few variations to work on your feedback.please review 
![image](https://user-images.githubusercontent.com/105664383/197398281-59b7fb4c-7545-42f7-aa47-0ebb9553699d.png)![image](https://user-images.githubusercontent.com/105664383/197398287-105afcc5-17b2-4f79-be27-103eb2935b1d.jpeg)![image](https://user-images.githubusercontent.com/105664383/197398288-bf0cb7a3-839e-49b6-918d-c7d98d5d33ce.jpeg)![image](https://user-images.githubusercontent.com/105664383/197398291-c58510bb-674d-414b-9afd-9f0e3535e9e5.jpeg)
![image](https://user-images.githubusercontent.com/105664383/197398363-6e2b88b8-6fef-4400-9777-b66a99729c98.jpeg)

**Comment by Grace-io** [comment]
> @Grace-io Very nice! This is looking good. 
> 
> Further feedback:
> - the solid line makes the icon stronger versus the outline stroke you used in the local screen mockup
> - the list lines are getting a bit squashed and lost at small sizes, it would be good to see if you can make these more prominent by spacing, reducing from 3 to 2, using less colors or some other way!
> 
> Great iteration, thanks!

Thank you 😊
I will definitely put these into consideration in my next iteration. Thank you for your feedback

**Comment by Augusta2** [comment]
Thanks @maprehensive 

Based on your feedback;
- I reduced  the size to accommodate the status bar and top bar
- I removed one of the features from my previous design and made the checkbox more visible.

In Addition; I made the colours deeper to make it look more mature and stand out.

![odk survey icon ](https://user-images.githubusercontent.com/115414092/197510053-3fff3e4f-cdfe-4a0e-8342-a240978247e8.png)
![0dk survey icon](https://user-images.githubusercontent.com/115414092/197510082-45fed3f4-0b3f-4eef-9689-d533f36b81e0.png)
![ODKX survey icon](https://user-images.githubusercontent.com/115414092/197510119-13ff8d35-17ea-4e2d-874d-24ba08dc9ed0.png)

**Comment by JessicaItepu** [comment]
Hi @Augusta2, you posted this under the wrong issue

**Comment by Augusta2** [comment]
Hello @maprehensive 
I appreciate your feedback. I made some adjustments.
I reduced the size of the icon.

![survey icon feedback ](https://user-images.githubusercontent.com/115414092/197522942-8d9f090d-920b-4f33-b04d-c25a8a4087ac.png)
![odkx survey icon4](https://user-images.githubusercontent.com/115414092/197522944-7e1877d8-42d3-4313-9934-09baf417df0c.png)
![odkx survey icon 3](https://user-images.githubusercontent.com/115414092/197522976-78a89336-8e0f-4c90-a4f7-c0e2bae5e04e.png)
![Odkx survey icon1](https://user-images.githubusercontent.com/115414092/197523021-d93812a6-cbe0-4076-9855-816e7af5432a.png)

[Link to document](https://1drv.ms/p/s!Alp6WckMB-v5gRniPzgXguxv7i94)

**Comment by BlueSkiez-dev** [comment]
Hi @maprehensive, good day!
An iteration to the logo based on the feedback you gave;

<img width="663" alt="Frame 76" src="https://user-images.githubusercontent.com/67054844/197745307-13e99c0a-408a-4019-a31a-7a942179ecb9.png">

**Comment by Karimatu05** [comment]
> @Karimatu05 This is great. Clean and simple, and I like the consistency you've got across your different app icons.
> 
> The icon is a little big in the mockups compared to the navigation icons - it's approx twice the height now. You could try bringing the size down to see if it still works well in the app header.
> 
> Nice work, this is looking really good.

okay sir, i would make some changes now. thank you

**Comment by Itsmiracle1130** [comment]
@maprehensive thanks for the feedback
I'll begin work immediately

**Comment by Karimatu05** [comment]
> > @Karimatu05 This is great. Clean and simple, and I like the consistency you've got across your different app icons.
> > The icon is a little big in the mockups compared to the navigation icons - it's approx twice the height now. You could try bringing the size down to see if it still works well in the app header.
> > Nice work, this is looking really good.
> 
> okay sir, i would make some changes now. thank you

@maprehensive here is the correction what do you think about it please your feedbacks are welcome and please the project timeline are we explaining our design brief more, that's our contribution or we are doing something different?
![ideas 2](https://user-images.githubusercontent.com/100648626/197903888-719bee57-fcb9-4f41-8ae7-3bd869b55060.jpg)

**Comment by Grace-io** [comment]
@maprehensive Thank you for your feedbacks. In this iteration, I reviewed the spacing of the list and changed the strokes to solid lines.
![newww odk](https://user-images.githubusercontent.com/115491097/198577159-12bf648b-7020-4f01-b7a9-1b3c9e1684b5.png)

**Comment by Itsmiracle1130** [comment]
> @Itsmiracle1130 Great iteration with a very clear explanation of the thought process. 
> 
> 
> 
> The use of the X is clever, but it is not standing out, especially smaller sizes. You could explore how to make this more prominent by reducing the lines, changing color, size or something else!
> 
> 
> 
> Good to see the color variations – which color do you think works best, and why?
> 
> 
> 
> Thank you!


@maprehensive I tried to work around the x like you said and I came up with this, I'll really like to know what you think about it

.![image](https://user-images.githubusercontent.com/115800726/198715690-10b23cb6-91de-4822-a56a-2a6d2bb7458e.jpeg)

![image](https://user-images.githubusercontent.com/115800726/198715875-27e03b7c-fce6-4026-946e-c25cfc74b7fe.jpeg)

![image](https://user-images.githubusercontent.com/115800726/198715910-6ac9d31f-2e63-4203-9065-3bb61a8a9998.jpeg)

**Comment by AnishaSingh0118** [comment]
Hello @maprehensive I have came up with these ideas in non copyrighted manner.
Kindly provide feedback.


**Design 1 :**
![odk-x 2 1-01](https://user-images.githubusercontent.com/76876709/197791023-3b8512fd-7665-4f2a-886b-c25db1f7136d.png)


**Design 2 :**
![odk-x 2 1-02](https://user-images.githubusercontent.com/76876709/197791031-3f90a1b9-63eb-4b7f-b33e-b93e0695e639.png)

**Design 3 :**
![odk-x 2 1-03](https://user-images.githubusercontent.com/76876709/197791032-3c2ae830-8512-427c-a96d-f75d58337f44.png)

**Design 4 :**
![odk-x 2 1-04](https://user-images.githubusercontent.com/76876709/197791035-34e495de-76b5-4228-83b8-5b17228d8ef3.png)

**Comment by 010220010** [comment]
Hello @maprehensive, this is to present my little bit on the survey logo redesign I'll be waiting on your review , thank you.

![As for the redesign of the survey logo  This is a logo which comprises of just two elements which are a pencil and a survey form for simplicity sake and so that the entire concept could still be very much prominent a](https://user-images.githubusercontent.com/105234341/199279131-a1418485-debc-45b5-9d3e-f2d5f21b3ed1.png)

**Comment by Redeem-Grimm-Satoshi** [comment]
![Survey Icon](https://user-images.githubusercontent.com/45304978/199959203-c87c1485-b181-4cb1-9ab6-39de8b0acb89.jpg)
--------------------------
@maprehensive Feedback Appreciated.

**Comment by Techxie-bc** [comment]
Can I work on this issue?

**Comment by maprehensive** [comment]
> Can I work on this issue?

@Techxie-bc Yes, go ahead 😀

**Comment by hamna456** [comment]
Hey @maprehensive, I'm eager to contribute! Could you assign me to this task, please? It's something I'd really enjoy working on.

**Comment by maprehensive** [comment]
> Hey @maprehensive, I'm eager to contribute! Could you assign me to this task, please? It's something I'd really enjoy working on.

Yes please go ahead

**Comment by hamna456** [comment]
@maprehensive, I have devised these designs for your consideration. Should you wish for any alterations or adjustments, I am completely open to your suggestions. Your feedback is invaluable to me.😊


![Image](https://github.com/odk-x/tool-suite-X/assets/76582769/d37a9c1a-a074-4dfc-8dcb-0768e94549dc)

**Comment by siva224513** [comment]
i would like to working on this issue

**Comment by Arnav2824** [comment]
Hey @maprehensive, I have designed the following logos, taking inspiration from the earlier suggested designs. I would really appreciate it if you could review them and give me your feedback.
![ODK-X Survey logo First iteration](https://github.com/odk-x/tool-suite-X/assets/126960489/9fb3ff0a-a729-46ce-91c8-e157a7f6f046)

**Comment by maprehensive** [comment]
> @maprehensive, I have devised these designs for your consideration. Should you wish for any alterations or adjustments, I am completely open to your suggestions. Your feedback is invaluable to me.😊
> 
> 
> ![Image](https://github.com/odk-x/tool-suite-X/assets/76582769/d37a9c1a-a074-4dfc-8dcb-0768e94549dc)
> 
> 
> 
> 
> 

Lots of good ideas in these designs! 

Things to think about:
- Will the design work well at small scale? 
- Do you need the app name incorporated into the logo? 
- Which is your preferred design and why?

**Comment by maprehensive** [comment]
> Hey @maprehensive, I have designed the following logos, taking inspiration from the earlier suggested designs. I would really appreciate it if you could review them and give me your feedback.
> 
> ![ODK-X Survey logo First iteration](https://github.com/odk-x/tool-suite-X/assets/126960489/9fb3ff0a-a729-46ce-91c8-e157a7f6f046)
> 
> 
> 
> 

This is a good start. Simple and clean.  


Things to think about:
- Will the design work well at small scale? The lines are quite fine and detailed. 
- Do you need the app name incorporated into the logo? 
- Which is your preferred design and why?

**Comment by hamna456** [comment]
@maprehensive, I have devised the design for your consideration taking into consideration your previous feedback. Should you wish for any alterations or adjustments, I am completely open to your suggestions. Your feedback is invaluable to me.😊
### Previous Design

![Previous Design](https://github.com/odk-x/tool-suite-X/assets/76582769/62a21679-22ef-4389-9f4d-76f0cf6fa2ce)

### Incorporating App Name into Logo 

While it's crucial to maintain visibility even at smaller scales, I personally believe that since the application name is already present within the app itself, there might be less necessity to include it in the logo. It seems that the icon alone effectively communicates the identity of the app.

### Preferred Design: Enhanced Clarity and Color Scheme

Among the designs, Design 3 stands out to me due to its clarity and adherence to the ODK-X theme colors. I've further refined this design to enhance the visibility of the logo. Utilizing similar and lighter shades from the ODK-X logo's color palette, I've adjusted the design for better visual appeal. Additionally, I've introduced a subtle blue shade in the background to accentuate the logo further.

### Modified Design

Below is a visualization of modified icon :

![Modified Design](https://github.com/odk-x/tool-suite-X/assets/76582769/4b04f473-69e8-4fd4-ad54-ee1b6be98dfd)


### Modified Design Small Scale Visualization
 
Below is a visualization of how the icon would appear on a mobile device:

![Icon on Device](https://github.com/odk-x/tool-suite-X/assets/76582769/ee3cd1e2-5e51-44ca-abde-c303a501a791)

**Comment by Arnav2824** [comment]
Hey @maprehensive , after your feedback I reconsidered my designs and also modified them a bit.

### **Earlier Designs**

![ODK-X Survey logo First iteration](https://github.com/odk-x/tool-suite-X/assets/126960489/35787b9c-7ba5-4264-bc64-16c8176f5efe)

### Integrating Application Logo
I considered integrating application name in the icon but that would just make the icon too cluttered. That's why I think it would be better to just let the designs and then maybe the splash screen can have the name of the application, that should be enough for the users to recognize the app. 

### My preferred design 
To be honest I preferred the second variation more because of its simplicity and cleanliness. I have tried to modify that design a bit in an effort to make it even better ,

**Comment by Arnav2824** [comment]
Hey @maprehensive , after your feedback I reconsidered my designs and also modified them a bit.

### **Earlier Designs**

![ODK-X Survey logo First iteration](https://github.com/odk-x/tool-suite-X/assets/126960489/35787b9c-7ba5-4264-bc64-16c8176f5efe)

### Integrating Application Logo
I considered integrating application name in the icon but that would just make the icon too cluttered. That's why I think it would be better to just let the designs and then maybe the splash screen can have the name of the application, that should be enough for the users to recognize the app. 

### My preferred design 
To be honest I preferred the second variation more because of its simplicity and cleanliness. I have tried to modify that design a bit in an effort to make it even better , 

### New Designs
![ODK-X Survey Logo second iteration](https://github.com/odk-x/tool-suite-X/assets/126960489/8a6c55be-d147-469a-ac16-828c1224b272)

I also tested them using certain mock-ups. 

### Mock-ups

![iPhone Screen (3)](https://github.com/odk-x/tool-suite-X/assets/126960489/753630ce-6017-492c-b2a2-444acfaa63de)

![iPhone Screen (2)](https://github.com/odk-x/tool-suite-X/assets/126960489/29294095-bda5-4fb3-af20-80445011f3ad)

I would really appreciate it if you could go through them and provide me with your valuable feedback.

**Comment by maprehensive** [comment]
@hamna456 Nice work. 

The rationalisation for the preferred logo is good, and you've made good improvements. It's looking good.

**Comment by maprehensive** [comment]
@Arnav2824 Good improvements! 

The updates give the logo a stronger presence and improved clarity. 

Do you have the latest ODK-X mark in there? It looks like the old version with lighter strokes. 

And a minor note - since ODK-X is an Android only app it's better to use Android for mockups, not iOS.

**Comment by hamna456** [comment]
> [@hamna456](https://github.com/hamna456) Nice work.
> 
> The rationalisation for the preferred logo is good, and you've made good improvements. It's looking good.

@maprehensive I apologize for the delay in responding; I was preoccupied with exams. Thank you for your valuable feedback.😊
