### ISSUE TITLE
ODK-X Tables - implement dark and light themes

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#367]
This issue is to enable and configure dark and light themes for ODK-X Tables

> Dark theme is available in Android 10 (API level 29) and higher. It has many benefits:
> 
> - Can reduce power usage by a significant amount (depending on the device’s screen technology).
> - Improves visibility for users with low vision and those who are sensitive to bright light.
> - Makes it easier for anyone to use a device in a low-light environment.

https://developer.android.com/develop/ui/views/theming/darktheme

## Design Guidelines:
Colors for a dark theme have been specified in the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

## Outreachy
This issue can be used for an Outreachy application for the project [Custom UI components for ODK-X mobile apps](https://www.outreachy.org/apply/project-selection/#odk-x)
**This issue is for the Technical stream of the project.**

Please request to be assigned to the issue so we can track the number of peopling doing this exercise. Multiple people can work on this issue simultaneously.

**Comment by wbrunette** [comment]
@maprehensive can you be more specific what you are looking for here? The only UI in tables is the top bar and the menus associated, the rest of the UI is created by users as custom web pages.

**Comment by cvemann** [comment]
I'd love to work on this too @maprehensive

**Comment by EvelyneMwende** [comment]
Hi @maprehensive. Can i work on this issue?

**Comment by JessicaItepu** [comment]
I would like to put my skills to the test through this project too. Kindly grant me access

**Comment by damiadejoro** [comment]
I am interested in working on this issue.

**Comment by Amarachhhiii** [comment]
I am interested to work on this issue. Can you assign me to this issue?

**Comment by Praise-Ugwum** [comment]
Hi @maprehensive, can I work on this issue, please?

**Comment by IjeomaGeorge** [comment]
@maprehensive I'll love to work on the themes issue

**Comment by JessicaItepu** [comment]
![odk tables light and dark](https://user-images.githubusercontent.com/115474999/195695316-c7087ab0-0ae2-4b55-bb1c-abc691e9f09d.png)


Hello @maprehensive... This project was very close to another one i submitted so i did it too. I hope you approve and assign me to it officially. Thank you

**Comment by Joyfro** [comment]
Hello @maprehensive ,
 Please assign me to this issue, I would be excited to work on this as my second contribution.

**Comment by salmasabo** [comment]
![image](https://user-images.githubusercontent.com/115367130/197264625-ae2e6aa9-012d-4712-b9f2-aa290c13ae81.png)
@maprehensive this is light and dark theme redesign to the issue.

**Comment by JessicaItepu** [comment]
Hello @salmasabo this is a technical project not a design one.

**Comment by salmasabo** [comment]
> Hello @salmasabo this is a technical project not a design one. 

Okay,thank you
