### ISSUE TITLE
ODK-X Survey - implement dark and light themes

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#368]
This issue is to enable and configure dark and light themes for ODK-X Survey

> Dark theme is available in Android 10 (API level 29) and higher. It has many benefits:
> 
> - Can reduce power usage by a significant amount (depending on the device’s screen technology).
> - Improves visibility for users with low vision and those who are sensitive to bright light.
> - Makes it easier for anyone to use a device in a low-light environment.

https://developer.android.com/develop/ui/views/theming/darktheme

## Design Guidelines:
Colors for a dark theme have been specified in the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

**Comment by wbrunette** [comment]
The in Survey the form selection screen and the top bar and the menus associated, the rest of the UI is created by ODK-X JavaScript rendering system so it's a series of  web pages. This means the majority of the UI is being rendered in a WebKit on Android. The question UI source code is in the Application Designer source tree.

**Comment by cvemann** [comment]
I'd love to convert the light theme of the ODK-X Survey app into a dark theme for each of the benefits listed by @maprehensive

**Comment by damiadejoro** [comment]
I would like to work on this issue. Can this be assigned to me?

**Comment by Hilzygift** [comment]
Hi @maprehensive, I'd like to work on this issue; ODK-X Survey- Implement dark and light themes (converting the light theme to a dark theme and improving its experience.

**Comment by mimi-tech** [comment]
Hi @maprehensive, Hope you doing well, I am an outreachy applicant. I would like to work on this issue.

**Comment by Amarachhhiii** [comment]
Hi @maprehensive @wbrunette I'm an Outreachy applicant, I would love to work on this issue.

**Comment by veekamunya** [comment]
Hello @maprehensive since the automatic dark and light theme only works on android 11 and higher, android devices with a lower android version would need a manual ligh-dark theme switch within the app..I would like to create a switch design to toggle between light and dark theme following the odk-x design guidelines and i would love to be asssigned this issue

**Comment by Joyfro** [comment]
Hello @maprehensive , Please I would like to be assigned to this issue
