### ISSUE TITLE
ODK-X Services - implement dark and light themes

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/tool-suite-X#369]
This issue is to enable and configure dark and light themes for ODK-X Services

> Dark theme is available in Android 10 (API level 29) and higher. It has many benefits:
> 
> - Can reduce power usage by a significant amount (depending on the device’s screen technology).
> - Improves visibility for users with low vision and those who are sensitive to bright light.
> - Makes it easier for anyone to use a device in a low-light environment.

https://developer.android.com/develop/ui/views/theming/darktheme

## Design Guidelines:
Colors for a dark theme have been specified in the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

**Comment by BlueSkiez-dev** [comment]
Hi @maprehensive I'd like to work on this issue

**Comment by cvemann** [comment]
Hello @maprehensive
This sounds interesting, and also for accessibility issues. Can I design the dark theme while @BlueSkiez-dev implements it?

**Comment by Thimmo** [comment]
Hello @maprehensive 
I would also love to work with @Cveman1 in designing the dark and light themes interface while @BlueSkiez-dev implements it.

**Comment by cvemann** [comment]
Awesome @Thimmo

**Comment by ghost** [comment]
Hello @maprehensive. My name is Emenyi Nelly and I am an Outreachy intern for this season.Please can I be assigned this issue?

**Comment by ghost** [comment]
Hello @maprehensive this is really awesome. Please can i would love to work on this isssue.

**Comment by maprehensive** [comment]
@BlueSkiez-dev @Cveman1 @Thimmo @Emenyi95 – thanks for the responses. This issue needs review with the PMC and it's not meant for Outreachy applications.

**Comment by cvemann** [comment]
Alright then. How do we identify issues that are meant for Outreachy though?

**Comment by maprehensive** [comment]
this has been subsumed into #404
