### ISSUE TITLE
ODK-X Services- Need for distinguishable settings icons

### ISSUE THREAD

**Issue by Grace-io** [opendatakit/tool-suite-X#378]
In the ODK-X services settings the **device specific settings** and **table specific settings** have no distinguishable icons as they have the same icons which might make users of this application (who are trying to complete an action quickly) mistake one setting for the other.
![Screenshot_20221012-194857](https://user-images.githubusercontent.com/115491097/195432210-0a301288-f1c3-4e8e-811d-ca0aecaf3397.jpg)   

## Design Guidelines:
Colours, icons and other user interface elements used should conform to the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

## Outreachy
This issue can be used for an Outreachy application for the project [Custom UI components for ODK-X mobile apps](https://www.outreachy.org/apply/project-selection/#odk-x)
**This issue is for the User Interface Design stream of the project.**

Multiple people can work on this issue simultaneously.

### You do not need to be assigned to this issue to work on it for an Outreachy application

**Comment by Grace-io** [comment]
Hi @maprehensive @wbrunette  I'll love to work on this task

**Comment by AnishaSingh0118** [comment]
Hi @Grace-io  is that ok 
![tables setting](https://user-images.githubusercontent.com/76876709/195777708-9aaf3045-cf9e-43c4-bb2a-01256b5539cb.jpeg)

**Comment by AnishaSingh0118** [comment]
Hello, @Grace-io I have tried to fix this issue. Kindly guide if there is anything that needs to be done from my end. Would love to hear your feedback on this particular PR!  [#249](https://github.com/odk-x/services/pull/249)

**Comment by Grace-io** [comment]
> Hello, @Grace-io I have tried to fix this issue. Kindly guide if there is anything that needs to be done from my end. Would love to hear your feedback on this particular PR!  [#249](https://github.com/odk-x/services/pull/249)

Hi @AnishaSingh0118 , I like this concept however we cannot work on this issue yet because it has not been approved. If you're an Outreachy applicant, you can contribute to any of the issues in the link below as only the contribution to any of the issues here will be considered for the Outreachy application.
https://forum.odk-x.org/t/welcome-outreachy-applicants-winter-2022/2002

**Comment by Grace-io** [comment]
> Hello, @Grace-io I have tried to fix this issue. Kindly guide if there is anything that needs to be done from my end. Would love to hear your feedback on this particular PR!  [#249](https://github.com/odk-x/services/pull/249)

Hi @AnishaSingh0118 , I like this concept however we cannot work on this issue yet because it has not been approved. If you're an Outreachy applicant, you can contribute to any of the issues in the link below as only the contribution to any of the issues here will be considered for the Outreachy application.
https://forum.odk-x.org/t/welcome-outreachy-applicants-winter-2022/2002

**Comment by AnishaSingh0118** [comment]
> > Hello, @Grace-io I have tried to fix this issue. Kindly guide if there is anything that needs to be done from my end. Would love to hear your feedback on this particular PR!  [#249](https://github.com/odk-x/services/pull/249)
> 
> Hi @AnishaSingh0118 , I like this concept however we cannot work on this issue yet because it has not been approved. If you're an Outreachy applicant, you can contribute to any of the issues in the link below as only the contribution to any of the issues here will be considered for the Outreachy application. https://forum.odk-x.org/t/welcome-outreachy-applicants-winter-2022/2002

Thank you so much for guiding me the right path for Outreachy's contributions :)

**Comment by maprehensive** [comment]
@Grace-io Thank you for raising this! It's now an Outreachy issue 🎉 (Sorry for the delay)

@AnishaSingh0118 this can be referenced in your Outreachy application. 

Remember that our icon set comes from the Material Design framework - referenced in the Style Guide :)

**Comment by AnishaSingh0118** [comment]
> @Grace-io Thank you for raising this! It's now an Outreachy issue 🎉 (Sorry for the delay)
> 
> @AnishaSingh0118 this can be referenced in your Outreachy application.
> 
> Remember that our icon set comes from the Material Design framework - referenced in the Style Guide :)

Thank you :) Happy contributer.

**Comment by cvemann** [comment]
> @Grace-io Thank you for raising this! It's now an Outreachy issue 🎉 (Sorry for the delay)
> 
> @AnishaSingh0118 this can be referenced in your Outreachy application.
> 
> Remember that our icon set comes from the Material Design framework - referenced in the Style Guide :)

Awesome. Thanks @Grace-io you win

**Comment by Thimmo** [comment]
Thank you @Grace-io for raising this issue.

@maprehensive I have been able to replace the confusing icons with more distinguishable ones. I also tested it with users, and they found no problem associating the new icons with their functions
![issue378](https://user-images.githubusercontent.com/105228037/197643208-9e6ea39b-73b6-44d8-ba35-f3e51b8f1943.png)

**Comment by AnishaSingh0118** [comment]
Hello @Grace-io, While making a PR to fix this issue I have kept in mind that it should be licenced so that we can use that icon without copyright. If creativity is concerned then I can put more efforts and can update the icon with a unique and creative manner. So, should I make a PR without copyright icon to show the creative icon format ? Or this one is perfect? Kindly guide.

**Comment by Augusta2** [comment]
@maprehensive I have solved this issue by simply scanning through icons in the material designs package.
I found an icon that I believe fits the Tables-Specific settings.

![new table settings icon](https://user-images.githubusercontent.com/115414092/197993890-a5fee1fe-d081-4781-bf01-d85608a3b796.png)

- I also changed the 'Verify User Permissions' icon to reference the issue on the Services menu navigation.

**Comment by realdipo** [comment]
Hi @maprehensive @Grace-io Here is my design iteration for this issue

Here is a shot showing my approach to the settings page and the original design. While the issue specifically states the Device specific settings and Table specific settings as the focus, I realised upon working on them that the settings page is filled with Technical jargon meaning that users would either have to guess at their function or click on each one to figure out the function(this is what I had to do to get familiar with the app). 

![New Design and Old design side by side](https://user-images.githubusercontent.com/30560611/198178196-95c221a8-f0b4-450e-87b7-418b6f1677a2.png)

I highlighted the changes I made to the settings page, such as clear copy to improve UX and help users easily navigate or scan settings list, well recognized icon set to distinguish between Device settings and Table settings, renamed settings list to clearer and easily understandable titles such as Privacy, Personalise your tables and so on.

![New design rationale](https://user-images.githubusercontent.com/30560611/198178855-38a12708-59d3-4db7-a2aa-cb68bde3afa9.png)


Looking forward to your feedback on this.

**Comment by Grace-io** [comment]
> @Grace-io Thank you for raising this! It's now an Outreachy issue 🎉 (Sorry for the delay)
> 
> @AnishaSingh0118 this can be referenced in your Outreachy application. 
> 
> Remember that our icon set comes from the Material Design framework - referenced in the Style Guide :)
> 

Thank you @maprehensive ☺️

**Comment by JessicaItepu** [comment]
...

**Comment by JessicaItepu** [comment]
![Settings icons design](https://user-images.githubusercontent.com/115474999/199113998-e80e14dc-2285-44ee-9359-62901d8d6165.png)
Hello @maprehensive, this is my submission to this project. I believe these new icons would help dispel any confusion that might have resulted from similar icon usage. These icons are built to communicate their meanings even at first glance. Thank you.

**Comment by JessicaItepu** [comment]
![dark mode](https://user-images.githubusercontent.com/115474999/200870333-20b5ad5c-95e5-41b6-bd07-800d874186dd.png)
Hello @maprehensive i have made a variation for the dark mode to see how the newly introduced icons look in a different theme.

**Comment by cvemann** [comment]
I just addressed this issue in #400

**Comment by maprehensive** [comment]
@Cveman1 OK I will close this issue as it is now a duplicate.
