### ISSUE TITLE
Redesign every Top App Bar as a UI Component to meet Material Design Guideline

### ISSUE THREAD

**Issue by cvemann** [opendatakit/tool-suite-X#397]
There's a need to improve the way information and page titles are displayed across the top of every screen in ODK-X Tools.

For instance: This should let users know that they are currently in the sync screen.

![Image](https://user-images.githubusercontent.com/80982139/210561148-e2f56c31-06d3-4566-906a-c22bb261b19b.png)

### Why this needs to be improved
1. Every screen needs a title that describes contents and actions related to that screen.
2. This would inform users of where they are during navigation

### Guidance
Follow the Material Design Guidelines [here](https://m3.material.io/components/top-app-bar/overview)

**Comment by cvemann** [comment]
Hi @Redeem-Grimm-Satoshi, here's my design solution for every Top bar for all the screens that require it:

![Image](https://user-images.githubusercontent.com/80982139/212428288-443fe298-7075-4868-90e0-a5906437900c.png)

### Guidelines
- 16px top and bottom padding only.
- 16px left/right margin.
- 16px padding between the back icon and the page title.
- 24px padding between the trailing icons at the top right.
- The page title is 22px
- No corner radius
- The background is white but can change to #F2F7FC upon scroll. This allows us to differentiate the contents of the screen and the title. 

### See it in context of use:
![Image](https://user-images.githubusercontent.com/80982139/212428533-224e994e-8e7c-425f-83f0-cb532f0ab576.png)

**Comment by wbrunette** [comment]
@Redeem-Grimm-Satoshi I would wait to implement top bar changes until they are reviewed. We had a discussion about this on the call. For example, this design does not take into account the new design. As a reminder @maprehensive was going to recreate a issue for top bars this weekend.

**Comment by Redeem-Grimm-Satoshi** [comment]
@wbrunette oh okay thought the new design was taken into consideration. Alright I'll keep this issue pending...

**Comment by cvemann** [comment]
I agree @wbrunette. I was also hoping to improve the recent design, due to repetition of actions (same as in settings) on the hamburger menu.

**Comment by maprehensive** [comment]
@Cveman1 the updated menu navigation issue is #403

Can you please close this issue, and implement these design changes via #403 

This will avoid confusion.

**Comment by cvemann** [comment]
Alright. Thank you

**Comment by cvemann** [comment]
.
