### ISSUE TITLE
Redesign the buttons used in ODK-X tools

### ISSUE THREAD

**Issue by cvemann** [opendatakit/tool-suite-X#402]
The buttons are dull, and inconsistent and do not meet up modern UI conventions.

![Image](https://user-images.githubusercontent.com/80982139/210849705-bc2564f8-4c28-440e-b4e1-a32e41dc2e87.png)

### Why this needs to be improved:
- The buttons need to show that they initiate action to be taken
- They need to feel like clickable buttons.

### Guidance
[Material Design Guidelines](https://m3.material.io/components/buttons/overview)

**Comment by cvemann** [comment]
Hi @Redeem-Grimm-Satoshi, I've designed a primary and secondary button for use across all ODK-X Tools. It follows the Material guidelines with exceptions to the label text. I retained all CAPs for the label text due to the diverse kinds of users we have. All CAPS would ensure that it communicates properly so that they can take an action. 

![Image](https://user-images.githubusercontent.com/80982139/211420428-5e7192e2-d124-498a-a5c9-8ca387b16759.png)

### Guidelines
- All corners are completely rounded.
- The filled colours are in line with the [ODK-X guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/edit#slide=id.g15bd994772e_0_3).
- The label text is 14px and all CAPs (Source Sans Pro).
- The width of the button can fill the grid of the screen.
- The height is 40px and fixed.

**Comment by Redeem-Grimm-Satoshi** [comment]
any link to the design? figma

**Comment by Redeem-Grimm-Satoshi** [comment]
@Cveman1 all corners are completely rounded? kind of sounds vague. stating the corner radius size in px will be more elaborate.

**Comment by cvemann** [comment]
Yes. They are completely rounded according to Material Design Guidelines. 100px is a good value to use.

I'll tag you to the Figma file

**Comment by Redeem-Grimm-Satoshi** [comment]
Great

**Comment by maprehensive** [comment]
@Cveman1 is this issue in test because you want feedback on the design? Normally we would use this column when the code has been implemented and there is a PR to test.

**Comment by Redeem-Grimm-Satoshi** [comment]
@maprehensive I can still do necessary changes if required ( at the backend )

**Comment by cvemann** [comment]
> @Cveman1 is this issue in the test because you want feedback on the design? Normally we would use this column when the code has been implemented and there is a PR to test.

Okay. I understand now. 

But I guess Redeem has started implementing some of the codes, I don't know if he has begun to push. @Redeem-Grimm-Satoshi?

**Comment by Redeem-Grimm-Satoshi** [comment]
@Cveman1 I'll push in no time.

**Comment by maprehensive** [comment]
Included in PR https://github.com/odk-x/services/pull/257 & https://github.com/odk-x/services/pull/242

**Comment by maprehensive** [comment]
Reviewed on outreach-2023 and buttons are successfully implemented. Ready to deploy from me. 

@Cveman1 would you like to review?

**Comment by cvemann** [comment]
Yes please. I'll have a call with @Redeem-Grimm-Satoshi on this
