### ISSUE TITLE
Fix Suitcase build to work with newer version of maven

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#407]
Fix suitcase build so it works with a newer version of Maven. See https://github.com/odk-x/suitcase/pull/79

**Comment by octonawish-akcodes** [comment]
I want to take this, I am lost how to get started with this project.

**Comment by Roseline-Bassey** [comment]
Hi @wbrunette, I'd like to work on this issue. Could you please assign the issue to me?

**Comment by nuilewis** [comment]
> I want to take this, I am lost how to get started with this project.

Hello @octonawish-akcodes, I think you can start by forking and cloning the repository. Maven requires JDK, so you might have to download and install that if you don't have it already. Then follow the steps on README.md to set up your project. Also, don't forget to add both Maven, Ant, and the JDK to your environment variables. Right now the build will work with Maven 3.8.6. I am not entirely sure if the issue is coming from Suitcase itself, I think the problem might be Maven itself because it seems to be a known issue and they are hopefully working on a fix.

**Comment by cvemann** [comment]
Hello @octonawish-akcodes and @Roseline-Bassey, you can work on this issue without being assigned!

**Comment by Roseline-Bassey** [comment]
> Hello @octonawish-akcodes and @Roseline-Bassey, you can work on this issue without being assigned!

Thank you

**Comment by NinaWendy** [comment]
In my case, I am using the Ubuntu operating system and have successfully upgraded my Maven version to 3.9.0, resulting in a successful build process. Probably a problem with windows os
![ODX](https://user-images.githubusercontent.com/98152860/224503675-9a8f6853-2559-45ec-b4bb-ede7861adeab.png)

**Comment by wbrunette** [comment]
Thanks for the information. After a few more people verify, I will probably close the issue. Please post here if you can compile Suitcase with Maven version 3.9.0.

**Comment by Roseline-Bassey** [comment]
I think the Maven 3.9.0 has a bug like someone mentioned earlier. Whenn I added Maven 3.9.0 to path, my builld failed but when I downgrade to Maven 3.8.7 i am able to build my project locally.

I was hoping to find a work around for this issue but it seems there's no official way to do to that.

**Comment by NinaWendy** [comment]
@wbrunette can the project be dockerized to see if the problem persists for those using windows os?

**Comment by wbrunette** [comment]
@NinaWendy that sounds like a good idea of a way to confirm IF and where the issue is :)

**Comment by darellwest** [comment]
This is what I got running the command with maven 3.9.0 on windows but built successfully with version 3.8.6
![Screenshot (332)](https://user-images.githubusercontent.com/43733122/225904108-af68b989-a1ff-4bc9-9a8d-3eb26a0bf467.png)

**Comment by tr-sangale** [comment]
@wbrunette succefully build the suitcase for the upgraded version of maven 3.9.0 on `windows os` and on `ubuntu` too 
there seems no error in building suitcase with maven 3.9.0v 


![image](https://user-images.githubusercontent.com/86203327/226106076-7e8561d0-2ab6-4640-b05d-09f373fd444a.png)

**Comment by tr-sangale** [comment]
> Thanks for the information. After a few more people verify, I will probably close the issue. Please post here if you can compile Suitcase with Maven version 3.9.0.

@wbrunette succefully compiled the suitcase for version of maven **version 3.9.0**  on `windows os` and on `ubuntu` too 
there seems no error in building suitcase with maven 3.9.0v 


![image](https://user-images.githubusercontent.com/86203327/226106799-40c472b6-285b-4383-ad8f-8adcfc764b25.png)

**Comment by tr-sangale** [comment]
@wbrunette suitcase also works fine with maven 3.9.1 , verified that too
