### ISSUE TITLE
OUTREACHY SPRING 2023 STARTER ISSUE #3 - Do this third

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#408]
GOAL: Install Docker on your computer to start becoming familiar.

MAIN TASK: Find something that needs clarification or a mistake in the ODK-X documentation: https://docs.odk-x.org/ and fix it.

To do this, you need to create a pull request for https://github.com/odk-x/docs with your documentation improvement. Please follow the **Docker** hosted build environment to test your changes on your local computer.
https://github.com/odk-x/docs#using-docker-hosted-build--environment

It is important to use the Docker method, so you gain some familiarity with Docker.

**Comment by S1Y333** [comment]
@wbrunette Hi mentor, do we need to be assigned to be recorded as the contributor? If so, can you please assign me? Thank you

**Comment by cvemann** [comment]
> @wbrunette Hi mentor, do we need to be assigned to be recorded as the contributor? If so, can you please assign me? Thank you

No @S1Y333, you don't need to be assigned. Please go ahead and work on the issue.

**Comment by S1Y333** [comment]
Share a great learning resource to get started. This tutorial covers all the Docker knowledge and the Linux command line, which is very helpful. ->https://www.youtube.com/watch?v=nqZ7JWLJimk

**Comment by Dorcas-BD** [comment]
Hello @wbrunette and  @Cveman1, I will also be working on this issue.

**Comment by Roseline-Bassey** [comment]
> Hello @wbrunette and @Cveman1, I will also be working on this issue.

Hey Dorcas, you don't need to be assigned, so please go ahead.

**Comment by nuilewis** [comment]
Hello, @wbrunette please review when available, thank you.
[https://github.com/odk-x/docs/pull/224](https://github.com/odk-x/docs/pull/224

**Comment by S1Y333** [comment]
@nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!

<img width="1089" alt="Screen Shot 2023-03-13 at 6 32 51 PM" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">

**Comment by nuilewis** [comment]
> @nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!
> 
> <img alt="Screen Shot 2023-03-13 at 6 32 51 PM" width="1089" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">

Hi @S1Y333, I did encounter an error when trying to run the command, wasn't quite sure yet what it was, I'm still trying to figure it out. Will keep you posted if I succeed

**Comment by S1Y333** [comment]
> @nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!
> 
> <img alt="Screen Shot 2023-03-13 at 6 32 51 PM" width="1089" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">

@nuilewis Problem solved. Here's the debugging process: 
1. when running ./run-task.sh odkx-autobuild , it shows the import python problem because it is using the python version on my laptop, which is 3.10, so I tried to upgrade the python version on my laptop to 3.11 but the problem continues.
2. Then I noticed in the  dockerfile, it didn't specify which python version, which can cause problem "FROM python", so I changed it to "FROM python:3.9.16-buster" specific version ( the version later than 3.9 all didn't work)
3. next, rebuild the docker image and then run  ./run-task.sh odkx-autobuild, it's working now. So it might need to fix the version problem later on.
<img width="552" alt="Screen Shot 2023-03-14 at 8 36 40 AM" src="https://user-images.githubusercontent.com/105386341/225002927-b93ffa17-6dbd-467d-90d6-6b8afab31280.png">

**Comment by wbrunette** [comment]
@S1Y333 nice work. Create an issue in the ODK-X issue queue and then make a matching pull request to fix it :)

**Comment by nuilewis** [comment]
> > @nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!
> > 
> > <img alt="Screen Shot 2023-03-13 at 6 32 51 PM" width="1089" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">
> 
> @nuilewis Problem solved. Here's the debugging process: 
> 1. when running ./run-task.sh odkx-autobuild , it shows the import python problem because it using the python version on my laptop, which is 3.10, so I tried to upgrade the python version on my laptop to 3.11 but the problem continue.
> 2. Then I noticed in the  dockerfile, it didn't specify which python version, which can cause problem "FROM python", so I changed it to "FROM python:3.9.16-buster" specific version ( the version later than 3.9 all don't work)
> 3. next, rebuild the docker image and then run  ./run-task.sh odkx-autobuild, it's working now. So it might need to fix the version problem later on.
> <img width="552" alt="Screen Shot 2023-03-14 at 8 36 40 AM" src="https://user-images.githubusercontent.com/105386341/225002927-b93ffa17-6dbd-467d-90d6-6b8afab31280.png">
> 
> 

Okay, that's nice 🎉

**Comment by Roseline-Bassey** [comment]
Hi @wbrunette , 

I've submitted a pull request here: https://github.com/odk-x/docs/pull/226
Please kindly review when available.

**Comment by Dee-Tyan** [comment]
Hi everyone, are we to edit the docker file? Because when I run the docker image, I get this message: "make: *** No targets specified and no makefile found.  Stop."

@wbrunette @Cveman1

**Comment by Roseline-Bassey** [comment]
Hi @Dee-Tyan, 
As @S1Y333 explained, it might be necessary for you to modify the Dockerfile to the specified python version.

**Comment by Dee-Tyan** [comment]
> Hi @Dee-Tyan, As @S1Y333 explained, it might be necessary for you to modify the Dockerfile to the specified python version.

Oh, I missed that. Thanks!

**Comment by nuilewis** [comment]
> > @nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!
> > <img alt="Screen Shot 2023-03-13 at 6 32 51 PM" width="1089" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">
> 
> @nuilewis Problem solved. Here's the debugging process:
> 
> 1. when running ./run-task.sh odkx-autobuild , it shows the import python problem because it is using the python version on my laptop, which is 3.10, so I tried to upgrade the python version on my laptop to 3.11 but the problem continues.
> 2. Then I noticed in the  dockerfile, it didn't specify which python version, which can cause problem "FROM python", so I changed it to "FROM python:3.9.16-buster" specific version ( the version later than 3.9 all didn't work)
> 3. next, rebuild the docker image and then run  ./run-task.sh odkx-autobuild, it's working now. So it might need to fix the version problem later on.
> 
> <img alt="Screen Shot 2023-03-14 at 8 36 40 AM" width="552" src="https://user-images.githubusercontent.com/105386341/225002927-b93ffa17-6dbd-467d-90d6-6b8afab31280.png">

Thanks @S1Y333, helped me out a lot!

**Comment by darellwest** [comment]
Hi @wbrunette Please help me review this pull request at https://github.com/odk-x/docs/pull/228

**Comment by Dee-Tyan** [comment]
Hii @wbrunette, here's my submission https://github.com/odk-x/docs/pull/230 . Thank you!
