### ISSUE TITLE
OUTREACHY SPRING 2023 STARTER ISSUE #4 - Do this fourth

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#409]
GOAL: Host a maven artifact repository using GitHub Packages.

MAIN TASK: Modify your CircleCI setup from the second starter issue, #406, to have a successfully built Android Library (compiles without error and passes tests) deployed to a Maven repository hosted by GitHub Packages. The deploy step should be handled automatically upon successful build. 

For more information about GitHub Packages, see: https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages

VERIFICATION: Once your successfully built libraries automatically deploy to GitHub Packages, please provide the link to the repository URL. It should look something like 
`https://maven.pkg.github.com/OWNER/REPOSITORY`

**Comment by Roseline-Bassey** [comment]
Hey everyone, Is anyone working on this issue and need someone to brainstorm with? I'm open to discussing or jumping on a call with y'all.

**Comment by Roseline-Bassey** [comment]
Hi @wbrunette ,

I have successfully created a package for androidlibrary which can be found at this link: https://github.com/Roseline-Bassey/androidlibrary/packages/1811966. The package build and test have been successful on Circleci. However, during deployment, there was an issue with transferring metadata to the URL(https://maven.pkg.github.com/Roseline-Bassey/androidlibrary) specified in my pom.xml file resulting in a failed deployment. I am currently working on resolving this issue, but I would appreciate any assistance you or anyone can provide.

Also, I have a question - Would it be necessary for me to create a new project and install the package dependencies to resolve this problem?
   
Error message from Circleci
```[WARNING] Could not transfer metadata org.android:androidlibrary:1.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/Roseline-Bassey/androidlibrary): status code: 401, reason phrase: Unauthorized (401)```

**Comment by wbrunette** [comment]
In response @Roseline-Bassey you do not need to worry about the meta-data at this point.

**Comment by Roseline-Bassey** [comment]
> In response @Roseline-Bassey you do not need to worry about the meta-data at this point.

Thank you for letting me know. I have included links here for your review: https://maven.pkg.github.com/Roseline-Bassey/androidlibrary.

https://maven.pkg.github.com/Roseline-Bassey/androidlibrary/org/android/androidlibrary/1.0-SNAPSHOT/maven-metadata.xml

**Comment by Roseline-Bassey** [comment]
Besides the resource shared by @wbrunette,  I also came across these two helpful resources while working on this issue. Please don't hesitate to reach out if you require any assistance.

https://www.youtube.com/watch?v=MhzoxE7NdpI
https://www.baeldung.com/maven-repo-github

Things you may need to set up:
-  GitHub personal access token 
- Maven is configured using a settings.xml file located under your Maven home directory (typically, this will be /user.home/.m2/settings.xml). 
- a POM file (pom.xml) in your `androidlibrary` directory for publishing a package

**Comment by NinaWendy** [comment]
> In response @Roseline-Bassey you do not need to worry about the meta-data at this point.

@wbrunette  Shouldn't this be a concern given that you said "The deploy step should be handled automatically upon successful build."  Locally the package is deployed successfully but when you automate the process using CircleCi the deploy step fails as a result of the metadata error ...Please clarify on this @wbrunette

**Comment by NinaWendy** [comment]
@wbrunette Please kindly review the following link: https://maven.pkg.github.com/NinaWendy/androidlibrary/org/opendatakit/androidlibrary/maven-metadata.xml. I would appreciate your feedback on whether it's okay.

**Comment by wbrunette** [comment]
@NinaWendy yes the meta data will matter for the internship. However, during the getting started contribution period, we often make adjustments to make it easier to get started. There is a difference between the getting started period and the internship. This is why I used the phrase "at this point".

**Comment by nuilewis** [comment]
> Besides the resource shared by @wbrunette, I also came across these two helpful resources while working on this issue. Please don't hesitate to reach out if you require any assistance.
> 
> https://www.youtube.com/watch?v=MhzoxE7NdpI https://www.baeldung.com/maven-repo-github
> 
> Things you may need to set up:
> 
> * GitHub personal access token
> * Maven is configured using a settings.xml file located under your Maven home directory (typically, this will be /user.home/.m2/settings.xml).
> * a POM file (pom.xml) in your `androidlibrary` directory for publishing a package

Hi @Roseline-Bassey, thanks a lot for this. Unfortunately, I haven't been able to work on this yet, just starting. I managed to set up the Github Packages on my local machine, But when I try to test it out in CircleCI my android library build is failing, again😅, even though everything works fine locally. Still trying to resolve that and see what's wrong.

**Comment by Roseline-Bassey** [comment]
> > Besides the resource shared by @wbrunette, I also came across these two helpful resources while working on this issue. Please don't hesitate to reach out if you require any assistance.
> > https://www.youtube.com/watch?v=MhzoxE7NdpI https://www.baeldung.com/maven-repo-github
> > Things you may need to set up:
> > 
> > * GitHub personal access token
> > * Maven is configured using a settings.xml file located under your Maven home directory (typically, this will be /user.home/.m2/settings.xml).
> > * a POM file (pom.xml) in your `androidlibrary` directory for publishing a package
> 
> Hi @Roseline-Bassey, thanks a lot for this. Unfortunately, I haven't been able to work on this yet, just starting. I managed to set up the Github Packages on my local machine, But when I try to test it out in CircleCI my android library build is failing, again😅, even though everything works fine locally. Still trying to resolve that and see what's wrong.

Hey, @nuilewis, could you share the error message you're getting from Circleci?

**Comment by nuilewis** [comment]
> > > Besides the resource shared by @wbrunette, I also came across these two helpful resources while working on this issue. Please don't hesitate to reach out if you require any assistance.
> > > https://www.youtube.com/watch?v=MhzoxE7NdpI https://www.baeldung.com/maven-repo-github
> > > Things you may need to set up:
> > > 
> > > * GitHub personal access token
> > > * Maven is configured using a settings.xml file located under your Maven home directory (typically, this will be /user.home/.m2/settings.xml).
> > > * a POM file (pom.xml) in your `androidlibrary` directory for publishing a package
> > 
> > 
> > Hi @Roseline-Bassey, thanks a lot for this. Unfortunately, I haven't been able to work on this yet, just starting. I managed to set up the Github Packages on my local machine, But when I try to test it out in CircleCI my android library build is failing, again😅, even though everything works fine locally. Still trying to resolve that and see what's wrong.
> 
> Hey, @nuilewis, could you share the error message you're getting from Circleci?

`androidlibrary_lib:mergeDemoBasicReleaseResources FAILED` I'm guessing it's because of some old cache files from previous builds which are still present and causing the issue.

**Comment by Roseline-Bassey** [comment]
Yes, It looks like you have a duplicate file name that needs to be removed. How about checking Circleci error log to be sure?

**Comment by Goodiec** [comment]
Hi @wbrunette, kindly review - https://github.com/Goodiec/_androidlibrary/packages/1813284. I also get the authentication error despite having set a personal access token and I am still trying to find a way around that.

**Comment by Roseline-Bassey** [comment]
@nuilewis If the problem persists, I'd suggest you clean and rebuild the project by selecting `Build` > `Clean Project` in Android Studio. Then, rebuild the project. This will clean up caches from the previous build process.

OR

Second Option: Go to `File` -> `Invalidate Caches` > `Invalidate and Restart` the project

**Comment by nuilewis** [comment]
I

> @nuilewis If the problem persists, I'd suggest you clean and rebuild the project by selecting `Build` > `Clean Project` in Android Studio. Then, rebuild the project. This will clean up caches from the previous build process.
> 
> OR
> 
> Second Option: Go to `File` -> `Invalidate Caches` > `Invalidate and Restart` the project

I think I messed something up in my working branch, and I don't think there is an issue on my Android Studio, because it works fine on my local, but doesn't on CircleCI. Anyways, I created a new branch from my master, which was working fine, and added the deployment to the `config.yml`, and now I'm getting the same error about transferring metadata

**Comment by nuilewis** [comment]
> I
> 
> > @nuilewis If the problem persists, I'd suggest you clean and rebuild the project by selecting `Build` > `Clean Project` in Android Studio. Then, rebuild the project. This will clean up caches from the previous build process.
> > OR
> > Second Option: Go to `File` -> `Invalidate Caches` > `Invalidate and Restart` the project
> 
> I think I messed something up in my working branch, and I don't think there is an issue on my Android Studio, because it works fine on my local, but doesn't on CircleCI. Anyways, I created a new branch from my master, which was working fine, and added the deployment to the `config.yml`, and now I'm getting the same error about transferring metadata

I got a 404 when I tried to visit [https://maven.pkg.github.com/nuilewis/androidlibrary](https://maven.pkg.github.com/nuilewis/androidlibrary), did anyone else have this issue? 

But here's my hosted package on GitHub
[https://github.com/nuilewis/androidlibrary/packages/1814361](https://github.com/nuilewis/androidlibrary/packages/1814361)

and here's the metadata
[https://maven.pkg.github.com/nuilewis/androidlibrary/org/odkx/androidlibrary/1.0-SNAPSHOT/maven-metadata.xml](https://maven.pkg.github.com/nuilewis/androidlibrary/org/odkx/androidlibrary/1.0-SNAPSHOT/maven-metadata.xml)

**Comment by S1Y333** [comment]
> > I
> > > @nuilewis If the problem persists, I'd suggest you clean and rebuild the project by selecting `Build` > `Clean Project` in Android Studio. Then, rebuild the project. This will clean up caches from the previous build process.
> > > OR
> > > Second Option: Go to `File` -> `Invalidate Caches` > `Invalidate and Restart` the project
> > 
> > 
> > I think I messed something up in my working branch, and I don't think there is an issue on my Android Studio, because it works fine on my local, but doesn't on CircleCI. Anyways, I created a new branch from my master, which was working fine, and added the deployment to the `config.yml`, and now I'm getting the same error about transferring metadata
> 
> I got a 404 when I tried to visit https://maven.pkg.github.com/nuilewis/androidlibrary, did anyone else have this issue?
> 
> But here's my hosted package on GitHub https://github.com/nuilewis/androidlibrary/packages/1814361
> 
> and here's the metadata https://maven.pkg.github.com/nuilewis/androidlibrary/org/odkx/androidlibrary/1.0-SNAPSHOT/maven-metadata.xml

Yes, I have the same 404 error and am working on this problem. @nuilewis

**Comment by tr-sangale** [comment]
> > I
> > > @nuilewis If the problem persists, I'd suggest you clean and rebuild the project by selecting `Build` > `Clean Project` in Android Studio. Then, rebuild the project. This will clean up caches from the previous build process.
> > > OR
> > > Second Option: Go to `File` -> `Invalidate Caches` > `Invalidate and Restart` the project
> > 
> > 
> > I think I messed something up in my working branch, and I don't think there is an issue on my Android Studio, because it works fine on my local, but doesn't on CircleCI. Anyways, I created a new branch from my master, which was working fine, and added the deployment to the `config.yml`, and now I'm getting the same error about transferring metadata
> 
> I got a 404 when I tried to visit https://maven.pkg.github.com/nuilewis/androidlibrary, did anyone else have this issue?
> 
> But here's my hosted package on GitHub https://github.com/nuilewis/androidlibrary/packages/1814361
> 
> and here's the metadata https://maven.pkg.github.com/nuilewis/androidlibrary/org/odkx/androidlibrary/1.0-SNAPSHOT/maven-metadata.xml

yes @nuilewis had the same issue of 404 , the package is getting hosted at https://github.com/tr-sangale/androidlibrary/packages/1816214
if i get any leads will surely update

**Comment by S1Y333** [comment]
@wbrunette Hi mentor, I published the package, please verify -> https://maven.pkg.github.com/S1Y333/androidlibrary. But I was stuck for hours trying to figure out why this page is getting 404 error, any clues for this? Thanks so much

**Comment by nuilewis** [comment]
> @wbrunette Hi mentor, I published the package, please verify -> https://maven.pkg.github.com/S1Y333/androidlibrary. But I was stuck for hours trying to figure out why this page is getting 404 error, any clues for this? Thanks so much

HI @S1Y333, it seems everyone has that error. I think you should add the link to your package on Github because that is where the package is being hosted, it should look something like this  `https://github.com/nuilewis/androidlibrary/packages/1814361`

**Comment by S1Y333** [comment]
> @wbrunette Hi mentor, I published the package, please verify -> https://maven.pkg.github.com/S1Y333/androidlibrary. But I was stuck for hours trying to figure out why this page is getting 404 error, any clues for this? Thanks so much

@nuilewis ok thanks!

@wbrunette  Hi mentor, my package is here: https://github.com/S1Y333/androidlibrary/packages/1816167

**Comment by darellwest** [comment]
@wbrunette  my package is here for review https://github.com/darellwest/odk-x-androidlibrary/packages/1816853 

I also got same error you asked us not to worry about earlier while implementing the automatic build. 
My link here https://maven.pkg.github.com/darellwest/odk-x-androidlibrary shows 404 error each time I try to visit, I have been trying to figure out why that is.

**Comment by Roseline-Bassey** [comment]
Hi, @wbrunette, I have fixed the `Could not transfer metadata org.android:androidlibrary:1.0-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/Roseline-Bassey/androidlibrary): status code: 401, reason phrase: Unauthorized (401)` issue I experience earlier by configuring Maven in the config file to automatically deploy the successfully built libraries to  GitHub Packages repository.

![Screenshot 2023-04-03 160456](https://user-images.githubusercontent.com/47522955/229552675-6b3f93b1-55e7-4d74-8ad3-9f30914fcea2.png)

**Comment by nuilewis** [comment]
Hey all, I also noticed that it may be good to enable the `Pass secrets to builds from forked pull requests` option in the CicrcleCI project settings, under the `Advanced` settings. This would allow CircleCI to share your environment variables and secrets to build jobs coming from forks, ensuring that the build passes.


![image](https://user-images.githubusercontent.com/72214279/231668312-8186be80-a14e-45b5-8c09-27e2338deaee.png)
