### ISSUE TITLE
Fix the issue on odk-x/docs not working on latest python version

### ISSUE THREAD

**Issue by S1Y333** [opendatakit/tool-suite-X#411]
> @nuilewis have you encountered an error when running ./run-task.sh odkx-autobuild ? I have installed docker and built the image successfully. Any idea? Thank you!
> 
> <img alt="Screen Shot 2023-03-13 at 6 32 51 PM" width="1089" src="https://user-images.githubusercontent.com/105386341/224860058-963bdbe0-94a1-4d79-acb8-9e44e45d1836.png">

@nuilewis Problem solved. Here's the debugging process: 
1. when running ./run-task.sh odkx-autobuild , it shows the import python problem because it is using the python version on my laptop, which is 3.10, so I tried to upgrade the python version on my laptop to 3.11 but the problem continues.
2. Then I noticed in the  dockerfile, it didn't specify which python version, which can cause problem "FROM python", so I changed it to "FROM python:3.9.16-buster" specific version ( the version later than 3.9 all didn't work)
3. next, rebuild the docker image and then run  ./run-task.sh odkx-autobuild, it's working now. So it might need to fix the version problem later on.
<img width="552" alt="Screen Shot 2023-03-14 at 8 36 40 AM" src="https://user-images.githubusercontent.com/105386341/225002927-b93ffa17-6dbd-467d-90d6-6b8afab31280.png">

_Originally posted by @S1Y333 in https://github.com/odk-x/tool-suite-X/issues/408#issuecomment-1468028858_

**Comment by wbrunette** [comment]
@S1Y333 do you want to submit a Pull Request with your fix to the docs repo?

**Comment by S1Y333** [comment]
@wbrunette Yes, I submitted the docker file update with my docs pull request. Is this what you mean?

**Comment by wbrunette** [comment]
@S1Y333 sorry I missed the PR email somehow  :) Yes that is what I meant

**Comment by S1Y333** [comment]
@wbrunette Here's the pull request with the docs updates and docker file update. --> https://github.com/odk-x/docs/pull/225#issue-1624084620

**Comment by wbrunette** [comment]
Yes, I had already found it and self assigned myself to review it in the future.
