### ISSUE TITLE
OUTREACHY SPRING 2023 ISSUE

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#412]
People have been asking for more issues, so this issue is a more challenging issue that you are not expected to solve, but if you do, great!

NOTE: This issue has not been attempted yet by the mentors so the mentors will not help with this issue.

GOAL: Build and test Sync-Endpoint repository using CircleCI in your GitHub account.

MAIN TASK: To complete this issue, you will need to first fork the “odk-x/sync-endpoint” repository to your GitHub account. Next, you will need to set up CircleCI continuous build check for pull requests sent to your version of the sync-endpoint repository. NOTE: for this issue, you do NEED to have CircleCI run the unit tests and verify the test pass.

VERIFICATION: Once you have CircleCI building a pull request for sync-endpoint post a link to your sync-endpoint repository. One of the mentors will test it by trying to submit a pull request to verify CircleCI is building sync-endpoint.

**Comment by Roseline-Bassey** [comment]
I will like to try this.

**Comment by wbrunette** [comment]
go ahead :)

**Comment by tr-sangale** [comment]
hey @wbrunette , i thought that there's no need to get myself assigned to issue, but have already started to work on the issue.
will you please assgin me to the issue

**Comment by cvemann** [comment]
> hey @wbrunette , i thought that there's no need to get myself assigned to issue, but have already started to work on the issue. will you please assgin me to the issue

You don't need to be assigned @tr-sangale, go ahead and work on it.

**Comment by wbrunette** [comment]
@tr-sangale , @Cveman1 is correct you do not need to be assigned to the general outreachy spring 2023 issues anyone can work on it.

**Comment by tr-sangale** [comment]
okay, thankyou @wbrunette @Cveman1 !

**Comment by S1Y333** [comment]
Hi mentor @wbrunette, I will be working on this issue too.

**Comment by cvemann** [comment]
Yes please. Go ahead @S1Y333

**Comment by S1Y333** [comment]
Hi mentors, I am looking into this task and tried on circleci. I got this result:

`[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (start) on project sync-endpoint-docker-swarm: Execution start of goal io.fabric8:docker-maven-plugin:0.34.1:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured`

I researched and wondered if we should learn some docker swarm to solve this problem. Do you have any suggestions on this? Should we spend some time on docker swarm or it isn't quite connected to solving our task?

Thank you so much!

**Comment by wbrunette** [comment]
@S1Y333 as a reminder the "NOTE: This issue has not been attempted yet by the mentors so the mentors will not help with this issue." Having said that docker swarm is a thing. might not be the right thing, but it is the thing being used likely

**Comment by nuilewis** [comment]
Hey all, I've been trying to run a build of the `sync endpoint` on my local machine, It's been running now for over an hour, is that normal? It's currently stuck at `Building sync-endpoint-docker-swarm 2.1.9` step 5 of 8

**Comment by nuilewis** [comment]
> Hey all, I've been trying to run a build of the `sync endpoint` on my local machine, It's been running now for over an hour, is that normal? It's currently stuck at `Building sync-endpoint-docker-swarm 2.1.9` step 5 of 8

Was supposed to enable `swarm mode` first by running `docker swarm init`

**Comment by Roseline-Bassey** [comment]
Hi @nuilewis, I experienced the same. 'mvn clean install' tends to build for over an hour. This could be because sync-endpoint is a servlet project and multi-module too.

**Comment by nuilewis** [comment]
> > Hey all, I've been trying to run a build of the `sync endpoint` on my local machine, It's been running now for over an hour, is that normal? It's currently stuck at `Building sync-endpoint-docker-swarm 2.1.9` step 5 of 8
> 
> Was supposed to enable `swarm mode` first by running `docker swarm init`

Enabling swarm mode seemed to fix the long build times issue.  It was able to complete step 5, and I now have issues with step 6, running the docker tests. 

I got this error initially 
```
Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (start) on project sync-endpoint-docker-test: Unable to build image [odk/sync-endpoint-test] : "The command '/bin/sh -c chmod +x /tm
p/init.sh &&     rm -rf /usr/local/tomcat/webapps/ROOT &&     unzip /sync-endpoint-war.war -d /usr/local/tomcat/webapps/ROOT &&     rm /sync-endpoint-war.war' returned a non-zero code: 127"  -> [Help 1]
[ERROR]
```
After searching on it, from what I could gather it seemed Docker was unable to find some certain files, I then looked at the Dockerfiles and realised the test Dockerfile was missing this command
 `RUN apt-get update && apt-get install unzip`  which was available in the Build Docker file.
I added this to the test Docker File and it seemed to solve that,  but now I got this error

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (start) on project sync-endpoint-docker-test: Cannot create docker access object : \\.\
pipe\docker_engine (All pipe instances are busy) -> [Help 1]
```

Still trying to see how to solve that.

**Comment by Roseline-Bassey** [comment]
Have you fixed that yet? 

For me `mvn clean install` takes a long time to build. The majority of the time is consumed by integration tests.

**Comment by wbrunette** [comment]
It will take a long time as it does a lot.

**Comment by S1Y333** [comment]
Hi @nuilewis, yes, it was running so long that I thought something is wrong so I canceled the process... I will try again.

I found some great reference documents to help understand endpoint logic ->  https://odk-x.org/software/#odk-x-sync-endpoint

**Comment by nuilewis** [comment]
> Have you fixed that yet?
> 
> For me `mvn clean install` takes a long time to build. The majority of the time is consumed by integration tests.

So the Docker tests now passed without any error, I haven't done anything, I just ran `mvn clean install` again this morning.

**Comment by Roseline-Bassey** [comment]
> 

How long did it take to build?

**Comment by Roseline-Bassey** [comment]
> > Have you fixed that yet?
> > For me `mvn clean install` takes a long time to build. The majority of the time is consumed by integration tests.
> 
> So the Docker tests now passed without any error, I haven't done anything, I just ran `mvn clean install` again this morning.

How long did it take to build?

**Comment by nuilewis** [comment]
> > > Have you fixed that yet?
> > > For me `mvn clean install` takes a long time to build. The majority of the time is consumed by integration tests.
> > 
> > 
> > So the Docker tests now passed without any error, I haven't done anything, I just ran `mvn clean install` again this morning.
> 
> How long did it take to build?

Its currently stuck at the Postgres tests. It has been on that for about 3 hours now

**Comment by Roseline-Bassey** [comment]
That takes time.
We may need to install Postgres, Tomcat and MySQL and create the necessary database credentials to be able to run integration tests. From one of the error messages I got, I think the application is unable to establish a connection with the database, leading to a failed build or timeout.

I'm currently reviewing the contents of the sync-endpoint's `docs` folder, which you may find useful to check out as well.

**Comment by nuilewis** [comment]
> That takes time. We may need to install Postgres, Tomcat and MySQL and create the necessary database credentials to be able to run integration tests. From one of the error messages I got, I think the application is unable to establish a connection with the database, leading to a failed build or timeout.
> 
> I'm currently reviewing the contents of the sync-endpoint's `docs` folder, which you may find useful to check out as well.

I see. I think I'll let it go overnight next time.

But by the way, isn't that the whole point of Docker? It provides an environment with all our dependencies so we don't have to install them manually, and from the logs, I can see Docker is already downloading and installing both Postgres and Tomcat in the container. I think the `docs` refer to when we are trying to build the project without using Docker. then we need to install those environments manually, or I'm I missing something?

**Comment by nuilewis** [comment]
> Hi mentors, I am looking into this task and tried on circleci. I got this result:
> 
> `[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (start) on project sync-endpoint-docker-swarm: Execution start of goal io.fabric8:docker-maven-plugin:0.34.1:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured`
> 
> I researched and wondered if we should learn some docker swarm to solve this problem. Do you have any suggestions on this? Should we spend some time on docker swarm or it isn't quite connected to solving our task?
> 
> Thank you so much!

Hi @S1Y333,  Did you make sure Docker is running? and have you tried to enable swarm mode on Docker?

You can try adding a run command to enable swarm mode with `docker swarm init` before running `mvn clean install`

**Comment by Roseline-Bassey** [comment]
> > That takes time. We may need to install Postgres, Tomcat and MySQL and create the necessary database credentials to be able to run integration tests. From one of the error messages I got, I think the application is unable to establish a connection with the database, leading to a failed build or timeout.
> > I'm currently reviewing the contents of the sync-endpoint's `docs` folder, which you may find useful to check out as well.
> 
> I see. I think I'll let it go overnight next time.
> 
> But by the way, isn't that the whole point of Docker? It provides an environment with all our dependencies so we don't have to install them manually, and from the logs, I can see Docker is already downloading and installing both Postgres and Tomcat in the container. I think the `docs` refer to when we are trying to build the project without using Docker. then we need to install those environments manually, or I'm I missing something?

You're right. Docker does that already.

**Comment by S1Y333** [comment]
Hi @wbrunette, this test has errors showing but won't stop and keep running for hours. Please find the attached screen recording for this. Does this count as a bug? If an error happens, it should stop, right?

Thank you



https://user-images.githubusercontent.com/105386341/231554883-a28b1b8f-e797-4f92-ab7a-419021473cbf.mov

**Comment by nuilewis** [comment]
I think I made a bit of progress on my end. 
Those random Docker errors I was getting seem to have been resolved. I guess it was because I was low on storage, so I cleaned my machine and set up my environment again. 

So my main error was something about password authentication. so It could not run the tests, and would just loop over the same error for hours. My error looked something like this.

```
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; 
nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "Open Data Kit")
```

I realised that the config info in the `integration.properties` file in the `external-resources` directory has to match exactly with the `create_db_and_user.sql` file in the `postgres` directory in `postgres-test` folder. 

The build runs the `create_db_and_user.sql` file which has the instructions to create the database for testing with a certain configuration, and the `integration.properties` file supplies those configurations/credentials for the database when the test starts, from my understanding.


![image](https://user-images.githubusercontent.com/72214279/232247242-a9977b1d-d9e0-4902-afb1-86832930a8c8.png)

I was trying to experiment by configuring it with different users and passwords and apparently, I had edited the `UNENCRYPTED PASSWORD 'odk'` in the  `create_db_and_user.sql` file to `UNENCRYPTED PASSWORD "odk"` and learned the hard way that there's a difference between `'odk'` and `"odk"` in SQL. So it was causing the password error when it tried to create a `PoolableConnectionFactory`

After I resolved the password issue, I could see from the logs that the Postgres integration test was running as it should and does not loop for hours but will actually fail and stop when it was complete.

The next error I got was something similar to this

```
org.opendatakit.aggregate.odktables.api.DataServiceTestIT org.opendatakit.aggregate.odktables.api.DataServiceTestIT.testGetRowsNoRows Time elapsed: 1.452 s <<< ERROR!
org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway: /odktables/default/tables/people at
postgres.test@2.1.9/org.opendatakit.aggregate.odktables.api.DataServiceTestIT.setUp(DataServiceTestIT.java:25)

```
and

```INFO: (CONNECTING) [id: 0x78edaa60, L:null ! R:localhost/127.0.0.1:8888]: Connection to upstream server failed
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: 
localhost/127.0.0.1:8888
Caused by: java.net.ConnectException: Connection refused: no further information
```
on some of the tests.

It seems it has some issues connecting with the server.

The test report I got shows about 82 tests ran, with 22 having errors, and 0 failures with 1 skipped test, and the integration test typically takes about 20-25 minutes to run on my local machine. I am still working on trying to get those tests with errors to work, if someone has an idea what could be the problem, please share. Thanks!

**Comment by nuilewis** [comment]
> Hi @wbrunette, this test has errors showing but won't stop and keep running for hours. Please find the attached screen recording for this. Does this count as a bug? If an error happens, it should stop, right?
> 
> Thank you

Hello @S1Y333, I think I also got something about a role not existing. I think your problem should be similar to my password issue but it's rather the user which is the `role` that does not match between the two configuration files. I think you should verify if your `create_db_and_user.sql` and `integration.properties` have the same configuration.
