### ISSUE TITLE
Need for a sign-up UI in either ODK-X Surveys/Tables 

### ISSUE THREAD

**Issue by cvemann** [opendatakit/tool-suite-X#425]
WARNING: This is a design practice issue. You should not create a proposal that creates as Sign-UI for your proposal.

There’s currently no means of onboarding into either Tables or Surveys. It needs a sign-up UI that allows users to sync to the server upon installing the applications.

### Why this needs to be improved:
If you go through any of the ODK-X Apps, you'll find that the current syncing process is long and tedious. You have to find the server settings in the settings page, before connecting to the server to use the app.

### Objectives
- To make onboarding easier for field workers who use these tools.
- Reducing the number of steps to start using the Apps.

Guidance
You can make reference to this: [Screen Designs - GSoC'21@ODK-X](https://docs.google.com/document/d/177Row1xrUgUMAt_F-hvWxo-J6cHN3GLGHlflU36QoiA/edit#) while adhering to the [ODK-X Design Guidelines](https://docs.google.com/presentation/d/1Ol7YhG4WPLOWCoQZUrKHLPguHSiDz8RC3m8dNyTGGLo/)

### Current UI
![image](https://github.com/odk-x/tool-suite-X/assets/80982139/2d984e45-63c9-471d-a5d0-414c2643d957)

**Comment by teelda** [comment]
@Godswill @elmps2018 @wbrunette 
Please, I'll need clarification on this issue.

Am I expected to create a seamless sign up experience based on the flow in the current app while using ODK-X design guidelines shared?

Or I am to improve on the sign up process based on the screens and design guidelines in the reference that was shared. https://docs.google.com/document/d/177Row1xrUgUMAt_F-hvWxo-J6cHN3GLGHlflU36QoiA/edit?usp=drivesdk

**Comment by elmps2018** [comment]
@Cveman1 can you explain a bit more about what is required here? Thanks!

**Comment by cvemann** [comment]
Hi @teelda.

Currently, users go through a long process of connecting to the servers in either ODK-X Tools. 

If you've tried [installing the sample application](https://docs.odk-x.org/survey-sample-app-install), you'll find that the process can be tedious. Users have to go digging into the app settings to connect to the server. 

Propose a solution that allows for seamless onboarding as soon as the app is installed.

P.S: You might have to try installing the sample applications yourself to have a better understanding

**Comment by teelda** [comment]
@Cveman1 @elmps2018  Please, I will need a review to be sure I didn't fail to capture any step in the current onboarding flow on the application. 

The Userflow diagram I attached below is based on the flow I observed on the app. From opening the app to successfully viewing a list of available forms. A feedback on the Userflow, would assist me tailor my solution to redesigning this flow to provide a better Sign Up experience for the users. Thank you

[A figma link to view it better](https://www.figma.com/file/Wzffk1x7NFBHfLdGIBtZZB/ODK_X?type=whiteboard&node-id=0%3A1&t=1sHsWuU2NV6KXeXc-1)

<img width="8112" alt="Userflow" src="https://github.com/odk-x/tool-suite-X/assets/57068192/a145c8ac-881c-4936-b14f-3d108d3fa77f">

**Comment by cvemann** [comment]
Hi @teelda, you've done pretty detailed work of identifying the existing user flow and proposing a new one.

With what you've done, the current syncing flow seems messy and tiring. What you've proposed seems straightforward and very functional. 

You're good to go, it would help for us to see screenshots of how this user flow would work for ODK-X users. 

Also, we wait for alternate contributions from others.

Well done!


> @Cveman1 @elmps2018 Please, I will need a review to be sure I didn't fail to capture any step in the current onboarding flow on the application.
> 
> The Userflow diagram I attached below is based on the flow I observed on the app. From opening the app to successfully viewing a list of available forms. A feedback on the Userflow, would assist me tailor my solution to redesigning this flow to provide a better Sign Up experience for the users. Thank you
> 
> [A figma link to view it better](https://www.figma.com/file/Wzffk1x7NFBHfLdGIBtZZB/ODK_X?type=whiteboard&node-id=0%3A1&t=1sHsWuU2NV6KXeXc-1)
> 
> <img alt="Userflow" width="2000" src="https://user-images.githubusercontent.com/57068192/273523741-a145c8ac-881c-4936-b14f-3d108d3fa77f.png">

**Comment by teelda** [comment]
Thank you @Cveman1 This is a document showing clear screenshots of my solution and also explaining my design process and decisions to the screenshots attached below. [Proposed solution for the ODK-X sign up process](https://docs.google.com/document/d/1p2oJnP0KhO-jvHCNXTwzUu4lDis2z52DtdZCUSia6l4/edit?usp=sharing)

I'm open to feedback for further iterations. Thank you

**Sign In as an Authenticated User**
![Sign In as Authenticated User](https://github.com/odk-x/tool-suite-X/assets/57068192/422ce946-0529-4644-8b09-cdeb8cea6df4)

**Sign In as Anonymous for returning users**
![Sign In as Anonymous](https://github.com/odk-x/tool-suite-X/assets/57068192/6e71887f-5ce6-464a-afd1-89c840c5ea4e)

**Sign In as Anonymous for first time users**
![FIrst time Sign in as Anonymous](https://github.com/odk-x/tool-suite-X/assets/57068192/88e72910-fb44-4a2d-8092-dc9ba25a5cc8)

**User Signs out of app**
![User is Logged out](https://github.com/odk-x/tool-suite-X/assets/57068192/b8e79dd8-0065-44ce-b4ca-8fba937f5e02)

**Updated Home Screen design with search field**
![User search bar](https://github.com/odk-x/tool-suite-X/assets/57068192/9e889748-1ff8-4af9-8714-2a925b76e0f2)

**Comment by wbrunette** [comment]
WARNING: This is a design practice issue. You should not create a proposal that creates as Sign-UI for your proposal.

**Comment by teelda** [comment]
> WARNING: This is a design practice issue. You should not create a proposal that creates as Sign-UI for your proposal.

Noted! @wbrunette 

Kindly, do you mean, I shouldn't include this in my final application or I shouldn't have created a document for the issue?

**Comment by cvemann** [comment]
Yes, DON'T include it as a project proposal in your final application. @teelda
