### ISSUE TITLE
Clarity Improvement

### ISSUE THREAD

**Issue by chioma-data-analytics** [opendatakit/tool-suite-X#432]
**Sync Endpoint is a server that enables data to replicated between mobile devices** contained in https://odk-x.org/software/, subtitle ODK-X Sync Endpoint, line 1.

Add the verb **“be”** after “to” 

This enhances the clarity and readability of the sentence.

![clarity issue](https://github.com/odk-x/tool-suite-X/assets/113908370/1afbdee2-9070-49fe-a6f8-ef87bea30866)

**Comment by chioma-data-analytics** [comment]
Can I be assigned to it?

**Comment by Lamouresparus** [comment]
Yes you can go ahead with it

**Comment by chioma-data-analytics** [comment]
> Yes you can go ahead with it

Thank you @Lamouresparus I have created a pull request for the changes, please could you review it for accuracy and your feedback. Thanks

**Comment by chioma-data-analytics** [comment]
This is the link. https://github.com/odk-x/website/compare/master...Chioma-data-analytics:website:master

**Comment by wbrunette** [comment]
Unfortunately, the pull request is not created until you push the green
create pull request button. Afterwards, it will show up in the list of pull
requests on the repo.

**Comment by chioma-data-analytics** [comment]
Thanks @wbrunette  It appears my approach was incorrect, I would review and ensure to create the pull request. Thanks so much this feedback means so much to me.

**Comment by chioma-data-analytics** [comment]
@wbrunette @Lamouresparus  I have created the pull request. Please could you review it. Thanks for your guidance.
