### ISSUE TITLE
"Import file must reside in opendatakit folder" error while attempting to import csv data

### ISSUE THREAD

**Issue by permission-error** [opendatakit/tool-suite-X#439]
Tag @wbrunette, @elmps2018, and @Redeem-Grimm-Satoshi.

I'm trying to follow the instructions in the documentation found at [this link](https://docs.odk-x.org/tables-managing/#importing-data) to import data from a CSV file directly into a table. However, I'm encountering an error message that says, `Import file must reside in opendatakit folder.`

The issue I'm facing is that the documentation mentions a path `/csv` on my device, but I can't find this path in `/opendatakit/default/config/assets.` So, I manually created the `/csv` folder and put my `people.csv` file in `/opendatakit/default/config/assets/csv.`

When I try to load `people.csv` from this directory into the tables, I still get the same error message, `Import file must reside in opendatakit folder.` I'm not sure if I'm doing something wrong or if there might be a bug. Any help or guidance on this would be much appreciated.

![Screenshot_20231012_141826](https://github.com/odk-x/tool-suite-X/assets/111251750/11e59e5e-bc01-4cfa-8bc4-53652cbef472)

**Comment by elmps2018** [comment]
Hi @permission-error! This is a known issue already raised here https://github.com/odk-x/tool-suite-X/issues/350 - so I am going to close your additional issue just so there's one. This is something that will hopefully get fixed in the next release.

**Comment by wbrunette** [comment]
Reclosing as dupliate

**Comment by wbrunette** [comment]
Duplicate

**Comment by wbrunette** [comment]
Duplicate
