### ISSUE TITLE
Create Test to Replicate Issue - OUTREACHY WINTER 2023

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#440]
This issue is targeted at interns interested in the testing project. However, any intern may work on this issue to demonstrate coding abilities.

Create a test in Tables to recreate this issue:
https://github.com/odk-x/tool-suite-X/issues/350
https://github.com/odk-x/tool-suite-X/issues/439 (Duplicate of the previous issue)

Creating a test before fixing it is a style of development called "Test Driven Development."
https://en.wikipedia.org/wiki/Test-driven_development

**Comment by Kemyikpe** [comment]
@wbrunette Kindly assign this issue to me.

**Comment by Kemyikpe** [comment]
@wbrunette greetings, I am patiently waiting for your respond for the issue to be kindly assign to me.

**Comment by cvemann** [comment]
You can go ahead to work on it without being assigned @Kemyikpe

**Comment by Kemyikpe** [comment]
Thank you @Cveman1

**Comment by permission-error** [comment]
@wbrunette can all the applicants attempt this issue?

**Comment by Redeem-Grimm-Satoshi** [comment]
> @wbrunette can all the applicants attempt this issue?

You don't need to be assigned before you can work on this issue

**Comment by nadin-kum** [comment]
hello @Redeem-Grimm-Satoshi 
I downloaded the APK of [Service app](https://github.com/odk-x/services/releases/tag/2.1.10) and cloned its corresponding [GitHub repository](https://github.com/odk-x/services). However, I've noticed that the version of the APK is higher than the code version available on GitHub.

please what would be the best course of action in this situation? I want to work on issue but  i am currently confuse

**Comment by wbrunette** [comment]
@nadin-kum what do you mean by this? And you are incorrect as the version is controlled by our gradle config repo. I think you are confusing what "code version" means.

In something that i do not expect anyone applying for outreachy to know... the version is controlled by this statement
gradle.ext.gradleConfigVersion = 155

CORRECTION: I checked it and you are correct, it should be 156 :) good job @nadin-kum

**Comment by wbrunette** [comment]
@nadin-kum since you discovered this why don't you create a PR so you get credit in your application. This is the diff:
https://github.com/odk-x/services/compare/master...2.1.10

It will give you a chance to practice your Git skills.

You need to checkout the tag 2.1.10 in the Services repo and create a branch in your repository based on 2.1.10. Once you do that create a PR against master and we will merge!

**Comment by nadin-kum** [comment]
@wbrunette thank you!  i will do just that

**Comment by nadin-kum** [comment]
Hello @wbrunette I have submitted the PR please verify [](https://github.com/odk-x/services/pull/263)

**Comment by nadin-kum** [comment]
[here is the link](https://github.com/odk-x/services/pull/263)
