### ISSUE TITLE
Explore newly released Services APK and report bugs - OUTREACHY WINTER 2023

### ISSUE THREAD

**Issue by Redeem-Grimm-Satoshi** [opendatakit/tool-suite-X#441]
A newly signed Services APK has been released with a revamped UI

Explore this app and report bugs

[Link to apk](https://drive.google.com/file/d/1a5wQhB8JuMheX1046vbiU0U2CKRdAweK/view?usp=share_link)

**Comment by Redeem-Grimm-Satoshi** [comment]
You don't need to be assigned to work on this :)

**Comment by Ukwuezepascaline** [comment]
Hi @Redeem-Grimm-Satoshi ,
I tried opening the link but an “unsupported file type” error message. 
could the fault be from my end?

**Comment by chioma-data-analytics** [comment]
@Ukwuezepascaline try one of the suggested third party apps.

**Comment by Redeem-Grimm-Satoshi** [comment]
> Hi @Redeem-Grimm-Satoshi , I tried opening the link but an “unsupported file type” error message. could the fault be from my end?

Its hosted on google drive, the fault should be at your end

**Comment by Ukwuezepascaline** [comment]
Alright, thank you! 
let me try using another device.

**Comment by chioma-data-analytics** [comment]
@Redeem-Grimm-Satoshi  
There is no option to open or edit the file with suggested third party apps on a mobile device. Try to open on a mobile device and got this:
![Screenshot_20231019-101359_Chrome](https://github.com/odk-x/tool-suite-X/assets/113908370/9c0e3243-38b8-4590-aac1-e696ebfdf27f)
![Screenshot_20231019-095917_Chrome](https://github.com/odk-x/tool-suite-X/assets/113908370/0456e2bb-c99c-4503-9a31-cd21801165fb)
![Screenshot_20231019-095839_Chrome](https://github.com/odk-x/tool-suite-X/assets/113908370/18ed674f-9250-4e95-ade7-834d12b4dd51)

**Comment by Chinex-Boroja** [comment]
@Chioma-data-analytics @Ukwuezepascaline you should download the APK file from Google Drive. From your screenshot above, click on `download anyway` 
- Check on your device where the APK file is downloaded
- Click on the APK file to install, it should prompt a dialog box with the message `your phone is not allowed to install unknown apps from this source`. See screenshot below
![1697711968074](https://github.com/odk-x/tool-suite-X/assets/61055200/404589e8-f15d-453e-b71a-c49bc50ea200)

- Go to your settings, then tap the button to `allow from this source`. See screenshot below

![1697711968046](https://github.com/odk-x/tool-suite-X/assets/61055200/c68aac1d-0baf-4253-af67-6ca6b4452b9e)

- Navigate back to the downloaded APK file, and try installing it again

![1697711968016](https://github.com/odk-x/tool-suite-X/assets/61055200/b4648ccd-d80c-49c4-883d-f205db213b38)

- Then allow default services, the app should be successfully installed
![1697711967953](https://github.com/odk-x/tool-suite-X/assets/61055200/57271735-42a4-499d-b289-b56824397ec6)

![1697711967920](https://github.com/odk-x/tool-suite-X/assets/61055200/e21bd3bf-e9b7-4974-8abc-1522849346ce)

**Comment by teelda** [comment]
@Redeem-Grimm-Satoshi @cveman1 I downloaded the new services app and went through it but didn't find any bug yet.

When I opened the survey app and tried to Sign In, I realized the new services app had been integrated into the survey app. However, the previous flow, allowed the **user to fill in username and password**. Then opens a modal that prompts the **user to authenticate new user** upon clicking the back button. But when I clicked the back button on the new app, it took me back to the settings page and I had to click on permissions to "**Verify new user**". 


I am not sure if the server verification and synchronisation is done automatically in the new app. If not, I am suggesting a **'Continue'** button be added to the screen after the user password is successful, to aid the user from trying to figure out how to verify server.

**When I clicked on the settings icon from the home screen of the survey app.**

![WhatsApp Image 2023-10-22 at 13 03 45](https://github.com/odk-x/tool-suite-X/assets/57068192/24a8330c-00aa-46ed-a201-deb11c8f833a)

**Then I clicked on Server** 

![WhatsApp Image 2023-10-22 at 12 52 48](https://github.com/odk-x/tool-suite-X/assets/57068192/9c6400f4-c576-4d19-8bda-00bf4488fa7d)

![WhatsApp Image 2023-10-22 at 12 52 45](https://github.com/odk-x/tool-suite-X/assets/57068192/6d8427d5-524f-49d1-bbf2-c47e1520be6d)

**I updated my Username**

![WhatsApp Image 2023-10-22 at 12 52 47](https://github.com/odk-x/tool-suite-X/assets/57068192/ea2c266b-9d08-411b-8fe8-1b1ade25117f)

**Updated my password**

![WhatsApp Image 2023-10-22 at 12 52 46 (1)](https://github.com/odk-x/tool-suite-X/assets/57068192/281171a2-5a3b-40df-9c25-78fcbbf72c38)

**And I got an alert that indicated it was successful but it took me back to the settings screen.**

![WhatsApp Image 2023-10-22 at 12 52 46](https://github.com/odk-x/tool-suite-X/assets/57068192/8c352c07-2bda-4552-8928-44c0e58bbd8a)

**Comment by Redeem-Grimm-Satoshi** [comment]
@teelda Great observation
