### ISSUE TITLE
Update Testing Dependencies in ODKx Tables App

### ISSUE THREAD

**Issue by Lamouresparus** [opendatakit/tool-suite-X#442]
**Description:**
We need to update the testing dependencies in the ODK-X Android Library module-level `build.gradle` file to ensure that our tests are using the latest and most compatible libraries. This update will help maintain the stability and reliability of our app’s testing infrastructure.

**Steps to Fix:**
1. Open the `build.gradle` file for the ODK-X Android Library app located at `androidlibrary_lib/build.gradle`.
2. Identify the current testing dependencies in the dependencies section of the `build.gradle` file.
3. Check for the latest versions of the testing dependencies on their respective official websites or repositories.
4. Update the testing dependencies to their latest versions, ensuring compatibility with the app’s existing codebase.

**Expected Behavior:**
Updating the testing dependencies should ensure that our tests run smoothly and without issues.

**Testing:**

1. Make sure that the update doesn’t introduce any breaking changes to the existing code.
2. Run the tests locally to verify that they pass with the updated dependencies.

**Comment by Kemyikpe** [comment]
@Lamouresparus  please assign to me

**Comment by Chinex-Boroja** [comment]
Hi @Lamouresparus, can I also work on this issue?

**Comment by NiranjanNlc** [comment]
> Hi @Lamouresparus, can I also work on this issue?

i think , we can work on this issuse without being assighned for now . 
@Lamouresparus  we need to update the testing dependncies only , right ??

**Comment by Kemyikpe** [comment]
Hi @wbrunette @Lamouresparus I've been trying to run the androidTest but I keep getting this error on all the androidTest.
I've tried running it on the `androidlibrary` project directly but some issue, I also tried running from `survey`, and `services` projects too, I still encounter same issue.

I have read through most of the odk-x documentations I can could find.

Please what could I be doing wrong. 🙏

## Error screenshots:

<img width="1336" alt="image" src="https://github.com/odk-x/tool-suite-X/assets/107570182/b1d9f155-283a-410f-965f-c8c276c60315">

<img width="1070" alt="image" src="https://github.com/odk-x/tool-suite-X/assets/107570182/a2ffabf6-f85d-49f7-8d56-152b123b688c">

I saw similar issues online which for them unchecking the *Run Android Instrumented Tests Using Gradle* worked for them, but it did't help in my case.

<img width="670" alt="Screenshot 2023-10-23 at 12 45 59 PM" src="https://github.com/odk-x/tool-suite-X/assets/107570182/bc83a297-b56b-4647-9e65-f027f0aaf639">

**Comment by Chinex-Boroja** [comment]
Hi @Kemyikpe if I may ask, are you currently working on the Android ODK-X Library? 
I followed the instructions described by @Lamouresparus. Which are:
- Upgrading the test dependencies to the latest version in the `build.gradle` file located at `androidlibrary_lib/build.gradle`
- Synced my gradle with the changes of latest dependencies updates
- Ran the tests again, and all passed

I have attached a couple of screenshots to demonstrate my steps.
## Updated test dependencies
![Updated Test Dependencies](https://github.com/odk-x/tool-suite-X/assets/61055200/51631e45-ce0e-458e-bd07-95beaad921a1)

## Result of Running the tests
![TestPassedInAndroidLibrary](https://github.com/odk-x/tool-suite-X/assets/61055200/f116765c-1d2f-4373-9886-a31188bb7e64)

Also, my _Run Android Instrumented Tests Using Gradle_ is checked. I don't really think that should be an issue, I guess.
![RunAndroidInstrumentedTests Checked](https://github.com/odk-x/tool-suite-X/assets/61055200/042ed560-4f92-44ff-84bc-ffd0e977dce4)

@Lamouresparus you can confirm if these are the expected results for this issue, thank you

**Comment by Kemyikpe** [comment]
Thank you @Chinex-Boroja for the suggestions, but i had already done what you suggested, but the test still didn't work.

**Comment by Kemyikpe** [comment]
# Here is what helped me fixed the issue: <br>
@Chinex-Boroja @Lamouresparus @wbrunette 

In search for the solution, I found this [link](https://issuetracker.google.com/issues/304343840?pli=1), which one of the suggestions was to downgrade to or install Android Studio Electric Eel or Flamingo.

Since I was using Android Studio Giraffe, I had to download Flamingo which is a bit higher than Electric Eel, ran the test again, everything now works. 😁

I have opened a [PR](https://github.com/odk-x/androidlibrary/pull/258) @wbrunette @Lamouresparus kindly review, thank you 🙏

**Comment by NiranjanNlc** [comment]
Hey @Kemyikpe , i was also thinking of raising the PR for it , but as you already did it , i think i should not duplicate my effort to replicate it .
Just a one small suggestion that we should raise the PR against the development branch , rather than the master  branch as you did  .
its super easy , just change the base branch of your PR from master to development.
Good luck.

**Comment by Kemyikpe** [comment]
@NiranjanNlc  Thank you for the suggestion.
@wbrunette @Lamouresparus  I hope this is okay?

**Comment by wbrunette** [comment]
@Kemyikpe there is a lot of text on this thread, I am not sure what you question is.

**Comment by Kemyikpe** [comment]
> @Kemyikpe there is a lot of text on this thread, I am not sure what you question is.

Hi @wbrunette sorry, I asked a question which I later found a fix for it.

Kindly review the PR, thank you 🙏

**Comment by wbrunette** [comment]
@Kemyikpe which PR, the PR you had which was good got closed because you according to GitHub "[Kemyikpe](https://github.com/Kemyikpe) closed this by deleting the head repositor"

Did you open a new one?

**Comment by Kemyikpe** [comment]
> @Kemyikpe which PR, the PR you had which was good got closed because you according to GitHub "[Kemyikpe](https://github.com/Kemyikpe) closed this by deleting the head repositor"
> 
> Did you open a new one?

Yes sending another PR now, i wanted to get the developement branch but can't get it from my forked repository.

**Comment by Kemyikpe** [comment]
@wbrunette please this is the new [PR](https://github.com/odk-x/androidlibrary/pull/259)

**Comment by Lamouresparus** [comment]
Great job @Kemyikpe @NiranjanNlc @Chinex-Boroja 

Since @Kemyikpe already raised a PR, you can look into other issues. @Kemyikpe  I would not merge your PR yet so you could have open PRs to record as your contribution.

**Comment by syedbarimanjan** [comment]
close this as it has been completed.
