### ISSUE TITLE
androidTestUitest Folder not showing up on Android Studio for tables app .

### ISSUE THREAD

**Issue by NiranjanNlc** [opendatakit/tool-suite-X#443]
**Description:**
When opening my project in Android Studio, the androidUiTest folder, which I can locate in the file explorer, is not visible in the  android studio. 

**Steps to Reproduce:**
1. clone the [table project ](https://github.com/odk-x/tables)
2. navigate to the table project and  under src directiry , you will see the androidUiTest folder .
3. Open Android Studio.
4. Load the project  on android studio .
5. Navigate to the tables app/java and check for the "androidUiTest" folder.
6. Observe that the "androidUiTest" folder is missing, even though it exists in the file explorer.

**Expected Results:**
I expect that when I open the project in Android Studio, the "androidUiTest" folder should be visible in the project view, allowing us to play with the test files . 
**Screenshots**
![image](https://github.com/odk-x/tool-suite-X/assets/25600880/462ca013-2bc3-4714-9295-924eb156b1ff)
![image](https://github.com/odk-x/tool-suite-X/assets/25600880/b65987e0-8cb3-46bd-ad05-66f17bc05f69)

**Comment by Chinex-Boroja** [comment]
Hi @wbrunette, I am currently facing this problem in my ODK-X tables_app too.  Without the androidUiTest folder showing, there is no way to locate and run some of the test files in the project. Please is there any other way to resolve this? Thank you

**Comment by NiranjanNlc** [comment]
@Chinex-Boroja , please check my PR , it is easier than we think

**Comment by NiranjanNlc** [comment]
The general convention is to use the "test" folder for unit tests and the "androidTest" folder for instrumented and UI tests. To resolve this issue, we should rename the "androidUITest" folder to "androidTest." After doing so, the content should be recognized and displayed correctly in Android Studio.
Hello @wbrunette @Lamouresparus ,
i have raised the PR for this issuse , but it is still giving some resolve conflict , could you please review my PR.

**Comment by wbrunette** [comment]
I closed your PR with an explanation.
