### ISSUE TITLE
OUTREACHY Create a Test for Services

### ISSUE THREAD

**Issue by Lamouresparus** [opendatakit/tool-suite-X#444]
NOTE: This issue is for Outreachy, you do not need to be assigned to this issue to work on it. It's a generic contribution issue.

**Description**
Outreachy applicants are encouraged to create a test for ODK-X Services to demonstrate their testing abilities and show that they can write effective tests. This issue is open to any applicant who wishes to work on it.

**Task Description**
- Create a new test for ODK-X Services that demonstrates your ability to write test cases.
- The test should cover a specific functionality or feature of ODK-X Services. Please specify which functionality you are testing in the test description.
- Ensure that the test is well-documented and follows best practices for testing.
- The test should be written in the appropriate testing framework used in the ODK-X Services project (e.g., JUnit, Espresso, etc.).
- If necessary, include setup and teardown steps for the test environment.
- The test should provide clear and informative test results.

**Submission Guidelines:**
- Fork the [ODK-X Services repository](https://github.com/odk-x/services).
- Create a new branch for your work.
- Write the test in the designated testing directory of the project.
- Commit and push your changes to your branch.
- Create a pull request with a clear title and description that links back to this issue.
- The pull request will serve as your submission for this task.

**Acceptance Criteria:**
- The test should run successfully without errors.
- The test should provide meaningful coverage for the chosen functionality.
- The test code is well-documented and follows the project's testing guidelines.
- The pull request is created and linked to this issue.

**Comment by Kemyikpe** [comment]
@Lamouresparus please can you assign to me? 🙏🙏🙏

**Comment by wbrunette** [comment]
@Kemyikpe this is is open to everyone.
