### ISSUE TITLE
Setting up Sync Endpoint on Digital Ocean

### ISSUE THREAD

**Issue by Goodiec** [opendatakit/tool-suite-X#465]
When I run a file script_to_run.sh from the console of a digital ocean droplet, at the end I get:
'this node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again'

After I get that error, when I run "docker swam init", I get:
'Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses on interface eth0 (64.23.129.247 and 10.48.0.5) - specify one with --advertise-addr'

Specifying the public IP address explicitly in the script and running the script again works.

![digital-ocean-test](https://github.com/odk-x/tool-suite-X/assets/15726413/dfdde535-27cc-4853-93bc-ac403da90724)

**Comment by r0ssing** [comment]
@Goodiec Did this issue prove to be transitory and fix itself? If so, can we close this issue?

**Comment by Goodiec** [comment]
> @Goodiec Did this issue prove to be transitory and fix itself? If so, can we close this issue?

Yes, it can be closed.
