### ISSUE TITLE
Missing style in the style resource XML file.

### ISSUE THREAD

**Issue by Stryker101** [opendatakit/tool-suite-X#468]
The xml layout for the ChooseSignInTypeFragment  (fragment_choose_sign_in_type) has a missing  style reference on the anonymous sign in button.
![17096540424256256478784862028192](https://github.com/odk-x/tool-suite-X/assets/95471989/f1a78b84-d24e-4a9a-af44-ac971f1611c7)

This was discovered after checking out to the updated  jdk 11 branch. 

Not sure how to proceed with this. Should an already existing style be used in place of this or is this a style that is supposed to be existing?

**Comment by Stryker101** [comment]
@wbrunette @elmps2018 how should i proceed with this ?

**Comment by wbrunette** [comment]
Make sure to use snapshot to flavor to build
