### ISSUE TITLE
Update Services to fix deprecated ViewModelProviders

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#480]
ViewModelProviders. has been deprecated and should be replaced in multiple Java files in Services.

Find the following warning and fix in files with the warning:
[deprecation] ViewModelProviders in androidx.lifecycle has been deprecated
[deprecation] of(FragmentActivity) in ViewModelProviders has been deprecated

**Comment by Arnav2824** [comment]
Hey @wbrunette , I would like to be assigned to this issue.

**Comment by wbrunette** [comment]
@Arnav2824 I have assigned you the issue

**Comment by siva224513** [comment]
Hey @wbrunette  can you assign this issue for me.. if not possible give me another issue

**Comment by Arnav2824** [comment]
Hey @wbrunette , I have made a pull request, please review it and give me your feedback , here is the link for the pull request [https://github.com/odk-x/services/pull/279]

**Comment by Arnav2824** [comment]
Hey @wbrunette , please review my pull request and provide me with your valuable feedback .

**Comment by Redeem-Grimm-Satoshi** [comment]
@Arnav2824 I can see you unassigned yourself from the issue assigned to you by @wbrunette, Is there any reason for that?

**Comment by Arnav2824** [comment]
@Redeem-Grimm-Satoshi , I tried my best to work on the issue but was unable to do it. I did not want to drag it for long unnecessarily, as I couldn't solve it and until I was unassigned no one else would have worked on this issue, that's why I unassigned myself from this issue.

**Comment by siva224513** [comment]
Hi @wbrunette and @Redeem-Grimm-Satoshi, I'm trying to fix this issue. In the first step, I changed ViewModelProviders to ViewModelProvider. After this change, I'm getting the following warnings:

- [deprecation] startActivityForResult(Intent,int) in Fragment has been deprecated
- [deprecation] startActivityForResult(Intent,int) in ComponentActivity has been deprecated

I'm working on fixing these issues. Can I continue with this task?

**Comment by wbrunette** [comment]
Those warnings likely existed before. I suggest keeping them separate.

**Comment by siva224513** [comment]
Hi @wbrunette  @Redeem-Grimm-Satoshi I Raised one pull request but doesn't passing some checks.. let me know how to check locally before create pull request.
