### ISSUE TITLE
Test Driven Development: Write Unit test for File System Upgrade

### ISSUE THREAD

**Issue by Stryker101** [opendatakit/tool-suite-X#499]
Following recent upgrades to the Android System, at a certain API level, the **File.io** system used to create file systems would be deprecated. Google made options for different scenarios available. [Here!](https://source.android.com/docs/core/storage/scoped)

**ODK-X Services** App utilizes the [File](https://developer.android.com/reference/java/io/File) class to create its file system that helps to create files and folders in the app storage.  Following the planned upgrade of the SDK version of the Services app, The File system would be replaced with the android recommended [Scoped Storage](https://source.android.com/docs/core/storage/scoped) API that utilizes Uri to make these operations better. 

The goal is to write test **(Test Driven Development)**, for the current system using the recommend Scoped Storage API, so that when the SDK is updated and the file system is reworked, we would have the tests for this already running.

I would recommend understanding how a file system work in its basic form by creating a "Hello world" project using the File.io API to create, get, edit and delete files or folders. This would help you understand how it works without the complexity of the Services app, with this knowledge you can take on the challenge better equipped.

Your PR should come attached with screenshot of the passing test results.

**Comment by Sonal1319** [comment]
@Stryker101 
Hi Stryker, 
May I ask if this issue was resolved internally or by an Outreachy applicant whom I can get in touch with?

**Comment by Stryker101** [comment]
This issue has been closed.
