### ISSUE TITLE
Improve ODK-X Services Test Coverage: Write Tests for AppPropertiesActivity

### ISSUE THREAD

**Issue by TunrayoIlawole** [opendatakit/tool-suite-X#506]
The AppPropertiesActivity class contains app-level settings
 
**For the `onResume` method, I would like to test for the following when the method is called:**
-  `mAppName` is set to the value passed through the intent
- Fall back to default app name when intent does not provide a value
- `mProps` is initialised with the correct `mAppName`
- Fall back to default app name when `mAppName` is null or an empty string.

**For the `onCreate` method, I would like to test for the following:**
- `appBar` is properly initialised and not null
- clicking the back button calls the `onBackPressed` method
- `mAdminMode` is set correctly based on the intent
- `mAdminConfigured` is properly set based on the admin password
- `preferenceViewModel` is properly initialised and updates the `adminConfigured` and `adminMode` values
- The tool bar title is correctly updated when `adminMode` changes
- `SettingsMenuFragment` is loaded properly when `savedInstanceState` is null.

**For the `onPreferenceStartFragment` method, I would like to test for the following:**
- If `fragment` is `ServerSettingsFragment`, `isFirstLaunch` is set to false if it was previously true
- The method returns false when unrecognised `fragment` is provided
- The correct `bundle` is passed to the `fragment`

These tests aims to increse test coverage of ODK-X services.
This issue addresses #504

**Comment by TunrayoIlawole** [comment]
Hi @Lamouresparus, kindly assign this to me

**Comment by Lamouresparus** [comment]
@TunrayoIlawole 
I will suggest you work on #507  first, as that is more beginner friendly, before working on this. But if you feel confident, you can go ahead :)

**Comment by TunrayoIlawole** [comment]
Sure thing, @Lamouresparus . I will look into #507
