### ISSUE TITLE
Feature request: app designer grunt with custom port

### ISSUE THREAD

**Issue by nullcode** [opendatakit/tool-suite-X#70]
8000 is hardcoded into the app, changing it only in the grunt config will result in undesired functionality. Would be good to have a grunt option to customise this port.

**Comment by wbrunette** [comment]
Pull request https://github.com/opendatakit/app-designer/pull/108

**Comment by maprehensive** [comment]
@wbrunette - should this be In Progress on the Roadmap if there's a pull request associated?

**Comment by wbrunette** [comment]
Revised pull request https://github.com/opendatakit/app-designer/pull/121

**Comment by wbrunette** [comment]
Released in 2.1.4
