### ISSUE TITLE
Generate QR code for configured server setting in Service app 

### ISSUE THREAD

**Issue by laddha-adi** [opendatakit/tool-suite-X#76]
Services should be modified to add a button that generates and display a QR code, containing information about server setting's current configuration.
Examples of how JSON Object for QR code would look like-
For anonymous configuration

```
{
  "url": "https://yoururl.appspot.com"
}
```
For username-password configuration

```
{
 "url": "https://yoururl.appspot.com",
"username":"username",
"password":"password"
}
```
**Would you like to work on this issue?** 
Yes

**Comment by linl33** [comment]
Fixed by opendatakit/services#72
